- starfish/watershedsegmenter.py
This is an almost verbatim re-implementation of centrosome.cpmorphology.relabel, only very subtle changes (use of a set object instead of np.unique, stylistic alterations). 
centrosome uses a BSD-3 license, which might clash with the MIT license on starfish as I believe BSD-3 propagates.
In the absence of specific unit tests, I've run this without error on the Mignardi notebook.
> add remimplementation of centrosome.cpmorphology.relabel

- REQUIREMENTS.txt
- setup.py
- starfish/filters.py
- starfish/io.py
- starfish/register.py
- starfish/starfish.py
A few changes to make this a pip-installable package.
> Reorganize into a package

- examples/get_iss_data.py
- starfish/io.py
- starfish/starfish.py
Re-factor io.stack to read from a json file instead of two csv files.
> Input format

- setup.py
- starfish.wdl
- starfish_example_inputs.json
Makes a few changes to the WDL so it runs on the HCA green box. Also fixes package discovery in the setup.py. It was missing stuff like starfish.spots before.
> Run starfish in the green box

- MANIFEST.in
- setup.py
Test plan:
```
% python setup.py sdist bdist_wheel upload
```
then in a different directory, ran:
```
pip install starfish && starfish
```
> Fix pip deployment.

- README.md
1. Simplified "install it from pypi!" for non-developers.
2. Setup instructions for new people who want to bang on the code.
> Documentation updates for running/developing on starfish.

- starfish/starfish.py
This allows things like python -m starfish.starfish
> add code to start up starfish if the module is started.

- starfish/starfish.py
It's nice to have starfish --help take up less time.
```
[czipa1osx186 (.venv)]:~/microscopy/starfish:tonytung-startup-time> time python -m starfish.starfish
real	0m0.087s
user	0m0.067s
sys	0m0.012s
```
Previously, it was 1.2s.
> Demand-import for the top level starfish cli.

- .travis.yml
- Makefile
- REQUIREMENTS-DEV.txt
- REQUIREMENTS.txt
- starfish/util/clock.py
- tests/test_iss_data.py
This takes the instructions from `README.md` and turns it into an integration test.
Also this adds:
1. A `REQUIREMENTS-DEV.txt`, which is a superset of `REQUIREMENTS.txt` and includes what is needed for running tests.
2. A `Makefile` with rules for tests and lint.  Lint is currently disabled as there's a ton of stuff that doesn't pass lint right now.
> ISS data integration test.

- starfish/starfish.py
- starfish/util/argparse.py
- tests/test_profiler.py
Trying to modularize starfish with click is turning out to be real nightmare.  The reason is that click is very procedurally oriented, whereas applying an OO pattern to the various pipeline stages requires a tremendous amount of hackery.
> switch to using argparse instead of click.

- starfish/registration/__init__.py
- starfish/starfish.py
- tests/test_iss_data.py
Changed maxproject into a specific algorithm of registration to enable multiple algorithms.
> Move registration into its own module.

- starfish/__init__.py
- starfish/registration/__init__.py
- starfish/registration/_base.py
- starfish/registration/_fourier_shift.py
Creates a base class for registration algorithms.  As long as the individual algorithms are imported into registration/__init__.py, they will be auto-discovered and be made available to the CLI / python API.
> base class for registration

- REQUIREMENTS.txt
- starfish/filters.py
> Remove opencv as a dependency for Starfish filters

- starfish/registration/__init__.py
```
[czipa1osx186 (.venv)]:~/microscopy/starfish:tonytung-trampoline> ipython
Python 3.6.1 (default, Jul 21 2017, 16:04:09)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from starfish.registration import Registration
In [2]: Registration.fourier_shift.__doc__
Out[2]: '\n    Implements fourier shift registration.  TODO: (dganguli) FILL IN DETAILS HERE PLS.\n    '
In [3]:
```
> Automagically create trampolines to the algorithms

- starfish/pipeline/pipelinecomponent.py
- starfish/pipeline/registration/__init__.py
A lot of this logic will be common for each pipeline component, so let's dedup in advance.
Depends on #84
> Move common logic for pipeline components to pipeline module.

- starfish/starfish.py
- tests/test_iss_data.py
CSV is a pain to parse, and is not future-proof.
> use json as the interchange medium.

- CONTRIBUTING.md
> Skeleton for CONTRIBUTING.md

- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.py
- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- notebooks/Starfish_simulation.py
This should unbreak the test breakage introduced in #81
> Add missing notebooks in .py format

- starfish/munge.py
Default is the current, which is just the hull.
This is necessary if we want the gene assignment stage to be its own pipeline stage, since this is the output of segmentation and the input for gene assignment.
> Give the option of outputting the region coordinates to geojson.

- notebooks/subdir.mk
They were wrong.  Not sure how I ran them to success before. :(
> Fix regenerate rules.

- starfish/image/_stack.py
#39 didn't do the code transformation correctly, and `self.data` should be `self._data`.
> Fix max_proj

- setup.py
We need to release a new pip package to deal with issues like #124
> bump version.

- Makefile
- REQUIREMENTS-DEV.txt
- starfish/starfish.py
This checks type hints.  There's a change to strip a python2 import that mypy freaked out about.
> Enable mypy for the repo

- starfish/starfish.py
> Don't call squeeze/unsqueeze for filter.

- README.md
- REQUIREMENTS.txt
- examples/get_iss_data.py
- starfish/image/__init__.py
- starfish/image/_base.py
- starfish/image/_stack.py
- starfish/io.py
- starfish/pipeline/decoder/_iss.py
- starfish/starfish.py
- tests/test_iss_data.py
Modified to use https://github.com/ttung/slicedimage
> RFC: New input format for starfish

- starfish/image/_stack.py
- starfish/io.py
This is required for 3d support.
> Support max projection along multiple axes.

- starfish/image/_stack.py
- starfish/io.py
- starfish/pipeline/registration/fourier_shift.py
- starfish/starfish.py
I made some guesses for what might make sense for fourier_shift and stain creation.
Depends on #126, #129, #130
> Support for 3D stacks.

- starfish/starfish.py
If we filter the hybridization images last, we can do it in-place rather than create a new array.
Depends on #131
> [easy] Filter hybridization images last.

- starfish/io.py
The new shape should be (#hybs, #chs, #layers) + tile_shape.
> unsqueeze is not z-aware

- starfish/io.py
Match the API change in https://github.com/spacetx/slicedimage/pull/6
> Update resolve_url call point.

- REQUIREMENTS.txt
- starfish/io.py
Go back to `resolve_url`, which better describes the functionality.
> Revert #145

- README.md
> Update link to notebook.

- starfish/io.py
https://github.com/spacetx/slicedimage/pull/6 introduced the ability to resolve a path or a URL.  Employ that to allow Stack().read() to accept arbitrary URLs or paths.
Depends on #145
> Use new path resolution primitives to resolve paths

- REQUIREMENTS.txt
- examples/get_iss_data.py
- starfish/image/_stack.py
- tests/test_get_slice_api.py
- tests/test_set_slice_api.py
Incorporate the renaming in https://github.com/spacetx/slicedimage/pull/12
> Update to latest slicedimage

- tests/test_apply.py
It was using the old slicedimage API.
> Fix test_apply

- examples/build_sample_experiment.py
To run, this requires:
https://github.com/spacetx/slicedimage/pull/7
https://github.com/spacetx/slicedimage/pull/8
https://github.com/spacetx/slicedimage/pull/9
https://github.com/spacetx/slicedimage/pull/10
> Script to generate a multi-FOV 3D synthetic input set

- starfish/munge.py
- starfish/pipeline/segmentation/__init__.py
- starfish/pipeline/segmentation/_base.py
- starfish/pipeline/segmentation/watershed.py
- starfish/starfish.py
- tests/test_iss_data.py
> Refactor segmentation into PipelineComponent.

- REQUIREMENTS.txt
- starfish/image/_stack.py
- starfish/pipeline/filter/bandpass.py
- starfish/pipeline/filter/clip.py
- Implementation of `clip` and `bandpass` methods needed for `allen-smFISH` notebook using `pipeline_component`
> allen-smFISH filters

- examples/build_sample_experiment.py
- starfish/pipeline/pipelinecomponent.py
- starfish/util/argparse.py
> Get rid of the (object) superclass.

- starfish/image/_base.py
- starfish/image/_stack.py
- starfish/io.py
Also add from_url(..) to base class.
> [easy] rename from_image_stack

- examples/build_sample_experiment.py
Added logic to skip over auxiliary images that are not specified.
> [auximg 1/13] [easy] Don't make any single aux image required.

- REQUIREMENTS.txt
fix in question: https://github.com/spacetx/slicedimage/pull/13
> [auximg 3/13] [easy] Upgrade slicedimage to pick up bugfix

- examples/build_sample_experiment.py
Missed this earlier.  Now the FOVs generate pretty names.
> [auximg 7/13] [easy] wire up tile opener

- examples/build_sample_experiment.py
Following up on https://github.com/spacetx/starfish/pull/213#discussion_r190770048
> [easy] rename DumbFetchedImage to RandomNoiseImage

- starfish/pipeline/algorithmbase.py
- starfish/pipeline/features/_validated_table.py
- starfish/pipeline/features/spot_attributes.py
- starfish/pipeline/features/spots/decoder/__init__.py
- starfish/pipeline/features/spots/detector/__init__.py
- starfish/pipeline/filter/__init__.py
- starfish/pipeline/filter/clip.py
- starfish/pipeline/filter/gaussian_low_pass.py
- starfish/pipeline/gene_assignment/__init__.py
- starfish/pipeline/pipelinecomponent.py
- starfish/pipeline/registration/__init__.py
- starfish/pipeline/segmentation/__init__.py
- Fixes some minor problems with my previous PRs related to typing
- Adds hints for uninitialized argparse.ArgumentParser objects to PipelineComponents
- reassign `id` -> `id_` to avoid clobbering builtin `id` method
- Assigned an errant TODO
> add type hints

- CONTRIBUTING.md
What's still missing from this doc?
> RFC: Updated Contributing.md

- README.md
- setup.py
- minor changes to installation instructions as well. 
- replaced inline code blocks with code strings, was making my editor go crazy.
> [DOC] Clarify python3.6+ Support in README and setup.py

- starfish/pipeline/features/spots/detector/gaussian.py
Additional changes:
- Rather than using astype, which clips floating values, use round(..) which rounds.
> Clip the spot detection coordinates to the image.

- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.py
This will detect unexpected results, hopefully.
> Rough verification of ISS pipeline results

- starfish/pipeline/features/pixels/__init__.py
- starfish/pipeline/features/spots/detector/__init__.py
- starfish/pipeline/features/spots/detector/local_max_peak_finder.py
- starfish/pipeline/filter/__init__.py
- starfish/pipeline/filter/richardson_lucy_deconvolution.py
I forgot you had to do this while I was lifting them over. 
Also tagging Charlotte on everything now because Tony does. 
Closes #255
> [BUG] fix pipeline component imports

- starfish/test/dataset_fixtures.py
- starfish/test/image/test_imagestack.py
- starfish/test/test_apply.py
The model is https://docs.pytest.org/en/latest/fixture.html#factories-as-fixtures
> [easy] Turn synthetic_stack into a factory.

- notebooks/Starfish_simulation.py
The synthetic notebook got pushed to master without updating the encoding. Here's an update that un-breaks the tests.
> BUG: [easy] update notebook encoding

- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.py
- notebooks/ISS_Simple_tutorial_-_Mouse_vs._Human_Fibroblasts.ipynb
- notebooks/ISS_Simple_tutorial_-_Mouse_vs._Human_Fibroblasts.py
- starfish/pipeline/features/spots/detector/__init__.py
- starfish/pipeline/features/spots/detector/_base.py
- starfish/pipeline/features/spots/detector/gaussian.py
- starfish/pipeline/features/spots/detector/local_max_peak_finder.py
- starfish/test/full_pipelines/api/test_iss_api.py
- starfish/test/full_pipelines/cli/test_iss.py
> Extricate Stack from spot detection.

- .travis.yml
- Dockerfile
Happy to also enable building of this in .travis if useful.
> docker: add Dockerfile which runs starfish by default

- .travis.yml
- notebooks/subdir.mk
This way, we can ensure that our users don't see broken behavior.
> Run the notebooks using the pip package on master

- starfish/pipeline/filter/richardson_lucy_deconvolution.py
- This filter was missing a verbosity flag.
> BUG: add missing verbosity flag

- starfish/image/_stack.py
- starfish/test/dataset_fixtures.py
- starfish/test/image/test_imagestack.py
- starfish/test/image/test_imagestack_metadata.py
- starfish/test/image/test_slicedimage_dtype.py
- starfish/test/test_apply.py
> Move synthetic_stack to ImageStack

- starfish/io.py
Stacks are only read from the top of the experiment.
Connects to #48
> Remove write methods from Stack.

- starfish/image/_stack.py
Allow it to store more information about the dimensions.
This change adds a `required` field but does not utilize it.
> Generalize the AXES_MAP structure.

- REQUIREMENTS.txt
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.py
- starfish/codebook.py
- starfish/test/pipeline/test_codebook.py
- Simple addition to the `Codebook` constructor to let us grab it from the web.
> Ajc make codebook downloadable

- starfish/image/_stack.py
Currently, the shape is not controlled by AXES_DATA.  This constructs the shape using the data in AXES_DATA.
This also changes how we fetch the dimensions, where we get it dynamically from the backing image instead of populating it at ImageStack construction.
Depends on #330
> Construct the data array using the data in AXES_DATA.

- starfish/pipeline/filter/gaussian_high_pass.py
I just fixed a small typo in the docstring for the Gaussian High Pass filter.
> fixed doc for high_pass method in the GHP filter

- starfish/pipeline/features/pixels/__init__.py
- starfish/pipeline/features/pixels/combine_adjacent_features.py
- starfish/pipeline/features/pixels/pixel_spot_detector.py
- starfish/test/pipeline/test_intensity_table.py
- Updates pixel_spot_detector pipeline component to use IntensityTable and Codebook objects.
> [6/8] ENH: update the pixel spot detector to use IntensityTable and Codebook

- REQUIREMENTS.txt
- starfish/io.py
- starfish/test/test_version.py
> Check the version in the file to see if we support it.

- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.py
- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.ipynb
- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- notebooks/allen_smFISH.ipynb
- notebooks/allen_smFISH.py
- starfish/io.py
- starfish/test/dataset_fixtures.py
Point all the notebooks to the 1.0.0 versions.
> Bump MIN_SUPPORTED_VERSION to 1.0.0

- notebooks/ISS_Simple_tutorial_-_Mouse_vs._Human_Fibroblasts.ipynb
- notebooks/ISS_Simple_tutorial_-_Mouse_vs._Human_Fibroblasts.py
- starfish/pipeline/segmentation/__init__.py
- starfish/pipeline/segmentation/_base.py
- starfish/pipeline/segmentation/watershed.py
- starfish/stats.py
* improve typing
* f-style strings
* `segment` becomes `run`
> ENH: update watershed API

- starfish/pipeline/filter/clip.py
- line length 100
- type parameters
- type return vals
- move verbose to `run`
- make all docs adhere to numpydoc
> ENH: harmonize clip code/API

- starfish/pipeline/filter/gaussian_high_pass.py
- starfish/pipeline/filter/gaussian_low_pass.py
- starfish/pipeline/filter/mean_high_pass.py
- starfish/pipeline/filter/richardson_lucy_deconvolution.py
- starfish/test/pipeline/test_filter.py
* gaussian_high_pass
* gaussian_low_pass
* mean_high_pass
* richardson_lucy_deconvolution
Minor updates to: 
- line length
- documentation
- adding types
- moving verbose to `run`
> ENH: minor filter algorithm consistency updates

- notebooks/osmFISH.ipynb
- notebooks/osmFISH.py
- Add osmFISH notebook
- Make the notebook run on master
> ENH: add osmFISH notebook that loads and displays data

- notebooks/allen_smFISH.ipynb
- notebooks/allen_smFISH.py
max_proj should be called with the indices directly.
> Fix allen smFISH notebook

- .flake8
- examples/build_sample_experiment.py
- examples/get_iss_data.py
- examples/support/__init__.py
- starfish/image/_stack.py
- starfish/intensity_table.py
- starfish/io.py
- starfish/munge.py
- starfish/pipeline/features/_validated_table.py
- starfish/pipeline/features/pixels/pixel_spot_detector.py
- starfish/pipeline/features/spots/detector/gaussian.py
- starfish/pipeline/features/spots/detector/local_max_peak_finder.py
- starfish/pipeline/filter/mean_high_pass.py
- starfish/pipeline/pipelinecomponent.py
- starfish/pipeline/segmentation/watershed.py
- starfish/starfish.py
- starfish/test/dataset_fixtures.py
- starfish/test/full_pipelines/api/test_merfish.py
- starfish/test/full_pipelines/cli/test_iss.py
- starfish/test/image/test_apply.py
- starfish/test/image/test_slicedimage_dtype.py
- starfish/test/pipeline/test_intensity_table.py
We never actually finished doing this. Now we have. :)
> Switch to 100col to make starfish follow slicedimage. 

- notebooks/osmFISH.ipynb
- notebooks/py/osmFISH.py
- Fixes a failing notebook to save the master build.
> fix osmFISH notebook

- starfish/stack.py
Adding a the tqdm progress bar lib to stack.read()
> Progress bar

- examples/get_iss_data.py
- starfish/experiment/__init__.py
- starfish/experiment/builder/__init__.py
- starfish/experiment/builder/cli.py
- starfish/experiment/builder/imagedata.py
This is the package for interacting with and creating experiment objects.
1. Rename starfish/experiment.py to starfish/experiment/__init__.py
2. Move examples/support/__init__.py into starfish/experiment/
3. Rename examples/build_sample_experiment.py to starfish/experiment/builder/cli.py
> Create experiment package.

- REQUIREMENTS.txt
- setup.py
This adds caching for slicedimage.
> Upgrade slicedimage and bump starfish version

- REQUIREMENTS.txt
- setup.py
Release starfish 0.0.13 as well.
> Bump slicedimage to 0.0.1

- starfish/image/_filter/gaussian_high_pass.py
- starfish/image/_filter/gaussian_low_pass.py
- starfish/image/_filter/util.py
* Gaussian filters were not handling verbosity properly.
* Multichannel should be false for our images, as the last axis does not
contains multi-channel data.
> BUG: fix verbosity handling and set multichannel false

- starfish/image/_registration/_base.py
- starfish/image/_registration/fourier_shift.py
Enables out-of-place registration.
> ENH: enable out-of-place-registration

- starfish/spots/_target_assignment/__init__.py
- starfish/spots/_target_assignment/_base.py
- starfish/spots/_target_assignment/point_in_poly.py
- starfish/test/full_pipelines/cli/test_iss.py
TargetAssignment now returns an IntensityTable augmented with cell ids.
> ENH: updated target assignment to augment the IntensityTable 

- starfish/stack.py
All the builders should be together.
> [easy] group all the builder methods together

- notebooks/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.ipynb
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/allen_smFISH.ipynb
- notebooks/py/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.py
- notebooks/py/ISS_Pipeline_-_Breast_-_1_FOV.py
- notebooks/py/allen_smFISH.py
This is a one-time deal (hopefully!) so I didn't bother building a proper tool to do this.
> Point to data that has correct checksums.

- starfish/image/_filter/white_tophat.py
There was a skimage.morphology.white_tophat function that replicates the functionality of ours. The only thing to note is that attempts to pass a structuring element that exceeds the size of the array will throw an error for the new function.
> ENH: replace white_tophat with skimage function that accepts floats

- starfish/spots/_detector/combine_adjacent_features.py
Unbreak the build, fix a bad refactor.
> BUG: fix build

- docs/fov-builder.md
Adds a README.md file for the FOV builder tool.
> DOC: add readme for fov builder tool

- README.md
Adds a simple bibtex citation to the README.
> DOC: Add starfish citation

- REQUIREMENTS.txt
- examples/get_iss_data.py
- starfish/experiment/__init__.py
Some minor changes were required to get things to run.
> Bump slicedimage version.

- README.md
- starfish/spots/_decoder/__init__.py
- starfish/spots/_decoder/per_round_max_channel_decoder.py
- starfish/spots/_decoder/per_round_max_decoder.py
- starfish/test/full_pipelines/cli/test_iss.py
Update the naming to reflect the code base.
> [Easy] ENH: rename ISS decoder to PerRoundMaxDecoder

- notebooks/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.ipynb
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.ipynb
- notebooks/allen_smFISH.ipynb
- notebooks/osmFISH.ipynb
- notebooks/py/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.py
- notebooks/py/ISS_Pipeline_-_Breast_-_1_FOV.py
- notebooks/py/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- notebooks/py/allen_smFISH.py
- notebooks/py/osmFISH.py
- setup.py
- starfish/experiment/__init__.py
- starfish/test/dataset_fixtures.py
- starfish/test/full_pipelines/api/test_allen_smFISH.py
- starfish/test/full_pipelines/api/test_dartfish.py
- starfish/test/full_pipelines/api/test_iss_api.py
- starfish/test/full_pipelines/api/test_merfish.py
- starfish/test/pipeline/test_filter.py
I haven't converted the existing code or notebooks to use this API, but I'll paste in a few sample runs.
> RFC: experiment API

- starfish/image/_filter/gaussian_high_pass.py
- starfish/stack.py
- starfish/test/pipeline/test_filter.py
Not for merging, and doesn't work, but is probably easy to fix and could be a fun place to work together on this @ambrosejcarr. Also, why doesn't it work (e.g., pass unit tests)?
> Initial pass at apply

- starfish/codebook.py
- starfish/image/_filter/white_tophat.py
- starfish/spots/_detector/combine_adjacent_features.py
- starfish/spots/_detector/gaussian.py
- starfish/spots/_detector/local_max_peak_finder.py
Removes unnecessary line continuation markers.
> [easy] Fix line wrapping

- validate_sptx/util.py
- validate_sptx/validate_sptx.py
Migrated from https://github.com/spacetx/sptx-format/pull/21
> Validation output

- .flake8
- Makefile
- starfish/starfish.py
- starfish/util/exec.py
- validate_sptx/test_codebook.py
- validate_sptx/test_experiment.py
- validate_sptx/test_field_of_view.py
- validate_sptx/test_fov_manifest.py
- validate_sptx/test_fuzz.py
- validate_sptx/util.py
- validate_sptx/validate_sptx.py
Turns out most of the errors are my own. :/
> Fix lint errors and re-enable lint checking

- starfish/test/image/test_slicedimage_dtype.py
It's convert to float, then merge.  Right now, we're merging and then converting to float.
This fixes the tests in `starfish/test/image`
> Follow the same conversion steps as ImageStack would be for the conversion tests

- notebooks/assay_comparison.ipynb
- notebooks/py/assay_comparison.py
Reverts spacetx/starfish#534
... because I removed the wrong notebook.
> Revert "Remove prematurely added notebook"

- notebooks/assay_comparison.ipynb
- notebooks/py/assay_comparison.py
This was inadvertently removed in #501.
> Re-add assay_comparison.py

- starfish/image/_filter/__init__.py
- starfish/image/_registration/__init__.py
- starfish/image/_segmentation/__init__.py
- starfish/pipeline/__init__.py
- starfish/pipeline/pipelinecomponent.py
- starfish/spots/_decoder/__init__.py
- starfish/spots/_detector/__init__.py
- starfish/spots/_target_assignment/__init__.py
It's like a tad less boiler plate. :)
Fixes #112
> Converted implementing_algorithms to get_algorithm_base_class

- starfish/experiment/builder/__init__.py
1. hybridization -> primary_image
2. hybridization (in terms of round) -> round.
Test plan: `python examples/get_iss_breast_data.py /Users/ttung/Downloads/starfish_data/mignardi_breast_1/raw/ ../starfish-formatted-data/breast/`
> Remove hybridization

- docs/source/API/image/filtering/filtering.rst
- docs/source/API/image/registration/registration.rst
- docs/source/API/image/segmentation/segmentation.rst
- starfish/image/_filter/richardson_lucy_deconvolution.py
Hook up everything in starfish.image to the docs.
> DOC: link image classes to docs

- docs/source/API/plot/plot.rst
- starfish/plot/decoded_spots.py
- starfish/plot/histogram.py
- Adds a doc for plots. 
- Fixes some plotting docstrings.
> DOC: plot docs

- .travis.yml
Caching the cache dir between builds.
> travis caching

- docs/source/API/types/types.rst
> DOC: add types doc

- starfish/experiment/builder/__init__.py
It's just a fallback value anyway.
> Make default shape optional for the experiment builder

- validate_sptx/schema/codebook/codebook.json
- validate_sptx/schema/codebook/codeword.json
- validate_sptx/schema/experiment.json
- validate_sptx/schema/extras.json
- validate_sptx/schema/field_of_view/field_of_view.json
- validate_sptx/schema/fov_manifest.json
- validate_sptx/schema/version.json
Fixes https://github.com/spacetx/starfish/issues/529
> Point schema $ID fields to their new home in starfish

- starfish/imagestack/imagestack.py
It is an optimization that seems to just complicate things.
Test plan: make -j all run_notebooks
> Always copy from the imagestack numpy array to the tiles when writing back

- notebooks/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.ipynb
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/allen_smFISH.ipynb
- notebooks/assay_comparison.ipynb
- notebooks/py/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.py
- notebooks/py/ISS_Pipeline_-_Breast_-_1_FOV.py
- notebooks/py/allen_smFISH.py
- notebooks/py/assay_comparison.py
- starfish/image/_filter/bandpass.py
- starfish/image/_filter/clip.py
- starfish/image/_filter/gaussian_high_pass.py
- starfish/image/_filter/gaussian_low_pass.py
- starfish/image/_filter/mean_high_pass.py
- starfish/image/_filter/richardson_lucy_deconvolution.py
- starfish/image/_filter/scale_by_percentile.py
- starfish/image/_filter/white_tophat.py
- starfish/image/_filter/zero_by_channel_magnitude.py
- starfish/image/_registration/fourier_shift.py
- starfish/imagestack/imagestack.py
- starfish/test/image/test_apply.py
- starfish/test/pipeline/test_filter.py
Default is out-of-place.
Depends on #598 
Fixes #384
> Make in-place opt-in.

- docs/source/usage/fov-builder/fov-builder.md
- docs/source/usage/index.rst
- docs/source/usage/iss/iss_pipeline.py
- docs/source/usage/iss/iss_vignette.rst
- examples/get_iss_breast_data.py
Adds an ISS Vignette. Not yet ready for review. 
Testing strategy: 
```
make docs-html
open docs/build/html/index.html
```
navigate to Starfish Usage -> In-Situ Sequencing & Read!
> Add complete multi-fov ISS vignette

- .travis.yml
- starfish/image/_filter/gaussian_high_pass.py
- starfish/image/_filter/gaussian_low_pass.py
- starfish/image/_filter/mean_high_pass.py
- starfish/image/_filter/richardson_lucy_deconvolution.py
- starfish/image/_filter/util.py
> Making clip above 1 default behavior in preserve_float_range

- starfish/image/_filter/mean_high_pass.py
As requested in #590 , this PR modernizes the mean high pass filter to reflect the change to floats for all image data in the starfish pipeline.
* removes type check
* uses new kernal shape check function
* updated docstrings
> Modernize MeanHighPass

- examples/get_merfish_u20s_data.py
Fixes https://github.com/spacetx/starfish/issues/657
> The tile_data method should be a @property

- starfish/imagestack/imagestack.py
- starfish/test/image/test_imagestack.py
fixes #591
test plan: wrote new test test in test_imagestack.py
> Converting to float32 in Imagestack.from_numpy_array()

- starfish/test/pipeline/test_filter.py
To address issue #636, I added tests for the mean high pass filter a la GaussianHighPass().
> Add tests for mean high pass filter

- starfish/test/dataset_fixtures.py
> [easy] Remove unused test fixture.

- starfish/image/_filter/util.py
Since all the operations are in-place, we can just manipulate either the numpy array (if the source is a numpy array) or xr.values (if the source is a DataArray).  This simplifies the code a bit.
> Simplify `preserve_float_range`

- starfish/spots/_detector/local_max_peak_finder.py
> Fix IntensityTable import.

- starfish/spots/_detector/detect.py
I didn't address https://github.com/spacetx/starfish/pull/686#discussion_r224942421 because that's my question...
> [easy] Fix post-land comments from #686

- examples/get_merfish_u20s_data.py
1. Sped up performance by caching the decoded image between tiles.  This sped up the construction of the MERFISH dataset from 1 hour to 6 minutes.
2. Provide fake coordinates for the aux tiles.
Test plan:
```
[tt (.venv)]:~/microscopy/starfish:tonytung-destroy> time python examples/get_merfish_u20s_data.py /Users/ttung/Downloads/starfish_data/moffit_u20s/dataByFOV/ ../starfish-formatted-data/moffit
real	6m20.311s
user	3m43.367s
sys	2m14.348s
```
Depends on #668
> Improve and fix MERFISH formatter

- docs/source/API/core_objects/expression_matrix.rst
- starfish/expression_matrix/expression_matrix.py
- starfish/intensity_table/intensity_table.py
- starfish/util/try_import.py
Early PR for feedback on linking `IntensityTable` to an `ExpressionMatrix` (2d genes x cells) object that can be exported to `loom` and `AnnData` for use in `Scanpy` and `Seurat`
Before I write tests, do we like how this looks? Anything anyone would change or add?
> RFC: Add Expression Matrix + Links to Seurat & Scanpy

- README.rst
- docs/source/introduction/introduction.rst
Updates and synchronizes the README files
> Update project status

- starfish/imagestack/imagestack.py
I suck with words, so would appreciate tips on improving the verbiage.
> Fix docs for apply and transform.

- notebooks/allen_smFISH.ipynb
- notebooks/py/allen_smFISH.py
1. API changes
2. Remove skip file
Depends on #742 
Test plan: https://travis-ci.org/spacetx/starfish/builds/445978652
> Fix allen notebook & enable it.

- starfish/experiment/builder/orderediterator.py
- starfish/test/experiment/builder/test_orderediterator.py
Given a discrete n-dimensional space, return an iterator that varies across that space.  The user picks the ordering of how dimensions vary, from slowest varying to fastest varying.
Test plan: see unit tests
> Methods to build iterators across a discrete n-dimensional space

- starfish/experiment/builder/__init__.py
We can vary which dimensions vary the fastest.
Depends on #757 
Test plan: `python examples/get_iss_data.py /tmp/starfish/raw /tmp/starfish/formatted --d 1`
> Dimension iteration order can be configured in the experiment builder.

- starfish/intensity_table/concatenate.py
- starfish/test/intensity_table/test_concatenate.py
Accidentally merged this into a feature branch. It's approved here: 
https://github.com/spacetx/starfish/pull/716
> Add concatenation function to merge multiple intensity tables over FOVs

- examples/format_osmfish.py
- notebooks/osmFISH.ipynb
- notebooks/py/osmFISH.py
- starfish/data/__init__.py
- Add osmFISH `TileFetcher`
- Add hook for processed `osmFISH` data in `starfish.data`
- Change order of iteration over axes in builder tools (round -> ch -> z) where z is changing fastest.
> Add updated osmFISH data that includes full FOVs.

- starfish/imagestack/imagestack.py
- starfish/starfish.py
> Remove show command and its support code.

- environment.yml
This has fallen somewhat behind. Here's a big bump.
> conda: bump slicedimage requirement

- starfish/imagestack/imagestack.py
Instead of using the coordinates, use Indices.Z.
Removed a bunch of extraneous code.
Test plan:
```
import os
from starfish import data, ImageStack, FieldOfView
use_test_data = os.getenv("USE_TEST_DATA") is not None
experiment = data.allen_smFISH(use_test_data=use_test_data)
primary_image = experiment.fov()[FieldOfView.PRIMARY_IMAGES]
primary_image.write('test_raw')
test_raw = ImageStack.from_path_or_url('test_raw.json')
```
Depends on #790
> Fix how we assign number to zlayers.

- REQUIREMENTS.txt
- REQUIREMENTS.txt.in
PR in question: https://github.com/spacetx/slicedimage/pull/77
> Bump slicedimage requirements to pick up fix for multi-level images

- starfish/imagestack/imagestack.py
> [easy] Provide a simple example for ImageStack.coordinates(..)

- starfish/imagestack/physical_coordinate_calculator.py
This is needed for crop-on-load.
> [easy] expose `recalculate_physical_coordinate_range`

- starfish/imagestack/imagestack.py
> [easy] Fix documentation for ImageStack.sel

- starfish/imagestack/imagestack.py
- starfish/pipeline/algorithmbase.py
- starfish/pipeline/pipelinecomponent.py
Adds documentation to close #233 
@ttung I took a stab at this, but your edits here would be welcome.
> add docs for PipelineComponent and AlgorithmBase

- docs/source/glossary/glossary.md
These stem from https://github.com/spacetx/starfish/pull/922#pullrequestreview-188564833
> RFC: clarify FOV, image tile, and coordinates in glossary.

- Makefile
- docs/source/usage/fov-builder/fov-builder.rst
- docs/source/usage/iss/iss_cli.sh
- docs/source/usage/iss/iss_vignette.rst
- examples/get_cli_test_data.py
- examples/get_merfish_u20s_data.py
- starfish/experiment/builder/__init__.py
- starfish/experiment/builder/cli.py
- starfish/image/_segmentation/_base.py
- starfish/imagestack/imagestack.py
- starfish/spots/_detector/_base.py
- starfish/spots/_detector/local_max_peak_finder.py
- starfish/spots/_detector/trackpy_local_max_peak_finder.py
- starfish/test/full_pipelines/cli/test_allen_smFISH_cli.py
- starfish/test/full_pipelines/cli/test_build.py
- starfish/test/full_pipelines/cli/test_dartfish_cli.py
- starfish/test/full_pipelines/cli/test_iss.py
- starfish/test/full_pipelines/cli/test_merfish_cli.py
- starfish/test/intensity_table/test_from_imagestack.py
Test plan: `make -j lint mypy fast`
Fixes #623
> Get rid of remaining references to hyb

- examples/format_starmap.py
Created a TileFetcher for StarMAP data.
Later PRs will add this to `starfish.data` and create a vignette.
> Add StarMAP tilefetcher

- readthedocs.yml
Attempt to install self.
Test plan: this seemed to work..? https://spacetx-starfish.readthedocs.io/en/tonytung-rtd/api/core_objects/image_stack.html
Plausibly Fixes #989
> fix readthedocs

- starfish/starfish.py
see: https://github.com/spacetx/starfish/pull/1026
> put install command under util

- docs/source/usage/validation/index.rst
- sptx_format/cli.py
- sptx_format/test_codebook.py
- sptx_format/test_experiment.py
- sptx_format/validate_sptx.py
- starfish/test/full_pipelines/cli/test_build.py
- starfish/test/full_pipelines/cli/test_iss.py
> validate: add further commands

- starfish/image/_filter/linear_unmixing.py
- starfish/test/image/filter/test_linear_unmixing.py
Accidentally merged this into the wrong branch. See #1045
> Add linear unmixing pipeline component

- docs/source/usage/iss/iss_cli.sh
This PR update ISS pipeline doc as bash script wasn;t up to date
> clean up ISS pipeline

- starfish/codebook/codebook.py
- starfish/test/codebook/test_from_code_array.py
- starfish/test/dataset_fixtures.py
1. n_ch ==> n_channel
2. fix docblocks.
Test plan: `pytest -n4 -v starfish/test/codebook/`
Fixes #1033
> [easy] fix consistency of codebook

- sptx_format/cli.py
see: https://github.com/spacetx/starfish/pull/1043#pullrequestreview-210420194
> [easy] Replace 'file' with 'path'

- docs/source/usage/index.rst
This PR adds usage suggestions to starfish that reflect the current state of development. 
@ttung when this is merged, I think this would be the appropriate place to add information about how to work with _starfish_ given our currently memory architecture.
> add usage instructions

- starfish/imagestack/imagestack.py
- starfish/imagestack/parser/_tiledata.py
- starfish/imagestack/parser/crop.py
- starfish/imagestack/parser/numpy/__init__.py
- starfish/imagestack/parser/tileset/__init__.py
- starfish/imagestack/parser/tileset/_parser.py
This simplifies the constructor a bit.
This is built on top of #1032
> Get the imagestack tile_shape from the TileCollectionData object.

- starfish/pipeline/pipelinecomponent.py
> [easy] Make explicit the abstract methods in the PipelineComponent hierarchy

- starfish/image/_filter/_base.py
- starfish/image/_filter/bandpass.py
- starfish/image/_filter/clip.py
- starfish/image/_filter/element_wise_mult.py
- starfish/image/_filter/gaussian_high_pass.py
- starfish/image/_filter/gaussian_low_pass.py
- starfish/image/_filter/laplace.py
- starfish/image/_filter/linear_unmixing.py
- starfish/image/_filter/match_histograms.py
- starfish/image/_filter/max_proj.py
- starfish/image/_filter/mean_high_pass.py
- starfish/image/_filter/richardson_lucy_deconvolution.py
- starfish/image/_filter/scale_by_percentile.py
- starfish/image/_filter/white_tophat.py
- starfish/image/_filter/zero_by_channel_magnitude.py
- starfish/image/_registration/_base.py
- starfish/image/_registration/fourier_shift.py
- starfish/image/_segmentation/_base.py
- starfish/image/_segmentation/watershed.py
- starfish/spots/_decoder/_base.py
- starfish/spots/_decoder/per_round_max_channel_decoder.py
- starfish/spots/_detector/_base.py
- starfish/spots/_detector/blob.py
- starfish/spots/_detector/local_max_peak_finder.py
- starfish/spots/_detector/trackpy_local_max_peak_finder.py
- starfish/spots/_pixel_decoder/_base.py
- starfish/spots/_pixel_decoder/combine_adjacent_features.py
- starfish/spots/_pixel_decoder/pixel_spot_decoder.py
- starfish/spots/_target_assignment/_base.py
- starfish/spots/_target_assignment/label.py
1. Ensure that the algorithm base classes's `run()` method is consistent with the implementations.
2. Fix missing documentation.
3. Add `*args` to all the run methods such that the implementations' run methods can take additional parameters.
Test plan: `make -j fast lint mypy`
> Clean up the algorithm base classes and run() methods.

- .travis.yml
- notebooks/STARmap.ipynb
- notebooks/py/STARmap.py
- starfish/data/__init__.py
- Adds a STARmap processing vignette
- Adds `starfish.data.STARmap` testing FoV 
Closes #863
> Add STARmap processing vignette

- data_formatting_examples/format_iss_breast_data.py
Shapes are mappings from axes to axis size.
> [easy] fix default shape for iss breast data

- REQUIREMENTS-STRICT.txt
- starfish/REQUIREMENTS-STRICT.txt
https://nvd.nist.gov/vuln/detail/CVE-2019-10255
> Bump version of notebook

- starfish/experiment/builder/test/test_orderediterator.py
I accidentally removed these tests as part of #1111.  Putting them back.
> Readd tests.

- CHANGELOG.md
Need to cut a release since slicedimage is updated.
> Release notes for 0.0.35

- starfish/image/_segmentation/_base.py
- starfish/spots/_decoder/_base.py
- starfish/spots/_detector/_base.py
- starfish/spots/_pixel_decoder/_base.py
- starfish/spots/_target_assignment/_base.py
We should not be using the click module directly, as it does not have the fix from #809.
> Use starfish.util.click instead of click

- starfish/experiment/builder/test/test_inplace.py
This should nail the coffin on #1116, though there may still be usability improvements we can deliver.
Depends on #1127
> Test to verify that inplace experiment construction works.

- starfish/_display.py
* Add ability of starfish.display to adjust z-size of spots to account for anisotropy
* Enable n-d spots in starfish.display
* Change default display colors to gray colormap + red spots
> Fixes for spots in starfish.display

- .travis.yml
https://travis-ci.com/spacetx/starfish/builds/107352600 is stacked on top of this PR and setup to trigger the cron.  Released notebooks successfully run.  Requirements are updated in https://github.com/spacetx/starfish/pull/1142
> Fix cron job tasks.

- starfish/util/indirectfile/_base.py
1. Improve documentation.
2. Properly type the `convert` method.
Test plan: `make -j lint mypy`
> [easy] small improvements to indirectfile package

- CHANGELOG.md
0.0.35 and notebooks in master are no longer compatible.
> Release changelog for 0.0.36

- starfish/spots/_detector/test/test_spot_detection.py
The code below also tests spot detection against an empty intensity table.
> Remove duplicate empty intensitytable test

- .travis.yml
branch = xxx is a string equality test.  branch =~ is a regex match.  see https://docs.travis-ci.com/user/conditions-v1
> Fix check requirements job

- docs/Makefile
- docs/source/_static/tutorials/exec_feature_identification_and_annotation.py
* fix docs that wasn't building
* check if this fixes build.
> Add clean rule to docs

- docs/source/_static/tutorials/exec_image_corrections.py
- starfish/image/_filter/test/test_api_contract.py
- starfish/image/_filter/test/test_filter.py
- starfish/image/_filter/test/test_histogram_matching.py
- starfish/image/_filter/test/test_linear_unmixing.py
- starfish/image/_filter/test/test_zero_by_channel_magnitude.py
- starfish/imagestack/imagestack.py
- starfish/imagestack/test/factories/from_codebook.py
- starfish/imagestack/test/test_apply.py
- starfish/imagestack/test/test_from_numpy_array.py
- starfish/imagestack/test/test_max_proj.py
- starfish/intensity_table/test/test_concatenate.py
- starfish/intensity_table/test/test_from_imagestack.py
- starfish/intensity_table/test/test_intensity_table_serialization.py
- starfish/intensity_table/test/test_stack_intensity_table_reshaping.py
- starfish/intensity_table/test/test_to_mermaid.py
- starfish/multiprocessing/test/test_multiprocessing.py
- starfish/spots/_detector/test/test_local_search_blob_detector.py
- starfish/spots/_detector/test/test_spot_detection.py
- starfish/spots/_pixel_decoder/test/test_calculate_mean_pixel_traces.py
- starfish/spots/_pixel_decoder/test/test_intensities_to_decoded_image.py
- starfish/test/factories.py
* update Imagestack to match Codebook, IntensityTable secondary constructor names
> [easy] Numpy only has arrays

- .gitignore
I get them when tests don't finish.
> [easy] Ignore partial coverage results

- starfish/intensity_table/intensity_table_coordinates.py
Trying to knock some seconds off of starfish. Here's part 1!
Before: 
After:
> vectorize imagestack -> intensity_table coordinate transfer

- notebooks/BaristaSeq.ipynb
- notebooks/py/BaristaSeq.py
*renames a parameter that got left behind in a notebook.
> [easy] Fix the build

- starfish/types.py
Its contents are actually in starfish/types/__init__.py
> [easy] Remove starfish/types.py

- docs/source/api/spots/detection/detection.rst
- starfish/spots/_detect_spots/_base.py
- starfish/spots/_detect_spots/blob.py
- starfish/spots/_detect_spots/local_max_peak_finder.py
- starfish/spots/_detect_spots/local_search_blob_detector.py
- starfish/spots/_detect_spots/trackpy_local_max_peak_finder.py
* move documentation of spots from constructor to class
* add top-level class docs to explain when to use each spot finder
> Spots documentation

- starfish/image/_filter/laplace.py
- starfish/image/_filter/max_proj.py
- starfish/imagestack/imagestack.py
For whatever reason, I'm seeing the docs build fail after combining #1221 and #1229 without these changes.  Master (with #1221) seems to build ok though.  Not sure why...?
> [easy] fix docs build

- docs/source/api/spots/decoding/decoding.rst
- starfish/spots/_decode/_base.py
- starfish/spots/_decode/metric_decoder.py
- starfish/spots/_decode/per_round_max_channel_decoder.py
- starfish/test/full_pipelines/cli/test_iss.py
* update decoding docs, 
* add metric decoder pipeline component
* change signature so that codebook is passed to constructor
> Decoding docs

- starfish/spots/_detect_pixels/_base.py
- starfish/spots/_detect_pixels/pixel_spot_decoder.py
> Update pixel decoder docs

- starfish/codebook/codebook.py
- starfish/intensity_table/intensity_table.py
- starfish/spots/_detect_spots/blob.py
- starfish/spots/_detect_spots/trackpy_local_max_peak_finder.py
> Changing See Also's to Notes

- README.rst
- notebooks/SeqFISH.ipynb
- notebooks/py/SeqFISH.py
* Adds work-in-progress SeqFISH notebook
* Data is too large, skip in travis.
> SeqFISH notebook

- starfish/util/click/indirectparams.py
- starfish/util/indirectfile/__init__.py
- starfish/util/indirectfile/_base.py
- starfish/util/indirectfile/_codebook.py
- starfish/util/indirectfile/_imagestack.py
Recipes is already a name for a different concept in this repo.
> [easy] rename recipe => formula

- .travis.yml
- README.rst
- notebooks/3d_smFISH.ipynb
- notebooks/py/3d_smFISH.py
- notebooks/py/smFISH.py
- notebooks/smFISH.ipynb
- starfish/data.py
- starfish/image/_filter/bandpass.py
* add back notebook
* add missing verbose parameter
* link to readme
> 3d smFISH notebook

- .gitattributes
- MANIFEST.in
- codecov.yml
- setup.cfg
- starfish/core/_version.py
It's moved into starfish/core.
Test plan: `python setup.py sdist` and then installed the resulting package in a different virtualenv
> Update references to _version.py

- docs/source/_static/tutorials/exec_running_a_pipeline.py
Two examples!  One is via the API.  The other is via the CLI.
Depends on #1160
> Documentation for running a recipe.

- docs/source/getting_started/installation/index.rst
add a section under the installation docs on how to set up virtual environments with conda
closes #704
> add documentation for use of conda environments

- .travis.yml
Note that this sets the TESTING=1 flag for `iss_pipeline.py`
> Add the data processing examples to travis runs for master

- docker/Dockerfile
- docker/environment.yml
Reverts spacetx/starfish#1256
This breaks master.
> Revert "Add pip to docker environment"

- Makefile
The solution is the wipe button on readthedocs
> Remove clean-docs rule.

- starfish/core/config/test/test_config.py
Rather than undoing things at the start of a test, wrap all monkeypatching in a context.
Test plan: `pytest -v starfish/core/config/test/`
> Use monkeypatch.context() to isolate monkeypatching

- starfish/core/codebook/codebook.py
- starfish/core/config/__init__.py
- starfish/core/imagestack/imagestack.py
I'm not sure this is the right thing to do, so feel free to reject.
> Remove .core from some docblocks.

- REQUIREMENTS-STRICT.txt
- starfish/REQUIREMENTS-STRICT.txt
Today's cron failed on "Check Requirements".
see: https://travis-ci.com/spacetx/starfish/jobs/197403005
> Bump requirements on failing cron

- docs/source/_static/tutorials/exec_image_manipulations.py
- starfish/core/experiment/experiment.py
- starfish/core/experiment/test/test_experiment.py
- starfish/core/imagestack/parser/crop.py
Unblocks @ambrosejcarr on seqFish work for now but will eventually be overridden by #1328
> Adding back ability to crop on fov.get_image()

- README.rst
- docs/source/community/contact/index.rst
1. Fix the join-slack link.
2. s/starfish-data@/starfish@/
3. Duplicated the contact info into README.rst
Test plan: none whatsoever.
> Update contact info

- starfish/core/spots/_detect_spots/detect.py
Tests are incomplete, and will be provided in the next PR.
Partial fix for #1258
> Fix spot detection for labeled data.

- starfish/core/spots/_detect_spots/detect.py
> Reference image max projection axes should be optional

- docs/source/_static/data_processing_examples/3d_smFISH.py
> Fix 3d smFISH notebook as well.

- notebooks/MERFISH.ipynb
- notebooks/py/MERFISH.py
I changed the starfish.data link for MERFISH to the full dataset so we no longer need two different ways of getting the scale factor info
> [Easy] fix merfish scale factors

- starfish/core/__init__.py
- starfish/core/image/_registration/transforms_list.py
- starfish/core/imagestack/imagestack.py
- starfish/core/spacetx_format/util.py
- starfish/util/plot.py
mypy 0.710 has some new errors.  Fix them.  There's one that's spurious, so I'm just blindly ignoring for now.
> Fix mypy errors

- starfish/data.py
Test plan:
```
exp['fov_000'].get_image('primary')
exp['fov_001'].get_image('primary')
exp['fov_002'].get_image('primary')
```
Fixes #1294
> [easy] point starfish.data.osmFISH() to new dataset

- starfish/core/experiment/builder/__init__.py
1. Make TileIdentifier an immutable dataclass.
2. Use a f-string to format paths in `_tile_opener`
3. Make `fov_path_generator` and `tile_opener` arguments of write*experiment_json default to None.  This allows user code to cleanly call these methods sometimes with overrides without crufty code[a].
4. Improve documentation a teeeeeeeeeeeny bit.
5. Rename remaining `TileCoordinates` to `TileIdentifiers`
[a]: If a caller sometimes needs to invoke write_experiment_json with a tile_opener, we can now do:
```
if needs_tile_opener:
tile_opener = abc
else:
tile_opener = None
write_experiment_json(blah_blah, tile_opener=tile_opener)
```
Previously, it would require something like:
```
if needs_tile_opener:
write_experiment_josn(blah_blah, tile_opener=abc)
else: …
```
> Improvements to experiment builder

- CONTRIBUTING.rst
> Adding Zenhub Info to contributors guide

- docs/source/_static/data_formatting_examples/format_baristaseq.py
- docs/source/_static/data_formatting_examples/format_imc_data.py
- docs/source/_static/data_formatting_examples/format_iss_breast_data.py
- docs/source/_static/data_formatting_examples/format_iss_data.py
- docs/source/_static/data_formatting_examples/format_merfish_U2OS_data.py
- docs/source/_static/data_formatting_examples/format_osmfish.py
- docs/source/_static/data_formatting_examples/format_seqFISH.py
- docs/source/_static/data_formatting_examples/format_starmap.py
- starfish/core/codebook/codebook.py
- starfish/core/experiment/builder/__init__.py
- starfish/core/experiment/builder/defaultproviders.py
- starfish/core/experiment/builder/providers.py
- starfish/core/experiment/builder/test/factories/all_purpose.py
- starfish/core/experiment/builder/test/inplace_script.py
- starfish/core/imagestack/imagestack.py
- starfish/core/imagestack/test/factories/all_purpose.py
- starfish/core/imagestack/test/test_coordinates.py
- starfish/core/imagestack/test/test_cropped_load.py
- starfish/core/imagestack/test/test_labeled_indices.py
- starfish/core/imagestack/test/test_slice_ops.py
- starfish/core/imagestack/test/test_slicedimage_dtype.py
- starfish/core/intensity_table/intensity_table.py
- starfish/core/intensity_table/test/test_empty_intensity_table.py
- starfish/core/spots/_detect_spots/detect.py
round_, _round, round_id => round_label
ch, ch_id => ch_label
z, zplane_id, => zplane_label
*_values => *_labels
Test plan: make -j test
Depends on #1419
> Fix glossary violations.

- starfish/core/imagestack/imagestack.py
1. Constructor takes the xarray and the tile_data.
2. Make a builder that takes a TileCollectionData and return an ImageStack.
This will allow us to avoid using the `from_numpy_array` escape hatch for methods like max_proj.
Depends on #1032, #1048, #1049
> Make ImageStack a thinner wrapper around the xarray.

- README.rst
- docs/source/usage/index.rst
Traditionally alpha = in house use, beta = external testers.
Test plan: lol
> Starfish pre-alpha -> beta

- notebooks/SeqFISH.ipynb
- notebooks/py/SeqFISH.py
need to set `is_volume=True` when creating clip filter to avoid nans from #1261
> Replacing scale by percent code with clip

- Makefile
- REQUIREMENTS-STRICT.txt
- REQUIREMENTS.txt
- docs/source/_static/data_formatting_examples/exec_format_structured_data.py
- starfish/REQUIREMENTS-STRICT.txt
- starfish/core/experiment/builder/structured_formatter.py
- starfish/core/experiment/builder/test/structured_formatter/structured_formatter_script.py
- starfish/core/experiment/builder/test/structured_formatter/test_multiple_fov.py
- starfish/core/experiment/builder/test/structured_formatter/test_single_fov.py
- starfish/core/experiment/builder/test/structured_formatter/test_tilepath.py
- starfish/core/experiment/builder/test/structured_formatter/util.py
code and docs for creating experiments from tiles with a regular naming schema.
very simple test included, but more testing of the bullet proofing from weird user choices is probably needed.  (bullet proofing is theoretically in the design already).
Depends on #1403, #1409, #1417, #1419 
Fixes #1318
> data set formatter with fixed filenames

- .travis.yml
- Makefile
removing starfish build command from `make docker` step
> Fixing travis build 

- REQUIREMENTS-STRICT.txt
- REQUIREMENTS.txt
- starfish/REQUIREMENTS-STRICT.txt
This is to pick up https://github.com/spacetx/slicedimage/pull/111
> Bump to slicedimage 4.0.1

- REQUIREMENTS-STRICT.txt
- starfish/REQUIREMENTS-STRICT.txt
> Updating requirements.

- .github/ISSUE_TEMPLATE/agile-user-story.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This PR adds 3 issue templates:
- For users to submit bug reports
- For users to submit feature requests
- For the team to submit user stories
> Adds issue templates

- .github/ISSUE_TEMPLATE/agile-user-story.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/user-story.md
This should sort the list better. Also "Agile" isn't really necessary.
> [EASY] Agile User Story -> User Story

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/user-story.md
my awesome addition of emoji to the issue template failed. this should fix it.
> fixes unicode in issue template

- setup.py
- starfish/core/_display.py
- starfish/core/segmentation_mask.py
- starfish/core/test/test_segmentation_mask.py
- update napari version to `0.1.3`
- add segmentation masks visualization support (resolves #1422)
closes #998
> update napari to 0.1.3

- notebooks/STARmap.ipynb
- notebooks/py/STARmap.py
The issue here actually had to do with the `intensities.fillna(0)` outputting a DataArray instead of an IntensityTable. I wrapped the call in the STARmap notebook.
> fix to dataframe

- starfish/core/image/_registration/LearnTransform/translation.py
Small improvements to documentation at @pdichiaro 's suggestion.
> Clarify registration upsampling factor

- starfish/core/spots/DetectSpots/local_search_blob_detector.py
Small improvements to documentation at @pdichiaro 's suggestion.
> Improve documentation on LocalSearchBlobDetector

- docs/source/api/datasets/index.rst
- docs/source/api/index.rst
let's see if it builds properly first...
> adds API docs for datasets

- starfish/core/codebook/test/factories.py
- starfish/test/full_pipelines/api/test_dartfish.py
- starfish/test/full_pipelines/api/test_iss_api.py
On Windows, this is not supported.  This is the same as https://github.com/spacetx/slicedimage/pull/118.
> don't hold the temp file open while trying to open it.

- .travis.yml
Depends on #1533, #1534, #1535, #1536, #1537
> Enable Windows builds on master

- .travis.yml
If the branch name is master or contains `-alltest`, then run all notebooks.
Test plan: well, hopefully this travis test?
> Make it easier to test all notebooks

- starfish/core/imagestack/imagestack.py
This is to address https://github.com/spacetx/starfish/pull/1519/files#r324791585.  I think this accurately captures what's happening here.
> [easy] fix docs regarding ImageStack.apply

- starfish/core/spots/DetectSpots/local_max_peak_finder.py
Shared state is fundamentally incompatible with multithreading.
1. Each tile computes its own threshold.
2. Don't share the spot coords.
Part of #834
> Get rid of shared state for LocalMaxPeakFinder

- starfish/core/image/Filter/__init__.py
- starfish/core/image/Segment/__init__.py
- starfish/core/image/_registration/ApplyTransform/__init__.py
- starfish/core/image/_registration/LearnTransform/__init__.py
- starfish/core/spots/AssignTargets/__init__.py
- starfish/core/spots/Decode/__init__.py
- starfish/core/spots/DetectPixels/__init__.py
- starfish/core/spots/DetectSpots/__init__.py
This is the same as #1510 except for all the algorithm implementations.
Depends on #1553
> Document all the algorithm implementations

- CHANGELOG.md
> Release 0.1.6

- starfish/core/image/_registration/_format.py
- starfish/core/image/_registration/transforms_list.py
fixes  #1104 
Part of larger #1309 epic
> Saxelrod add transforms versioning

- REQUIREMENTS-STRICT.txt
- starfish/REQUIREMENTS-STRICT.txt
> [easy] Update all requirements

- docs/source/api/image/index.rst
This is a continuation of #1554
#1510 is where we made the first change.
> Convert remaining autoclass directives to automodule

- starfish/core/intensity_table/intensity_table.py
Noticed this while looking at some code.
Test plan: whatever......
> [easy] update example for intensity table docs

- starfish/core/segmentation_mask/expand.py
- starfish/core/segmentation_mask/test/test_expand.py
- starfish/core/segmentation_mask/util.py
This method allows us to produce a labeled image with minimal looping in python.  It takes a mask array with labeled axes, a fill value, and writes the fill value into the result array where mask is True.
Depends on #1578
Test plan: see tests that are written
> Masked fill method

- starfish/core/spots/DecodeSpots/test/test_decoding_without_spots.py
- starfish/core/spots/DecodeSpots/test/test_trace_builders.py
- starfish/core/spots/FindSpots/local_max_peak_finder.py
- starfish/core/spots/FindSpots/test/test_spot_detection.py
- starfish/core/spots/FindSpots/test/test_synthetic_data.py
- starfish/core/test/factories.py
- starfish/core/types/_spot_finding_results.py
This PR moves and modifies all existing spot finding test code into the new modules.
> 7.) changing test code to use new spot finding modules

- REQUIREMENTS-CI.txt
[This](https://github.com/python/mypy/issues/7735) causes spurious errors.
> Don't use mypy 0.740

- starfish/core/label_image/label_image.py
- starfish/core/label_image/test/test_label_image.py
@ambrosejcarr says we agreed to parrot xarray's convention.  I have no recollection of this, senator.
> Update vocabulary for LabelImage I/O operations.

- REQUIREMENTS-STRICT.txt
- REQUIREMENTS.txt
- starfish/REQUIREMENTS-STRICT.txt
This is mostly to pick up PNG support.
> Upgrade to slicedimage 4.1.0

- starfish/core/types/__init__.py
- starfish/types.py
This is an array-like type that accepts ndarray, DataArray, or a sequence of a numeric type.
I remember we talked about doing this, but I can't seem to find any issue to connect this to. :/
Test plan: none!
> Create an ArrayLike type

- starfish/core/image/Segment/watershed.py
- starfish/core/morphology/binary_mask/binary_mask.py
- starfish/core/morphology/binary_mask/test/test_binary_mask.py
- starfish/core/morphology/label_image/label_image.py
- starfish/core/morphology/label_image/test/test_label_image.py
- starfish/core/test/test_display.py
I like @kne42's usage of physical ticks and applied it to both pixels and physical.  Pixel ticks is less confusing than pixel coordinates.
Test plan: codemod && travis
Depends on #1632
> Update LabelImage's vocabulary

- starfish/core/morphology/binary_mask/binary_mask.py
I wrote this documentation but stuck it in the wrong diff.
Test plan: it's a docblock
> Fix documentation for uncropped_masks

- starfish/core/morphology/Filter/min_distance_label.py
- starfish/core/morphology/Filter/structural_label.py
One is a simple labeling algorithm using a structuring element.
The other uses local max peak finder to find the point furthest from the background image to seed a labeled watershed.  A minimum distance parameter tunes how far apart the peaks must be.
> Implement Labeling algorithms

- docs/source/help_and_reference/roadmap.rst
This PR updates the roadmap, reflecting the starfish team's priorities in the coming months.
Feedback and questions welcome! 
Will leave this open at least until Dec 4.
> updated roadmap

- REQUIREMENTS-STRICT.txt
- REQUIREMENTS.txt
- starfish/REQUIREMENTS-STRICT.txt
This is to pick up https://github.com/spacetx/slicedimage/pull/131
> Bump slicedimage to 4.1.1

- starfish/core/image/Filter/__init__.py
- starfish/core/image/Segment/__init__.py
- starfish/core/image/_registration/ApplyTransform/__init__.py
- starfish/core/image/_registration/LearnTransform/__init__.py
- starfish/core/morphology/Binarize/__init__.py
- starfish/core/morphology/Filter/__init__.py
- starfish/core/spots/AssignTargets/__init__.py
- starfish/core/spots/DecodeSpots/__init__.py
- starfish/core/spots/DetectPixels/__init__.py
- starfish/core/spots/FindSpots/__init__.py
@shanaxel42 pointed out that a lot of these are not filters.  Replaced them with a more generalized term that is conducive to copy-pasta. :)
BOOM.  Also simplified the code.
Test plan: make -j lint mypy
> Fix definition of __all__

- starfish/core/morphology/Filter/areafilter.py
- starfish/core/morphology/Filter/test/test_areafilter.py
> Use kwargs for area filter and validate args

- docs/source/api/morphology/index.rst
- starfish/core/image/Segment/watershed.py
- starfish/core/morphology/Binarize/__init__.py
- starfish/core/morphology/Segment/__init__.py
- starfish/core/morphology/Segment/_base.py
- starfish/core/morphology/Segment/watershed.py
- starfish/morphology.py
This is the agreed upon API from the community sync.
Fixes #1707
Depends on #1719
> [easy] Move watershed segmentation from morphology.Binarize to morphology.Segment

- notebooks/MERFISH.ipynb
- notebooks/py/MERFISH.py
- starfish/core/image/Filter/test/test_filter.py
- starfish/core/image/Filter/test/test_linear_unmixing.py
- starfish/core/imagestack/test/test_apply.py
- workflows/wdl/merfish_published/recipe.py
Port the remaining instances to use Levels.
Test plan: make -j fast
> Remove remaining usages of Clip

- docs/source/getting_started/formatting_data/index.rst
- examples/data_loading/README.txt
- examples/data_loading/plot_tilefetcher_loader.py
Test plan: `make docs-html`
Fixes: #1759
> Add docs for TileFetcher as loader

- notebooks/BaristaSeq.ipynb
- notebooks/DARTFISH.ipynb
- notebooks/SeqFISH.ipynb
- notebooks/py/BaristaSeq.py
- notebooks/py/DARTFISH.py
- notebooks/py/SeqFISH.py
> Remove instances where we use `expand_dynamic_range` in notebooks

- starfish/core/spots/DecodeSpots/test/test_spot_finders.py
- starfish/core/spots/FindSpots/blob.py
Also fixing bug I discovered where blob_doh does not accept the 'exclude_border' argument. 
Added test/ 
Fixes: #1555
> [easy] -Adding Value error to BlobDetetor that prevents blob_doh use with 3d images

- starfish/core/codebook/codebook.py
- starfish/core/spots/DecodeSpots/metric_decoder.py
- starfish/core/spots/DecodeSpots/test/test_metric_decoder.py
> Adding flag to MetricDistance decoder to return original intensity values 

- starfish/util/plot.py
> Added diagnose_registration docstring

- starfish/core/intensity_table/test/test_from_imagestack.py
> remove low-signal TODOs

- starfish/core/imagestack/test/factories/from_codebook.py
It's not clear why we want to make it smaller.
Fixes #1774
> Remove low-signal TODO

- starfish/core/experiment/builder/structured_formatter.py
> [easy] Remove TODO

- starfish/core/codebook/codebook.py
This is not on the critical path of any code, so nuking this.
Test plan: meh.
Fixes #1785
> Remove TODO

- Makefile
1. `pin-requirements` takes into consideration the existing pins, and repins only the minimal set of changes required to satisfy the top-level requirements.  Run this when you add a new requirement.
2. `pin-all-requirements` wipes away all the pins and pins based on the latest.  Do this periodically so we don't have stale requirements.
Test plan: run both rules manually.
> Clarify existing rules for requirements

- README.rst
`starfish` is now a community partner of the image.sc forum.
> README: add image.sc forum badge and link

- docs/source/_static/my-styles.css
- docs/source/index.rst
- docs/source/user_guide/index.rst
- examples/plot_image_corrections.py
- examples/plot_image_registration.py
see: https://spacetx-starfish.readthedocs.io/en/mcai-registration-docs/
* added image registration tutorial to examples gallery
* also changed the css style of note and warning admonitions
closes #1851
> added image registration tutorial

- docs/source/api/index.rst
- docs/source/api/plot_utils/index.rst
- docs/source/api/utils/index.rst
- starfish/util/plot.py
* added api for plotting utilities and data structures
* still need CC-BY licenses for datasets
see: https://spacetx-starfish.readthedocs.io/en/mcai-api-additions/api/
closes #1852
> expanded api docs

- .travis.yml
pip can't be upgraded in place any more.
> Fix Windows tests

- README.rst
- REQUIREMENTS.txt
- examples/quick_start/plot_quick_start.py
- examples/tutorials/watershed_segmentation.py
Closes: #1898, #1900, #1901, #1902 
Also fixes [sympy version issue ](https://forum.image.sc/t/starfish-threading-issue-with-local-max-peak-finder-py/40377/9)
> Address easy fixes by JOSS reviewers

- examples/tutorials/assigning_spots.py
- examples/tutorials/manual_segmentation.py
> Add code for downloading necessary RoiSet.zip to relevant examples

- paper/paper.md
minor changes to JOSS paper for Allen Institute name and acknowledgements.
> update BRL affiliation and acknowledgement

- requirements/REQUIREMENTS-CI.txt
- requirements/REQUIREMENTS-NAPARI-CI.txt
See https://github.com/spacetx/starfish/pull/1918#issuecomment-731504327
> Move to pillow 7.1.2 instead.

- docs/source/conf.py
- requirements/REQUIREMENTS-CI.txt
- requirements/REQUIREMENTS-CI.txt.in
> Use m2r2 instead of m2r

- CHANGELOG.md
The master branch is protected against updates.
Changes must be made through a pull request.
> Updating CHANGELOG.md for release 0.3.1

- .github/workflows/dependabot.yml
This new workflow will automatically open PR to update new Actions version:
actions/cache
actions/checkout
actions/setup-python
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
> Create dependabot.yml to update Actions version

- CHANGELOG.md
PR for updating CHANGELOG.md for release 0.3.3
> Changelog 0.3.3
