spacetx/starfish

- examples/get_iss_data.py
- starfish/io.py
Just some suggested renaming here:
`meta_data` -> `metadata` (this is a more common way to write it)
`aux_data` -> `aux` (possibly we'll have aux metadata)
So the fields are now `data`, `metadata`, and `aux`, which feels cleaner to me.
This change should only affect how we're writing the example data, and our `io` functions.
> renaming data  fields

- starfish/munge.py
- starfish/starfish.py
- starfish/viz.py
This PR adds support for converting `spot` and `region` information into the `geoJSON` format, and then exports to those formats in the CLI operations for `detect_spots` and `segment`. Munging functions derived from example Jupyter notebook. Confirmed that generated `regions.json` files could be used in web-based data visualization.
> geojson ouput

- starfish/starfish.py
This allows starfish to be run, rather than running python starfish.
Test:
```
[czipa1osx186 (.venv)]:~/microscopy/starfish:tonytung-env> pip install -e .
Obtaining file:///Users/ttung/microscopy/starfish
Installing collected packages: starfish
Found existing installation: starfish 0.0.1
Uninstalling starfish-0.0.1:
Successfully uninstalled starfish-0.0.1
Running setup.py develop for starfish
Successfully installed starfish
[czipa1osx186 (.venv)]:~/microscopy/starfish:tonytung-env> starfish
Usage: starfish [OPTIONS] COMMAND [ARGS]...
Options:
--help  Show this message and exit.
Commands:
decode
detect_spots
filter
register
segment
show
[czipa1osx186 (.venv)]:~/microscopy/starfish:tonytung-env> 
```
> Add she-bang to the top of starfish.py

- REQUIREMENTS.txt
Numpy 1.13.0 is the default numpy provided by travis's python 3.5 image.  This version is incompatible with starfish, so we need to blacklist it.
Here's an example log of it breaking: https://travis-ci.org/chanzuckerberg/starfish/jobs/293396599
```
Traceback (most recent call last):
File "/home/travis/virtualenv/python3.5.3/bin/starfish", line 11, in <module>
load_entry_point('starfish', 'console_scripts', 'starfish')()
File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke …
```
> Blacklist numpy 1.13.0

- starfish/starfish.py
- tests/test_profiler.py
Added a hidden no-op command that's used to quickly test the profiler.
> Enable profiling with a command line switch.

- starfish/decoders/merfish.py
- starfish/spots/pixel.py
This PR implements a merfish decoder by:
1. Creating a simple pixel-based spot detector, which assigns each pixel to a spot_id in the standardized encoder table format. Technically, this is not necessary for the decoder, but does keep in line with our standard file format for other kinds of data.
2. Creating a MerfishDecoder class that takes as input the output of the pixel-based spot detector, the codebook, and some tuning parameters.
I verified that this can re-produce results from a collaborator with r = 0.99 for copy number comparison.
> Added merfish-decoder

- .flake8
- starfish/spots/gaussian.py
- starfish/starfish.py
1. Set column limit to 120.
2. Remove some generic try-catch'es. (I checked numpy's `max` and `mean` functions, and it seems to handle NaN in input correctly.  It does, however, barf on a 2D array that's incorrectly set up, e.g., a row/column that's a scalar instead of an vector).
> Prepare for enabling lint.

- tests/test_iss_data.py
Currently, we just verify that starfish runs and doesn't crash.  This adds a quick sanity test to ensure that _some_ result is generated and that the result seems reasonable.
> [easy] add quick sanity test to ensure that the pipeline actually ran.

- setup.py
- starfish/__main__.py
- starfish/starfish.py
- tests/test_iss_data.py
- tests/test_profiler.py
This allows us to convert starfish into a proper package without harmless yet scary looking messages.
> use the standard module __main__ to drive command line interpreter usage

- starfish/registration/__init__.py
Provides an entry point for code-level access to registration algorithms.  Unlike `_cli()`, which groups the entire load-process-write into one method tied to command line parameter processing, this `run(..)` method is a pythonic construct, where the algorithm name and stack are passed in individually (along with algorithm arguments).
> python api access to registration.

- setup.py
The fix in #29 is not quite right.  That PR solves the issue with running `python -m starfish`, but introduces harmless but scary looking messages when just running `starfish`.
> Fix entry_points

- examples/get_iss_data.py
- starfish/io.py
1. Always use it in upper case (in preparation for conversion to an Enum)
2. Always have it present, for aux as well.
> [imagestack] Normalize file format field.

- starfish/io.py
1. Use os.path.splitext instead of string replacement.
2. replace `new_org` with `self.org` as it _implies_ a copy whereas it's just a reference.
3. reorder imports to follow PEP8 conventions.
> [imagestack] Clean up filename and org.json munging.

- starfish/image/__init__.py
- starfish/image/_base.py
- starfish/image/_stack.py
- starfish/io.py
- starfish/registration/_fourier_shift.py
Image stacks are a logically different concept than a starfish input set. This PR attempts to separate the two concepts in the *code* in preparation for separating the manifest files that describe them.  With this change, we continue to source image stack data from org.json, but in code, it's a component within the input set.
In a future PR, the image stack data will be extracted to a separate file.
> [imagestack] Separate the notion of a starfish input set with an image stack

- starfish/registration/__init__.py
- tests/test_iss_data.py
help looks like this now:
```
[czipa1osx186 (.venv)]:~/microscopy/starfish:master> starfish register fourier_shift --help
usage: starfish register fourier_shift [-h] [--u U]
optional arguments:
-h, --help  show this help message and exit
--u U       Amount of up-sampling
h[czipa1osx186 (.venv)]:~/microscopy/starfish:master>
```
Fixes #40
> Convert in_json and out_dir to required parameters

- starfish/registration/__init__.py
- starfish/registration/_base.py
- starfish/registration/_fourier_shift.py
1. The algorithms are now required to implement two methods.
a. `get_algorithm_name()`, which returns the name of the algorithm.
b. `add_arguments(parser)`, which adds the algorithm's arguments to the parser.
2. The top-level pipeline stage (e.g., Registration) is now responsible for setting up the parser.  This reduces boilerplate code.
3. Explicitly calls `_ensure_algorithms_setup()`.
> Refactor how the individual algorithms are set up.

- starfish/pipeline/pipelinecomponent.py
#87 broke the `run()` method.  h/t to @ambrosejcarr for finding this.
> Fix Registration.run()

- Makefile
- REQUIREMENTS-DEV.txt
- notebooks/subdir.mk
Add makefile rules to automatically validate all notebooks in notebooks/*.  Note that this will _fail_ travis test builds because `notebooks/Starfish_simulation.py` does not exist.
> Convert .ipynb to .py and compare for validation.

- starfish/pipeline/registration/__init__.py
- starfish/starfish.py
argparse doesn't handle unrecognized arguments with subcommands correctly.  It always prints the top-level help even when a subcommand has been selected.
It does this:
```
[czipa1osx186 (.venv)]:~/microscopy/starfish:master> starfish register -i /dev/null -o /dev/null --abone
usage: starfish [-h] [--profile]
{register,filter,detect_spots,segment,decode,show} ...
starfish: error: unrecognized arguments: --abone
```
With this patch, it does:
```
[czipa1osx186 (.venv)]:~/microscopy/starfish:tonytung-arguments> starfish register -i /dev/null -o /dev/null --abone
_              __ _     _
| |            / _(_)   | |
___| |_ __ _ _ __| |_ _ ___| |__
/ __| __/ _` | '__|  _| / __| '_  `
\__ \ || (_| | |  | | | \__ \ | | |
|___/\__\__,_|_|  |_| |_|___/_| |_|
usage: starfish register [-h] -i INPUT …
```
> Workaround for handling of unrecognized arguments.

- starfish/starfish.py
Currently, segment writes region.json twice, overwriting the data with previously written data.
This prompted me to try to clean up where we write our output to.  Now, all geojson output will be written to XXX.geojson.
> Standardize where we write geojson to.

- notebooks/subdir.mk
`make regenerate_ipynb` will regenerate all the `.ipynb` notebooks.
`make regenerate_py` will regenerate all the `.py` counterparts.
> Makefile rules to regenerate .py/.ipynb notebooks.

- starfish/munge.py
This will be necessary to separate gene assignment from segmentation, as we will need to load up geojson output from segmentation to do gene assignment.
> Add a geojson-to-region converter.

- notebooks/Mignardi_Pipeline.ipynb
- notebooks/Mignardi_Pipeline.py
- starfish/assign.py
- starfish/starfish.py
1. Both assignment and the output of segmentation convert from labels to regions.  This ensures we only do the work once.
2. Rename the variable `r` to `regions`.
Depends on #99
> Clean up the API around gene assignment.

- starfish/pipeline/decoder/__init__.py
- starfish/pipeline/decoder/_base.py
- starfish/pipeline/decoder/_iss.py
- starfish/starfish.py
- tests/test_iss_data.py
Follow-on changes:
1. Get the codebook from a file.  This requires us to add the codebook to the pipeline API. (#96)
2. Merge `starfish.decoders.iss` into `starfish.pipeline.decoder._iss` (this will require refactoring the notebooks, but with @ambrosejcarr having landed the notebooks, it should be a lot easier). (#97)
> Refactor decode stage into a PipelineComponent.

- Makefile
- tests/test_iss_data.py
This will stop .coverage.xxx files from getting dropped everywhere.
Test plan: Run `make tests/test_iss_data.py` and no .coverage.xxx files were created.
> Only run with coverage when running the entire test suite.

- Makefile
- notebooks/subdir.mk
Ignore the notebook metadata when validating that the .ipynb and the .py match.  This is because subtle and unimportant changes are written there, such as the version of the python interpreter used to evaluate the notebook.  None of this matters as far as how the notebook code and layout is preserved.
> unbreak the build

- starfish/pipeline/pipelinecomponent.py
The earlier mechanism was more complicated, and lost constructor signatures.  This is a better way.
> Simplify the creation of the shortcuts to the individual algorithms

- README.md
- starfish/pipeline/decoder/__init__.py
- tests/test_iss_data.py
#95 changed how decode works.  This fixes up the documentation.
Removed -c as an option for specifying codebook.
I also snuck in a change renaming decoder_table to decoded_table. :)
> Fix decode documentation and filenames

- REQUIREMENTS-DEV.txt
- examples/get_iss_data.py
- starfish/pipeline/decoder/_iss.py
- tests/test_iss_data.py
1. Modify `examples/get_iss_data.py` to create the codebook that was previously hardcoded in starfish.py
2. Modify `tests/test_iss_data.py` to extract the path of the codebook and feed it into the decode stage.
Depends on #95
> Use the codebook loaded from a file.

- examples/get_iss_data.py
- starfish/image/__init__.py
- starfish/image/_constants.py
- starfish/image/_stack.py
- starfish/io.py
- starfish/pipeline/registration/fourier_shift.py
- starfish/starfish.py
Things like 'hyb', 'ch', etc. should be referred to by constants rather than magic strings.  That makes 1) usage easier to track, and 2) easier to refactor.
> Use "constants" instead of magic strings.

- starfish/image/_stack.py
This allows users to specify the axes and the values by which to slice the data.  This is the preferred way of accessing data, since it allows us to change the order of dimensions, though the `numpy_array()` accessor remains accessible.
Depends on #133
> Add slice operations to ImageStack

- starfish/image/_stack.py
- starfish/pipeline/registration/fourier_shift.py
- starfish/starfish.py
This removes the need to allocate a new array, and makes the pipeline code unaware of the ordering of the axes.
Depends on #134
> use the slice operations to get and set data.

- starfish/image/_base.py
- starfish/image/_stack.py
- starfish/io.py
image.shape now returns an ordered index_name -> index_size map.
> get the actual numpy shape for comparison in set_stack

- README.md
- starfish/pipeline/gene_assignment/__init__.py
- starfish/pipeline/gene_assignment/_base.py
- starfish/pipeline/gene_assignment/point_in_poly.py
- starfish/starfish.py
- tests/test_iss_data.py
Create a gene assignment pipeline component, and move the relevant code there.
Note that this changes the output of segmentation to output the full geometry of the regions, rather than the hull.
Depends on #102, #101, #100
> Separate assignment from segmentation.

- tests/test_get_slice_api.py
- tests/test_iss_data.py
- tests/test_profiler.py
- tests/test_set_slice_api.py
This is necessary when users don't `pip install -e .`, but we recommend that in README.md.
> Remove import hack

- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.py
The stack is read fairly normally.  The codebook is currently sourced through a side channel, so I need to think of a better way to handle that. :)
Depends on #146 
You can look at s3://czi.starfish.data.public/ISS/ to see how to lay out your files (there's really nothing special, since #146 grants us the ability to resolve like a web browser)
> Convert ISS notebook to source data from the cloud.

- starfish/spots/gaussian.py
@ambrosejcarr  is making me clean up the codebase.  this is removed because we dropped 2.7 support.
> remove from __future__ import

- starfish/image/_stack.py
- tests/test_apply.py
- Adds `Stack.apply` which enables the iterative application of any 2d or 3d function to the data in Stack.numpy_array using the `get_slice` and `set_slice` API. 
- I excluded multiprocessing, but left a comment where the map function could be swapped out, when we have more confidence what our numpy back-end will look like.
> add stack function apply method

- starfish/image/_base.py
- starfish/image/_stack.py
1. _data is always set, so we can get rid of the escape clauses for them being None.
2. Fix type annotations to match.
3. Fix type annotations in base class.
> [easy] Fix shape and raw_shape.

- starfish/pipeline/decoder/__init__.py
- starfish/pipeline/decoder/_base.py
- starfish/pipeline/decoder/iss.py
- starfish/pipeline/gene_assignment/__init__.py
- starfish/pipeline/gene_assignment/_base.py
- starfish/pipeline/gene_assignment/point_in_poly.py
- starfish/pipeline/registration/__init__.py
- starfish/pipeline/registration/_base.py
- starfish/pipeline/registration/fourier_shift.py
- tests/test_iss_data.py
Upside: we can get rid of the `from_cli_args` call.  Downside: every algorithm's constructor is required to have `**kwargs`.
> use **val(args) to call algorithm's constructor

- .travis.yml
- starfish/image/_stack.py
Converted existing _variable_ type annotations to use the new syntax.
> Drop python < 3.6

- starfish/io.py
This was required for <py36 because they have some brokenness with bytes vs strings.
> Remove codecs workaround

- examples/build_sample_experiment.py
1. Set the default image type to numpy. This is not really that important since each entry overrides the image type, but it's confusing otherwise.
2. Add extras to the top level experiment doc.
> Small fixes to sample experiment generator

- examples/build_sample_experiment.py
build_image expects hyb, ch, z, not the other way around.
> [auximg 2/13] [easy] Fix the order of the parameters to build_image

- examples/build_sample_experiment.py
The build_sample_experiment.py tool could possibly generate the data required for get_iss_data.py.
> [auximg 5/13] [easy] Add dots as a possible auxiliary image

- .flake8
This allows statements like
```
x = lambda: 1
```
flake8 is asking that we do:
```
def x():
return 1
```
> [auximg 6/13] [easy] allow assignments from lambdas

- Makefile
- examples/build_sample_experiment.py
Introduce the notion of a FetchedImage, which provides the necessary data to set up a tile in `slicedimage`.  Create `DumbFetchedImage`, which is an implementation of `FetchedImage` that generates random noise for an image.
Depends on #205, #206, #207, #209, #211
> [auximg 8/13] Always write TIFF files for the sample builder.

- examples/support/__init__.py
This allows callers of `build_image(..)` to provide the tile shape.
Depends on #214
> [auximg 11/13] move default tile shape to be configured at the experiment level.

- starfish/io.py
- Simple PR to make stack construction a single line. 
- Later PRs can add error-handling related to `slicedimage` to this class. 
- Snuck in a spelling correction.
> add classmethod constructor for Stack

- starfish/errors.py
- starfish/image/_stack.py
- tests/test_slicedimage_dtype.py
This is particularly important for passthrough pipeline stages that don't do much computation, but reading the data and immediately writing the data alters it.
> [auximg 4/13] Set up the caching numpy array to match the dtype of the tiles.

- examples/get_iss_data.py
- starfish/io.py
- starfish/pipeline/features/spots/detector/gaussian.py
- starfish/pipeline/filter/bandpass.py
- starfish/pipeline/filter/clip.py
- starfish/pipeline/filter/gaussian_high_pass.py
- starfish/pipeline/filter/gaussian_low_pass.py
- starfish/pipeline/filter/richardson_lucy_deconvolution.py
- starfish/pipeline/filter/white_tophat.py
- starfish/pipeline/registration/fourier_shift.py
- starfish/pipeline/segmentation/watershed.py
There are two commits that make up this diff.  The first one will not work by itself, because it only changes the write path of get_iss_data.py to use the new examples/support module, and generate the new format.  The tests will obviously break because it expects a single image for each aux img.  The second one changes the consumers to use ImageStack for aux images, and unbreaks the tests.
I have kept the two changes separate for readability purposes, as it's an absurdly large change otherwise. :)
Depends on #208, #215
> [auximg 12/13] switch aux images to using ImageStack

- starfish/munge.py
- starfish/pipeline/features/spots/detector/gaussian.py
- starfish/spots/binary.py
- starfish/spots/pixel.py
- Add docstring to `munge.gather`
- Rename `gather -> melt` since that's what it's calling
- Clarify how args relate to `pd.melt`, that it wraps. 
- Use kwargs when calling melt to clarify outcome of calling the function. 
N.B.  `starfish/spots/gaussian.py` is unchanged because it's vestigial and removed in #222
> Ajc doc gather

- starfish/pipeline/filter/white_tophat.py
Take the minimum of image,max_filtered to ensure we don't get a negative result.  This allows us to avoid the cast to float64.
This is a better solution to the problem #241 was attempting to solve.
Depends on #242
> Clip bottom range of white-top-hat filter to 0

- .travis.yml
- notebooks/subdir.mk
If *.py.skip exists, then that notebook is skipped.
See https://travis-ci.org/spacetx/starfish/builds/389071632 for a run when .travis.yml is set to look for a different branch name.
> Validate that the notebooks can run successfully

- starfish/io.py
If stack.write(..) gets an absolute path, then experiment.json['hybridization'] is an absolute path and everything works.  However, if stack.write(..) gets a relative path, then experiment.json['hybridization'] gets the relative path twice -- once from the baseurl, and once from the written entry.
This resolves the bug by always treating everything as relative paths.
> Write relative paths correctly when writing experiment.json

- starfish/image/_stack.py
- starfish/test/image/test_imagestack_metadata.py
Also fixed a bug where we were joining the keys blindly, but they might not necessarily be strings.
Depends on #263, #271
> Add some basic tile metadata tests.

- starfish/image/_stack.py
- starfish/test/image/test_slicedimage_dtype.py
1. Actually test the data rather than calling all().  I completely misunderstood what that function does.
2. Add a uint test (separate from int)
3. Fix how fixed-point scaling works.  It should multiply by the difference in the ranges, not the max.
4. Change how floating point scaling works (it does not interpolate the range any more).
Depends on #271
> Fix the dtype test.

- starfish/test/dataset_fixtures.py
- starfish/test/image/test_imagestack.py
- starfish/test/image/test_imagestack_metadata.py
- starfish/test/image/test_slicedimage_dtype.py
- starfish/test/test_apply.py
1. Made it a simple function.
2. Remove the now unnecessary deepcopy calls.
> Remove the indirection for the synthetic stack factory

- starfish/test/full_pipelines/cli/test_iss.py
only rmtree if we don't detect the env variable set.
> [easy] environment variable to keep data from a iss run.

- REQUIREMENTS-DEV.txt
- starfish/test/full_pipelines/cli/test_iss.py
I did this a long time ago in #96, but I forgot the reason I did it by the time the code was being reviewed.  Now I remember: this is to generalize the retrieval of data fields when converting away from `Stack`.
> convert codebook retrieval to use jsonpathrw

- starfish/image/_stack.py
- starfish/pipeline/features/spots/detector/local_max_peak_finder.py
- starfish/pipeline/filter/_base.py
- starfish/pipeline/filter/bandpass.py
- starfish/pipeline/filter/clip.py
- starfish/pipeline/filter/gaussian_high_pass.py
- starfish/pipeline/filter/gaussian_low_pass.py
- starfish/pipeline/filter/richardson_lucy_deconvolution.py
- starfish/pipeline/filter/white_tophat.py
- starfish/test/test_apply.py
Two commits: 
- First moves the existing functionality of `apply(in_place=False)` which enables transformations of the stack into other objects to a `transform` function and enables true out-of-place `apply` functionality which always returns an `ImageStack`
- Second enables `in_place=False` for all filters.
> Ajc out of place apply

- starfish/pipeline/filter/gaussian_high_pass.py
- starfish/pipeline/filter/gaussian_low_pass.py
- starfish/test/pipeline/test_filter.py
- Makes `gaussian_high_pass` and `gaussian_low_pass` consistent
- Fixes typing through use of `Number`
- Adds 3D support for gaussian_high_pass (`osmFISH` needs it)
- Adds a test for new functionality
> [ENH] Enable 3-d support for gaussian high-pass

- starfish/constants.py
They can now be easily reused for constants in the Codebook and in IntensityTable.
Extricated from #298.
> Refactored the Enum classes

- starfish/image/_stack.py
- The default for rescale is False, which caused rescale to always run, because False is not None.
> [Easy] BUG: allow rescale to be False

- starfish/image/_stack.py
- raw shape's type + doc was out of date. 
This set of 8 Pull Requests supports pixel-based decoding using the IntensityTable and Codebook, updating the MERFISH notebook and all the pipeline components that it depends on. 
Note: depends on #313
> [1/8] DOC: fix raw shape docs and types

- starfish/intensity_table.py
- starfish/pipeline/features/spots/detector/gaussian.py
- starfish/test/dataset_fixtures.py
- starfish/test/pipeline/test_intensity_table.py
- Next PR enables direct conversion of ImageStack to IntensityTable by reshaping pixels. 
- This PR makes that reshaping process revertible by storing the shape of the ImageStack in the IntensityTable when it is created.
> [2/8] ENH: IntensityTable tracks the shape of the ImageStack it was created from

- starfish/constants.py
This allows for easier formatting without requiring a call to `.value`.  Only downside is that it's not obvious when one is dealing with an AugmentedEnum or a string.
> __str__ for AugmentedEnum

- examples/build_sample_experiment.py
- notebooks/allen_smFISH.ipynb
- notebooks/allen_smFISH.py
- starfish/codebook.py
All the interactions between the enum and xarray appear to still require the `.value`.  I didn't dive too deeply into figuring out why, however.
Depends on #342
> remove .value when possible.

- starfish/image/_stack.py
- starfish/intensity_table.py
- starfish/test/dataset_fixtures.py
- starfish/test/image/test_imagestack.py
- starfish/test/test_stack_intensity_table_reshaping.py
Add methods to:
- reshape ImageStack directly into an IntensityTable containing pixel intensities
- revert an IntensityTable containing pixel intensities back into an ImageStack
@ttung @dganguli There's a note at the bottom here questioning whether or not we want to support reshaping non-contiguous intensities (i.e. IntensityTables that contain _spots_) back into an ImageStack. My sense is no, since it would be a lossy reversion (we summarize spots as location, radius, intensity, not clear how to reconstruct original data). 
If we _don't_ support it, then I think having the method here is a bit weird, since it only works on one type of IntensityTable. Open to thoughts.
> [3/8] ENH: add methods to reshape pixels to/from intensities

- REQUIREMENTS.txt
- Travis installs pytest 3.3 by default, which breaks a dependency on pytest-xdist.
> ENH: require pytest>=3.6.3

- notebooks/ISS_Simple_tutorial_-_Mouse_vs._Human_Fibroblasts.ipynb
- notebooks/ISS_Simple_tutorial_-_Mouse_vs._Human_Fibroblasts.py
- starfish/codebook.py
- starfish/image/_stack.py
- starfish/intensity_table.py
- starfish/pipeline/features/spots/detector/gaussian.py
- starfish/test/dataset_fixtures.py
- starfish/test/full_pipelines/api/test_iss_api.py
- starfish/test/image/test_imagestack.py
- starfish/test/pipeline/test_codebook.py
- starfish/test/pipeline/test_intensity_table.py
- starfish/test/test_stack_intensity_table_reshaping.py
- starfish/test/test_synthetic_data.py
- starfish/typing.py
- Updates euclidean decode to work with the MERFISH requirements
- Swap out brute force search for NearestNeighbors
- add `min_intensity`, `max_distance`
- swap `np.nan` gene_ids to `None`. Both approaches are gross, but `np.nan` was being implicitly converted to string, so I find setting it as a string `None` more explicit. How to deal with `object` coordinate indices is on my list of things to talk to the xarray people about.
> [4/8] ENH: update euclidean codebook with MERFISH filters and NearestNeighbor search

- starfish/intensity_table.py
- starfish/pipeline/features/pixels/combine_adjacent_features.py
- starfish/test/pipeline/test_intensity_table.py
- Adds connected components pixel merging to IntensityTable
I've left some notes in the method string that discuss how we might implement this for non-contiguous methods. If the decision is to not support this, I'll remove that text prior to merging.
> [5/8] ENH: adapt connected-components pixel merging to IntensityTable

- starfish/pipeline/filter/__init__.py
- starfish/pipeline/filter/mean_high_pass.py
I added a mean high pass filter following the same pattern as the Gaussian high pass filter. The image typing is handled in the same manner as the Gaussian high pass filter (uses img_as_uint to convert) and will likely need to be updated when issue #316 is resolved. 
I did not add a test, as only some of the filters have tests. However, if the current test style for the Gaussian High Pass filter (just checking that the total intensity is reduced) is sufficient, I can add that.
> added mean high pass filter

- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.py
- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.ipynb
- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- notebooks/allen_smFISH.ipynb
- notebooks/allen_smFISH.py
- starfish/pipeline/filter/__init__.py
- starfish/pipeline/filter/_base.py
- starfish/pipeline/filter/bandpass.py
- starfish/pipeline/filter/clip.py
- starfish/pipeline/filter/gaussian_high_pass.py
- starfish/pipeline/filter/gaussian_low_pass.py
- starfish/pipeline/filter/mean_high_pass.py
- starfish/pipeline/filter/richardson_lucy_deconvolution.py
- starfish/pipeline/filter/white_tophat.py
- starfish/test/dataset_fixtures.py
- starfish/test/full_pipelines/api/test_iss_api.py
- starfish/test/full_pipelines/api/test_merfish.py
- starfish/test/pipeline/test_filter.py
- change `<filter_name>.filter` -> filter.run to improve ease of use of the package (all algorithms will be `<name>.run()`)
- update `bandpass.py` to adhere to various code standards
- line length 100
- typed return values
- typed parameters
- runtime parameters in run, algorithm parameters in constructor (`verbose` from `__init__` -> `run`)
- remove default arguments, except for `truncate` which I don't understand
- assign @dganguli to doc that method (not doc'd in trackpy)
- add 3d volume support
Notes:
- a bunch of notebooks got brought along for the ride due to the refactor. 
- Further PRs will address the other algorithms in filter.
> ENH: change filter.filter to filter.run, Update bandpass

- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.py
- starfish/pipeline/filter/util.py
- starfish/pipeline/filter/white_tophat.py
- starfish/test/dataset_fixtures.py
- starfish/test/full_pipelines/api/test_iss_api.py
- starfish/test/full_pipelines/cli/test_iss.py
- starfish/test/pipeline/test_white_tophat.py
- Update `white_tophat` with API changes similar to #364 
- Add 3d support
- change `disk_size` to `masking_radius` to make compatible with 3d. 
- Add tests
- Update notebooks
- Move the code that filters the numpy array out of `run` to make it consistent with other filters
- Fixes a bug where in_place wasn't being passed to `apply`
- Adds verbose option
> ENH: enable 3d white tophat, harmonize API

- starfish/munge.py
- starfish/pipeline/target_assignment/__init__.py
- starfish/pipeline/target_assignment/_base.py
- starfish/pipeline/target_assignment/point_in_poly.py
- starfish/test/full_pipelines/cli/test_iss.py
In attempting to modernize the target assignment API a few questions came up: 
1. Currently, target assignment emits a 2-column `Dataframe` that maps spot ids to cells. We no longer have an explicit representation of spot ids in the IntensityTable, and I wonder if the IntensityTable should just gain a column of "cell id" 
2. As far as I can tell, segmentation in starfish is purely 2d at the moment. This means that our assignment method is also 2d, however we assume but don't test this and I have a feeling that as a result, this method may not work for approaches that don't follow the ISS pipeline. 
Proposal: 
- If we store cell information in the `IntensityTable`, we can simply assign spots to cells using x/y coordinates (ignore z) until such a time as we support 3d segmentation. 
- …
> RFC: update target assignment API

- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.ipynb
- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
max_proj is supposed to take Indices, but prior to #350, it also magically worked with their string equivalents, due to the `__eq__` hack in `AugmentedEnum`.  Switching to an `xarray` backend removed the indexing, so it doesn't work any more.
> Unbreak the merfish notebook.

- REQUIREMENTS.txt
Pin showit to >= 1.1.4, which has https://github.com/freeman-lab/showit/pull/5 and https://github.com/freeman-lab/showit/pull/6 merged.
Test plan: reran @csweaver's repro steps and successfully ran starfish.
Fixes #372
> Fix python setup.py install

- starfish/image/_filter/gaussian_high_pass.py
- starfish/image/_filter/gaussian_low_pass.py
- starfish/image/_filter/util.py
There is an inconsistency in skimage's gaussian filter documentation which suggests that scalar kernel sizes are broadcast to the image depth. This is not true, and this PR fixes rectifies the inconsistency by broadcasting to full-size kernels in the starfish codebase. Since this code is used by multiple functions, it is factored out into `util.py`.
> BUG: fix skimage anisotropic kernel

- REQUIREMENTS.txt
Old versions of pandas do not support `pd.MultiIndex.to_frame()`
> increase pandas version to ensure multiindex support

- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- Implements a fix that removes a cast to uint prior to scaling to avoid a loss of precision
- Updates the notebook to work with the new API organization
- Note also that the combination of anisotropic kernel and this change do fix the copy number issue.
> BUG: fix casting issue in MERFISH notebook that was causing a loss of precision

- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.py
- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- starfish/experiment.py
Per request, this PR renames `experiment.org` to `experiment.format_metadata`
> [6/5] Rename experiment.org

- .travis.yml
We don't actually need it as far as I can tell.
> remove sudo requirement

- starfish/experiment/builder/cli.py
- starfish/starfish.py
1. Create a "main" method for the script.
2. Add an entry point for the pip package.
Test plan:
```
% pip install -e .
% build_sample_experiment --help
```
Connects to #418
> Create entry point for starfish/experiment/builder/cli.py

- .flake8
- starfish/__init__.py
Adds a warning filter to get rid of numpy x cython x scipy dtype warning (happens when versions of scipy and numpy don't match up, is apparently harmless. 
The warning: 
```python
/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: 
RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
return f(*args, **kwds)
```
adds E402, "imports must be at top of file" to suppressed filters. Per our previous conversation, it's not easy to get file-specific granularity with flake. 
See e.g. 
https://github.com/ContextLab/supereeg/pull/176
> suppress harmless cython warning

- starfish/stack.py
- Makes the outcome (`hybridization_images.json` has `.json`) as one would expect from the request for path+prefix.
> [Easy] fix imagestack.write so that it correct appends a prefix

- REQUIREMENTS-DEV.txt
- notebooks/py/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.py
- notebooks/py/ISS_Pipeline_-_Breast_-_1_FOV.py
- notebooks/py/ISS_Simple_tutorial_-_Mouse_vs._Human_Fibroblasts.py
- notebooks/py/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- notebooks/py/allen_smFISH.py
- notebooks/py/osmFISH.py
Picks up this sort-of [format change](https://github.com/ttung/nbencdec/commit/9e3548c1aef920f3bf4cbec4f9894504777a23d2).
Reason it's not completely breaking is that it still decodes correctly, just that each markdown cell will have a space in front of each line.
Rationale for this change: markdown cells get prefixed with "# ", and if it's just an empty line, and an editor comes along and strips trailing whitespace, then it becomes "#", which doesn't decode the same as "# ".
> Upgrade to nbencdec 0.0.5

- starfish/experiment/__init__.py
- starfish/experiment/builder/__init__.py
It's currently hardcoded to 0.0.0; it should be 1.0.0.
> Experiment builder should write the current version number

- notebooks/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.ipynb
- notebooks/py/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.py
`nbencdec-0.0.5` unescaped markdown cells incorrectly, and #446 apparently landed using `nbencdec-0.0.5`.  This reverts the markdown cell changes.
> Fix notebook markdown cells

- starfish/intensity_table.py
- starfish/spots/_detector/combine_adjacent_features.py
- starfish/spots/_detector/detect.py
- starfish/test/dataset_fixtures.py
- starfish/test/pipeline/test_intensity_table.py
* not necessary if we are not supporting reversion from IntensityTable to ImageStack
* adds flexibility to IntensityTable, as now we don't need to pass along an attr.
> ENH: Remove IntensityTable's image_shape

- starfish/test/dataset_fixtures.py
- starfish/test/image/test_imagestack.py
- starfish/test/pipeline/test_intensity_table.py
- starfish/test/test_stack_intensity_table_reshaping.py
First of many, many PRs that change fixtures into factories. In this case, I also renamed it to have a more informative name.
> ENH: change single_synthetic_spot to a factory function

- .gitignore
- examples/get_iss_breast_data.py
- examples/get_iss_data.py
- starfish/experiment/builder/__init__.py
- starfish/experiment/builder/imagedata.py
This PR:
1. Introduces get_iss_breast_data.py, which converts raw data from s3://czi.starfish.data.public/browse/raw/20180820/iss_breast/ to spaceTx formatted data. This will be our first real multi-fov dataset. 
2. re-names things. image -> tile, image_fetcher -> tile_fetcher
I tested this PR in a notebook locally. I downloaded the 1 FOV from he breast data formatter and ran the ISS breast notebook against it. It worked.
Remaining work for @ambrosejcarr :
1. Run this tool.
2. Upload formatted data to s3 browsable.
3. Copy codebook.json from 1 FOV dataset over to latter bucket.
Remaining work for @ttung :
1. Get cracking on experiment API so that...
Remaining work for Deep:
1. Use experiment API to analyze this entire dataset (blocked by @ttung )
2. Generate copy number plot for call 2 …
> Add example of raw->spacetx format conversion for ISS Breast Data

- examples/get_merfish_u20s_data.py
Remaining work includes:
1. Running this tool against all raw data
2. Uploading formatted data to cloud
3. Using experiment API against this dataset to test parsing larger datasets
> Upload example of transforming raw MERFISH -> spaceTx formatted data

- starfish/test/full_pipelines/api/test_allen_smFISH.py
- starfish/test/full_pipelines/api/test_dartfish.py
- starfish/test/full_pipelines/api/test_iss_api.py
- starfish/test/full_pipelines/api/test_merfish.py
Strategy: 
- verified real notebooks work
- cropped a small (x, y) piece of the 5-d tensor
- calculated the outputs over the small piece as a python test
- added assertions at each stage of processing to isolate earliest point of failure
- tests will probably fail on ANY change to processing algorithms, are designed to err on over-sensitivity. 
* Also adds non-functional test for allen_smFISH, currently blocked by checksum issues
* Overall testing time is reduced, as this reduces the time taken for the existing iss test.
> TST: add notebook tests on cropped data for ISS_Pipeline, MERFISH, DARTFISH

- starfish/codebook.py
- starfish/test/pipeline/test_codebook.py
This allows us to use file:/// schema URLs.
> Use slicedimage's backends to load codebooks.

- starfish/codebook.py
- starfish/intensity_table.py
- starfish/test/dataset_fixtures.py
- Update doctests in codebook that escaped refactoring of constants -> types.
- Remove an `image_shape` attr that escaped expulsion from IntensityTable.
- Remove a fixture that wasn't used.
> Remove some unused items

- starfish/experiment/builder/imagedata.py
This causes the issue @joshmoore is seeing [here](https://github.com/joshmoore/build-starfish/issues/1#issuecomment-416537231)
Test Plan: ran `starfish build --fov-count 1 --hybridization-dimensions '{"h": 2, "c": 2, "z": 1}' /tmp/2`
> Add missing @property annotation to tile_data_handle

- starfish/test/dataset_fixtures.py
- starfish/test/pipeline/test_filter.py
- Removes a slow fixture and replaces it with some synthetic data. 
- Gains ~ 5s on testing time.
> Remove MERFISH fixture, speed up filter tests

- validate_sptx/validate_sptx.py
This was missing from https://github.com/spacetx/sptx-format/pull/12
> Missing rename from hybridization_images to primary_images

- setup.py
- sptx-format/README.md
- validate_sptx/examples/field_of_view/dartfish_field_of_view.json
- validate_sptx/examples/field_of_view/dartfish_nuclei.json
- validate_sptx/examples/field_of_view/field_of_view.json
- validate_sptx/schema/field_of_view/field_of_view.json
They are redundant since the field of view manifests are indexed by their name already.
With this change, https://github.com/spacetx/slicedimage/pull/55 *should* no longer be necessary.
> Remove the fov id from the field of view manifests

- .flake8
- Makefile
- starfish/spots/_target_assignment/_base.py
- starfish/stack.py
- starfish/test/full_pipelines/api/test_dartfish.py
- starfish/test/full_pipelines/api/test_merfish.py
- starfish/test/full_pipelines/cli/test_validate.py
- starfish/test/image/test_imagestack.py
- starfish/test/pipeline/test_codebook.py
- starfish/test/pipeline/test_intensity_table.py
- starfish/test/pipeline/test_spot_detection.py
- starfish/util/exec.py
- validate_sptx/cli.py
- validate_sptx/test_fuzz.py
Enable F401 (unused import) _except_ for __init__.py.  There's too much code in __init__.py that pulls stuff in for the benefit of setting up a package, so we don't want that validation.
> Tweak linting infrastructure

- examples/get_iss_data.py
- starfish/experiment/__init__.py
- starfish/test/full_pipelines/api/test_allen_smFISH.py
- starfish/test/full_pipelines/api/test_dartfish.py
- starfish/test/full_pipelines/api/test_iss_api.py
- starfish/test/full_pipelines/api/test_merfish.py
- starfish/test/full_pipelines/cli/test_iss.py
This allows fovs to definitively be addressed by name.
> Experiments can only point to Collections.

- examples/get_iss_breast_data.py
tifffile writes files that include a timestamp.  If that timestamp is not provided, it defaults to the current time.  That means every time we run the script, we get slightly different files.  This is undesirable because:
1. it makes it hard to upload data sets with file format changes.
2. it pollutes the disk cache
With this change, we now set the timestamp to unixtime 0.
Test plan: regenerated the ISS breast data set, then ran strings on one of the TIFF files.
```
[tt]:~/microscopy/starfish-formatted-data> strings breast/nuclei-fov_007-Z0-H0-C0.tiff | grep 1969
1969:12:31 16:00:00
```
> Build consistent files for iss breast data set.

- starfish/experiment/__init__.py
- starfish/stack.py
Updated API proposal: 
```python
import starfish
```
```python
experiment = starfish.Experiment.from_json('https://dmf0bdeheu4zf.cloudfront.net/browse/formatted/20180912/iss_breast/experiment.json')
```
```python
experiment
<starfish.Experiment (FOVs=16)>
{'fov_000': <starfish.FieldOfView>
Primary Image: <slicedimage._tileset.TileSet object at 0x12f60f0f0>
Auxiliary Images:
nuclei: <slicedimage._tileset.TileSet object at 0x12f6899e8>
dots: <slicedimage._tileset.TileSet object at 0x12f698e80>, 'fov_001': <starfish.FieldOfView>
Primary Image: <slicedimage._tileset.TileSet object at 0x12f60fd30>
Auxiliary Images:
nuclei: <slicedimage._tileset.TileSet object at 0x12f689240>
dots: <slicedimage._tileset.TileSet object at 0x12f698550>, 'fov_002': <starfish.FieldOfView>
Primary Image: …
```
> Add __repr__ strings to ImageStack, Experiment, and FieldOfView

- README.md
- starfish/spots/_detector/__init__.py
- starfish/test/full_pipelines/cli/test_iss.py
They should not be given a directory to write an arbitrary file.  This makes it hard to compose pipelines in the CLI.
Updated README.
> CLI commands should always write to an explicit file

- examples/get_iss_breast_data.py
- examples/get_iss_data.py
- examples/get_merfish_u20s_data.py
- starfish/experiment/builder/__init__.py
- starfish/experiment/builder/defaultproviders.py
- starfish/experiment/builder/providers.py
There are some TODOs introduced by this PR that @dganguli will probably need to fill in.
Test plan: `python examples/get_iss_breast_data.py /Users/ttung/Downloads/starfish_data/mignardi_breast_1/raw/ ../starfish-formatted-data/breast/` + visual inspection
Depends on #566
> Allow TileFetchers to provide the coordinates for a tile.

- .gitignore
Now that we suggest a specific `venv` install, `gitignore` that by default.
> [Easy] add suggested gitignore directory to gitignore

- notebooks/subdir.mk
virtualenv only guarantees that python is in your path, not python3.6 (which is provided by _some_ virtualenvs).
> Change python3.6 executable to python

- docs/source/API/spots/decoding/decoding.rst
- docs/source/API/spots/detection/detection.rst
- docs/source/API/spots/target_assignment/target_assignment.rst
- starfish/spots/_decoder/__init__.py
- starfish/spots/_decoder/_base.py
- starfish/spots/_decoder/per_round_max_channel_decoder.py
- Link up `spots` modules to the docs. 
- Add docstring to `PerRoundMaxChannelDecode`
- Refactor `DecoderAlgorithmBase.decode` to `DecoderAlgorithmBase.run` to match starfish API.
> DOC: link spots modules to docs

- starfish/experiment/builder/__init__.py
- starfish/experiment/experiment.py
- starfish/experiment/version.py
- starfish/test/test_version.py
> [easy] Move experiment version data to its own package.

- Makefile
python -m venv on travis produces broken virtualenvs.  This circumvents the issue by invoking virtualenv instead.  This means it doesn't always work perfectly in local dev environments as virtualenv is not a requirement and python3.6 is, but working on travis is more important for this rule.
Test plan: see https://travis-ci.org/spacetx/starfish/builds/430296829
> Fix the notebook + pypi pkg test

- docs/source/contributing/contributing.md
1. Commit names being informative is confusing.  Changed this to commit summaries.
2. An ask for test plan.
Test plan: None whatsoever.
> tweak the text on the code contribution guidelines

- docs/source/API/image/filtering/filtering.rst
- docs/source/API/image/registration/registration.rst
- docs/source/API/image/segmentation/segmentation.rst
- docs/source/API/spots/decoding/decoding.rst
- docs/source/API/spots/detection/detection.rst
- docs/source/API/spots/target_assignment/target_assignment.rst
- docs/source/conf.py
- readthedocs.yml
- starfish/readthedocs.yml
per http://blog.readthedocs.com/python-36-support/ , this is how to make our docs build not fail.
> Build docs with python 3.6

- README.rst
Adds badges for: 
- docs master build
- travis master build
- code coverage
Testing strategy: 
Look at rendered README: https://github.com/spacetx/starfish/blob/ajc-badge-docs/README.rst
> Add README badges

- README.rst
README points at wrong image loctions, breaks splash page docs.
> Update README.rst to reflect position in root directory, not docs

- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.ipynb
- notebooks/allen_smFISH.ipynb
- notebooks/osmFISH.ipynb
- notebooks/py/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- notebooks/py/allen_smFISH.py
- notebooks/py/assay_comparison.py
- notebooks/py/osmFISH.py
The fov field was removed in https://github.com/spacetx/sptx-format/pull/24, but some of the data sets still have it.
Test plan: make -j run_notebooks
> Point notebooks at data sets without the 'fov' fields in TileSets.

- starfish/image/_filter/__init__.py
- starfish/image/_filter/_base.py
- starfish/image/_filter/bandpass.py
- starfish/image/_filter/clip.py
- starfish/image/_filter/gaussian_high_pass.py
- starfish/image/_filter/gaussian_low_pass.py
- starfish/image/_filter/mean_high_pass.py
- starfish/image/_filter/richardson_lucy_deconvolution.py
- starfish/image/_filter/scale_by_percentile.py
- starfish/image/_filter/white_tophat.py
- starfish/image/_filter/zero_by_channel_magnitude.py
It should always return an ImageStack.  If it's in_place, then it returns the original.  If not, it returns the new ImageStack.
Test plan: `pytest starfish/test/pipeline/test_filter.py`
> Fix the function signature for <filter>.run(..)

- REQUIREMENTS-DEV.txt
- REQUIREMENTS.txt
- REQUIREMENTS.txt.in
- examples/get_iss_breast_data.py
- examples/get_iss_data.py
- examples/get_merfish_u20s_data.py
- starfish/experiment/builder/__init__.py
- starfish/experiment/builder/defaultproviders.py
- starfish/experiment/builder/providers.py
Instead of returning a file handle to the source, we now just get the tile data and use the new file_format argument to `generate_partition_document` introduced in https://github.com/spacetx/slicedimage/pull/64.  This means we don't have to generate the TIFF file and save to an in-memory file in the experiment/image builders.
This was previously opened as #584 but github helpfully closed that for me.
Test plan: test_iss cli test should cover this case.  separately, re-ran the entire test suite.
> Change tile_data_handle to tile_data

- starfish/experiment/builder/__init__.py
- starfish/experiment/builder/defaultproviders.py
- starfish/experiment/builder/providers.py
Most TileFetchers are very simple.  They simply return an instance of a FetchedTile.  Rather than duplicate this code over and over again, we can just create a factory that builds these, based on the most common patterns.
Test plan: `starfish build --fov-count 1 --hybridization-dimensions '{"h": 2, "c": 2, "z": 1}' /tmp/2`
> Introduce tile_fetcher_factory

- starfish/experiment/builder/defaultproviders.py
- starfish/imagestack/imagestack.py
- starfish/test/image/test_imagestack_metadata.py
- starfish/test/image/test_slicedimage_dtype.py
This allows us to unify all the stack creation code paths.
Test plan: make -j all run_notebooks
Depends on #610
> Refactor synthetic_stack to use build_image in experiment/builder

- starfish/image/_filter/gaussian_high_pass.py
- starfish/image/_filter/gaussian_low_pass.py
Some of the Filter classes have unclear or potentially wrong types in the docstring for the input image in the filtering method (e.g., high_pass() in GaussianHighPass). I changed the GHP and GLP filters to np.float32 based on my current understanding of the pipeline and the preserve_float_range() calls.
In going through the filters, I noticed that some (e.g., Clip) still have code to support int. Should filters still support int even though the pipeline internal standard is float? I can make a separate issue if this requires discussion.
> Fix image type Filter docstrings

- docs/source/usage/iss/iss_cli.sh
- starfish/spots/_detector/gaussian.py
- starfish/test/full_pipelines/cli/test_iss.py
It's now a part of the spot detectors' arguments, so it needs to precede the algorithm name.
Test plan: `. docs/source/usage/iss/iss_cli.sh`
> Remove duplication of the --blobs-stack argparse parameter

- starfish/image/_filter/clip.py
Everything should transact in float32.
Thanks to @kevinyamauchi for [noticing this](https://github.com/spacetx/starfish/pull/621#issue-217750314)
Test plan: make -j all
> Remove type handling code from Clip pipeline component

- starfish/imagestack/imagestack.py
n_processes is currently left behind when in_place = False.
> [Easy] fix apply bug where n_processes was not propagated when in_place=False

- starfish/test/pipeline/test_filter.py
1. Remove `test_gaussian_high_pass_apply`, which is the same as `test_gaussian_high_pass`.
2. Rename `test_gaussian_high_pass_apply_3d` to `test_gaussian_high_pass_3d`.
> Clean up gaussian tests

- notebooks/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.ipynb
- notebooks/py/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.py
- starfish/__init__.py
- starfish/codebook/codebook.py
- starfish/experiment/experiment.py
- starfish/spots/_decoder/__init__.py
- starfish/spots/_decoder/per_round_max_channel_decoder.py
- starfish/spots/_detector/pixel_spot_detector.py
- starfish/test/dataset_fixtures.py
- starfish/util/synthesize.py
This allows us to modularize it like experiment and imagestack.
> [CODEBOOK 1/3] Move codebook to its own package.

- starfish/experiment/builder/__init__.py
Fix the list of dimensions written to the TileSet metadata
It should be the set of all physical and non-physical dimensions.
Test plan: make -j test
> Fix the list of dimensions written to the TileSet metadata

- examples/get_iss_data.py
- starfish/experiment/builder/__init__.py
- starfish/test/dataset_fixtures.py
This allows us to update the codebook format without mucking around in code elsewhere.
> [CODEBOOK 2/3] Use the file IO mechanism in Codebook to write codebooks for tests.

- Makefile
- REQUIREMENTS-DEV.txt
- REQUIREMENTS-DEV.txt.in
- REQUIREMENTS-NOTEBOOK.txt
Since we slurp in the notebook code for unit testing as of #583, we actually need the notebook requirements to develop.  This brings in the only requirement in REQUIREMENTS-NOTEBOOK.txt into REQUIREMENTS-DEV.txt.in and REQUIREMENTS-DEV.txt.
> Integrate REQUIREMENTS-NOTEBOOK into REQUIREMENTS-DEV

- starfish/image/_filter/__init__.py
- starfish/image/_filter/bandpass.py
- starfish/image/_filter/clip.py
- starfish/image/_filter/gaussian_high_pass.py
- starfish/image/_filter/gaussian_low_pass.py
- starfish/image/_filter/mean_high_pass.py
- starfish/image/_filter/richardson_lucy_deconvolution.py
- starfish/image/_filter/scale_by_percentile.py
- starfish/image/_filter/white_tophat.py
- starfish/image/_filter/zero_by_channel_magnitude.py
- starfish/image/_registration/__init__.py
- starfish/image/_registration/fourier_shift.py
- starfish/image/_segmentation/__init__.py
- starfish/image/_segmentation/watershed.py
- starfish/pipeline/algorithmbase.py
- starfish/pipeline/pipelinecomponent.py
- starfish/spots/_decoder/__init__.py
- starfish/spots/_decoder/per_round_max_channel_decoder.py
- starfish/spots/_detector/__init__.py
- starfish/spots/_detector/gaussian.py
- starfish/spots/_detector/local_max_peak_finder.py
- starfish/spots/_detector/pixel_spot_detector.py
- starfish/spots/_target_assignment/__init__.py
- starfish/spots/_target_assignment/point_in_poly.py
- starfish/starfish.py
- starfish/test/pipeline/test_white_tophat.py
All the methods that don't need to be seen get renamed with a _ prefix.
There is a wrinkle in PipelineComponent since the destination name already exists, so that gets further renamed.
Test plan: make -j run_notebooks all
Fixes #589
> [easy] Hide code that the user doesn't need to see.

- examples/get_iss_breast_data.py
#572 fixes some of the vocabulary such that we avoid `hybridization`, but I didn't fix `get_iss_breast_data.py`.
Test plan: successfully run `python examples/get_iss_breast_data.py /Users/ttung/Downloads/starfish_data/mignardi_breast_1/raw/ ../starfish-formatted-data/breast/ 16`
Fixes #649
> Fix get_iss_breast_data.py

- notebooks/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.ipynb
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.ipynb
- notebooks/allen_smFISH.ipynb
- notebooks/assay_comparison.ipynb
- notebooks/osmFISH.ipynb
- notebooks/py/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.py
- notebooks/py/ISS_Pipeline_-_Breast_-_1_FOV.py
- notebooks/py/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- notebooks/py/allen_smFISH.py
- notebooks/py/assay_comparison.py
- notebooks/py/osmFISH.py
- starfish/data/__init__.py
- starfish/test/full_pipelines/api/test_allen_smFISH.py
1. `test_data` => `use_test_data` for clarity.
2. Use starfish.data for the assay comparison notebook.
Test plan: `python notebooks/py/assay_comparison.py`
> Improvements to starfish.data

- starfish/test/pipeline/test_filter.py
This PR consolidates the tests for the gaussian high pass and mean high pass filters with is_volume=False/True, as suggested by @ambrosejcarr in #655.
> Consolidated Gaussian/mean high pass filter tests

- starfish/intensity_table.py
Fixes #552 and simplifies conversion of `IntensityTable` annotations `pd.DataFrame`
> Fix to_dataframe bug #552

- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/py/ISS_Pipeline_-_Breast_-_1_FOV.py
- starfish/imagestack/imagestack.py
- starfish/intensity_table.py
- starfish/test/full_pipelines/api/test_dartfish.py
- starfish/test/full_pipelines/api/test_iss_api.py
- starfish/test/full_pipelines/api/test_merfish.py
- starfish/test/image/test_apply.py
- starfish/test/image/test_imagestack.py
- starfish/test/image/test_slicedimage_dtype.py
- starfish/test/pipeline/test_filter.py
- starfish/test/test_stack_intensity_table_reshaping.py
- starfish/util/synthesize.py
Most of this is straightforward, except for `starfish/test/image/test_imagestack.py::test_synthetic_spot_creation_produces_an_imagestack_with_correct_spot_location`, which is complicated because advanced indexing is wonky in xarray.
Fixes #673
> Expose ImageStack's data as an xarray.

- examples/get_iss_breast_data.py
- examples/get_iss_data.py
- examples/get_merfish_u20s_data.py
- starfish/experiment/builder/__init__.py
- starfish/experiment/builder/defaultproviders.py
- starfish/experiment/builder/providers.py
- starfish/test/image/test_slicedimage_dtype.py
This reverses what was done with #658 and partly done in #600 because this allows us to pass tile_data as a future.  This is necessary to prevent memory consumption from blowing up.
Note that this does not actually change how we load the data.  A newer version of slicedimage (one that includes #68) is required to actually take advantage of the future.
Test plan: travis.
> Make tile_data _not_ a property.

- starfish/test/image/filter/test_api_contract.py
- starfish/test/image/filter/test_zero_by_channel_magnitude.py
- starfish/test/image/test_imagestack_coordinates.py
Test plan: `pytest starfish/test/image/filter/test_api_contract.py`
> Updated test_api_contract.py to use .xarray instead of .numpy_array

- REQUIREMENTS-DEV.txt
- REQUIREMENTS.txt
- REQUIREMENTS.txt.in
- starfish/experiment/builder/__init__.py
Use `set_numpy_array_future` to avoid loading the tile data until we start writing out to disk.
Depends on #667 
Fixes https://github.com/spacetx/starfish/issues/666
> Fix memory consumption issues with merfish formatter

- REQUIREMENTS-DEV.txt
- REQUIREMENTS.txt
- REQUIREMENTS.txt.in
- setup.py
Both notebooks had datasets where the tile shapes were not consistently provided.  https://github.com/spacetx/slicedimage/pull/72 broke the recording of the tile shape, and https://github.com/spacetx/slicedimage/pull/73 fixes it.
Test plan: `make -j run__notebooks/py/ISS_Pipeline_-_Breast_-_1_FOV.py run__notebooks/py/assay_comparison.py`
> Fix assay_comparison and ISS notebooks

- docs/source/debugging.rst
- docs/source/index.rst
This doc will eventually detail how users should expect to deal with our rapid iteration. It brought up a few questions that I think we should mull over: 
1. **Assuming users are using starfish with data we host, how do they find the right datasets that match the starfish version?** 
1. Right now, we go by date. This is fine if they clobber their notebooks with ours, but it's not great UX for a user that is creating their own notebooks. Could we replace our date-stamps with version names that match our starfish/slicedimage versions? Presumably a breaking change that requires new data warrants a version change, and so this should be feasible. 
2. **Assuming users are using starfish with data they've generated, how do they update their SpaceTx-format metadata to work with the current …
> RFC: user-facing debugging instructions

- docs/source/API/core_objects/codebook.rst
- docs/source/API/core_objects/experiment.rst
- docs/source/API/core_objects/field_of_view.rst
- docs/source/API/core_objects/image_stack.rst
- docs/source/API/core_objects/index.rst
- docs/source/API/core_objects/intensity_table.rst
- starfish/experiment/experiment.py
- Links Experiment and Field of View to the docs. 
- Refactors some docstrings in the above files so sphinx doesn't choke on them (with some textual changes, please check my modifications). 
Also I discovered how to make internal links with ```:ref:`ReferenceName` ```. I'll start weaving those into the docs.
> Ajc experiment docs

- starfish/image/_filter/__init__.py
- starfish/image/_filter/laplace.py
This filter enhances spots, and is used by the osmFISH pipeline. Under the hood, it's simply a call to ```scipy.ndimage.gaussian_laplace```
Note that there is no test for this filter. From offline conversations, it's not clear what our testing strategy for filters are. Especially for filters that are pulled in from existing libraries, like this one. Really, what we want to test here is that the Starfish specific wrapping code works as expected.
For now, I'll rely on [osmFISH 5/5] notebook to function as the test of this filter.
> [osmFISH 2/5] Implement Laplacian Filter

- REQUIREMENTS.txt
- REQUIREMENTS.txt.in
- environment.yml
- starfish/spots/_detector/local_max_peak_finder.py
- starfish/types/_constants.py
This SpotDetector uses skimage.local_max_peak_finder, and implements the automatic thresholding algorithm employed by pysmFISH.
Several outstanding issues remain:
- skimage.local_max_peak_finder only works in 3D
- the automatic thresholding code needs some documentation
- it's unclear how to pull out the radius from these algorithms. in fact, the radius is not needed for sequential smFISH anyways. radius is mostly just necessary for non-pixel spot detection based methods for multiplexed techniques
- i'm not sure the CLI hookup was done correctly. it's not tested either.
- there's no test for this. but i think that's easy to implement? for now i rely on the notebook from [osmFISH 5/5]
FYI @simone-codeluppi
> [osmFISH 4/5] Implement LocalMaxPeakFinder

- environment.yml
Docker resolves to a different version than what is in requirements.txt, and then pip install conflicts and is unable to uninstall what docker installed.
Test plan: https://travis-ci.org/spacetx/starfish/jobs/442465711
> pin certifi in docker env

- examples/get_iss_breast_data.py
- examples/get_iss_data.py
- examples/get_merfish_u20s_data.py
- starfish/experiment/builder/defaultproviders.py
- starfish/experiment/builder/providers.py
- starfish/spots/_detector/detect.py
- starfish/test/dataset_fixtures.py
- starfish/test/image/test_imagestack_metadata.py
- starfish/test/spots/detector/test_spot_detection.py
hyb, as a dimension, should be round/r.
Note that I did not change 'hybridization', which is a reference to the primary image(s), pending the discussion of singular vs plural. :)
Test plan: `make -j fast run_notebooks`
> Nuke a bunch of references to hyb.

- starfish/experiment/experiment.py
Current master throws an error when executing: 
```python3
import starfish
exp = starfish.Experiment.from_json(<pick_your_experiment.json>)
exp.__repr__()
```
> Fix Field of View repr

- starfish/expression_matrix/expression_matrix.py
- starfish/util/try_import.py
This allows us to maintain IDE compatibility, and provide nice error messages.
This is based on top of #684
Test plan:
```
In [7]: a.save_loom('/tmp/aobab')
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/microscopy/starfish/starfish/util/try_import.py in wrapper(*args, **kwargs)
14             try:
---> 15                 func(*args, **kwargs)
16             except ImportError as ex:
~/microscopy/starfish/starfish/expression_matrix/expression_matrix.py in save_loom(self, filename)
47         """
---> 48         import loompy
49 
ModuleNotFoundError: No module named 'loompy'
The above exception was the direct cause of the following exception:
ImportError …
```
> Reimplement try_import as a decorator

- sptx_format/README.md
#641 changed the format such that the codebook's top level construct is a dictionary to accommodate a version field.  This updates the example in the codebook format specification.
Fixes #746
> Fix codebook format specification

- starfish/image/_filter/bandpass.py
- starfish/image/_filter/clip.py
- starfish/image/_filter/gaussian_high_pass.py
- starfish/image/_filter/gaussian_low_pass.py
- starfish/image/_filter/laplace.py
- starfish/image/_filter/mean_high_pass.py
- starfish/image/_filter/richardson_lucy_deconvolution.py
- starfish/image/_filter/scale_by_percentile.py
- starfish/image/_filter/util.py
- starfish/image/_filter/white_tophat.py
- starfish/imagestack/imagestack.py
- starfish/spots/_detector/detect.py
- starfish/test/image/test_apply.py
Split by is ambiguous because it could be axes along which we are splitting the image, or it could be the dimensions that remain.  Right now, it means the latter.
Group by, however, is less ambiguous.
Updated all the callers in the process.
Depends on https://github.com/spacetx/starfish/pull/736
> Rename split_by to group_by.

- starfish/imagestack/_mp_dataarray.py
- starfish/imagestack/imagestack.py
Right now, we only wrap the xarray.  Next we will add the shmem construct that will allow us to pass data to and from subprocesses without copying.
> Wrapper class for the xarray in ImageStack.

- starfish/multiprocessing/shmem.py
- starfish/test/test_multiprocessing.py
1. Added the shmem module, which wraps some very ugly logic necessary to pass multiprocessing.Array objects between processes.
2. Add tests for a multiprocessing.Array backing a numpy array to be passed between processes.
Test plan: wrote tests!
> Tests for passing a multiprocessing.Array backing a numpy array between processes

- starfish/imagestack/_mp_dataarray.py
- starfish/test/test_multiprocessing.py
https://github.com/spacetx/starfish/pull/737 created the wrapper class for xr.DataArray, but fundamentally, it was still a copy-on-write construct that did not allow multiple writers across processes to operate on it.  This swaps out the underpinnings with the constructs introduced and tested in https://github.com/spacetx/starfish/pull/738, such that processes that we fork out in `ImageStack` can cooperatively work on multiple parts of the tensor concurrently.
Whenever we construct a `MPDataArray`, we now construct a `multiprocessing.Array`, and layer a `numpy` object on top of that memory.  Then we construct a `xr.DataArray` around that `numpy` object.  Fun, right?
We freely copy xr.DataArray around when we want to run `ImageStack.apply` not in-place, so we have a `__deepcopy__` method …
> Make MPDataArray actually shared-memory

- sptx_format/schema/field_of_view/tiles/coordinates.json
- sptx_format/schema/field_of_view/tiles/indices.json
Currently this contains a minor unification, but the given URLs don't resolve. One possibility is to just add "tree/master", but that shouldn't be the general state of the files. On release we could conceivably update the files to point to the upcoming release roughly like https://github.com/spacetx/starfish/tree/0.0.27/validate_sptx/schema/experiment.json as a partial implementation of gh-700.
> fix schema IDs

- .flake8
- MANIFEST.in
- Makefile
- setup.py
- sptx_format/cli.py
- starfish/experiment/experiment.py
- starfish/starfish.py
- starfish/util/exec.py
0.0.28 is missing the schema json files for sptx-format leading
to the error:
```
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/sptx_format/util.py", line 51, in load_json
with open(json_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory:
'/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/sptx_format/schema/experiment.json'
make: *** [run__notebooks/py/assay_comparison.py] Error 1
```
see: gh-717
> sptx-format: remove uses of validate_sptx/validate-sptx

- starfish/experiment/experiment.py
Experiment.from_json() now creates an experiment with multiple FOVs. Before, every time a FieldOfView was added to the experiment, its image_tilesets overrode that of the previous one so all the FOVs in the Experiment had the same images
> Fixed experiment from_json for multiple fov

- starfish/imagestack/imagestack.py
- starfish/util/__init__.py
- starfish/util/_functools.py
Currently, we are slicing the tensor in the parent process, and passing the slices to each of the child processes.  To share memory more efficiently, we want to pass the entire tensor (and the backing shared memory construct) to the child processes, and instead just pass the slice indices to the child process.  The child process will slice out the part of the tensor it is interested in, and then pass it to the callable (filter, spot calling code, etc.).
`_multiprocessing_workflow` is the entry point for the child processes.  It retrieves the tensor using the constructs provided by https://github.com/spacetx/starfish/pull/738, and slices the data.
Remove `_iter_tiles` as it is no longer needed.
Depends on #736, #737, #738, #739, #740
This is a continuation of #741
> Pass the entire tensor to child processes as well as the slice indices

- starfish/imagestack/imagestack.py
Rather than have apply calculate the output, and pass it back to the parent process, we merge the results back into the original tensor.  This is possible because all the child processes use a shared memory construct provided by https://github.com/spacetx/starfish/pull/738.  This is done in the finalizer callable provided by https://github.com/spacetx/starfish/pull/754.
Depends on #736, #737, #738, #739, #740, #754 
> Apply to save results in-place

- starfish/imagestack/physical_coordinate_calculator.py
1. `physcial` -> `physical`.
2. Reorder min before max for `_calculate_physical_pixel_size`.
3. Small line wrapping tweaks.
4. Fix annotations and docblock for `_recalculate_physical_coordinate_ranges`.
> [easy] stylistic cleanup of physical_coordinate_calculator.py

- starfish/image/_filter/bandpass.py
The Bandpass filter wraps trackpy's bandpass filter. This underlying filter accepts a None value for the threshold parameter. This None value then internally gets set to 1/255. This makes sense for uint8 images, but not for our float32 images which contain small values in [0,1]. This caused some pain for @berl who is used to using trackpy in this manner. 
To counteract this issue, I set the default for the threshold to 0 (which is effectively a noop) and raise an exception if the user passes in a None value.
> [Easy] Add default threshold parameter for Bandpass filter

- docs/source/sptx-format/index.rst
- sptx_format/README.md
* Update codebook docs to adhere to spec
* Update wording to reflect that SpaceTx Format is no longer a repository
* Change Title to match format of other docs headings
> Fix Codebook Docs

- REQUIREMENTS.txt
This is due to https://nvd.nist.gov/vuln/detail/CVE-2018-19352 and https://nvd.nist.gov/vuln/detail/CVE-2018-19351
> Bump version for `notebook` requirement

- starfish/experiment/experiment.py
- starfish/experiment/test_experiment.py
Order all fovs by name by default. (Other idea from starfish sync was to order by physical coordinates)
cc: @berl
> [easy] order fovs by name by default

- starfish/experiment/builder/__init__.py
#730 reordered it such that the postprocess_func is called at the end.  However, that means any side effects of the postprocess_func is not reflected in the written experiment document.
This PR moves the write of the experiment document to *after* the postprocess_func.
Test plan: visual inspection.
> [easy] Fix writing of experiment document.

- starfish/imagestack/imagestack.py
These tick marks correspond to the round/ch/zlayer.  Right now, it's just sequentially numbered, but once we support nonsequential indices, we need to provide the tick marks.
Test plan: `make -j lint mypy && pytest -v -n8 starfish/test/image/`
> Provide tick marks for the physical coordinates xarray.

- starfish/imagestack/imagestack.py
- starfish/imagestack/parser/__init__.py
- starfish/imagestack/parser/_key.py
- starfish/imagestack/parser/_tiledata.py
- starfish/imagestack/parser/tileset/__init__.py
- starfish/imagestack/parser/tileset/_parser.py
At the construction of the `ImageStack`, we use the `TileData` class to parse and store the extras associated with tiles.
`ImageStack.tile_metadata` gets its data from TileSet instance we store.
Test plan: `pytest -vv -n4  starfish/test/image/test_imagestack_metadata.py   starfish/test/full_pipelines/cli/test_merfish_cli.py  starfish/test/full_pipelines/api/test_merfish.py`
Note:
- This is the first part of #776
> [NO-TILESET 1/3] Decouple tile_metadata from the TileSet.

- examples/get_cli_test_data.py
- starfish/image/_filter/__init__.py
- starfish/image/_registration/__init__.py
- starfish/imagestack/imagestack.py
Rather than writing the data back to the source ImageStack and writing that out to disk, make a new TileSet, and set it up appropriately.
This makes explicit what is needed for writing the ImageStack, and what is used to write the ImageStack.
Depends on #782 
Test plan: `make -j fast run_notebooks`
> [NO-TILESET 2/3] Implement ImageStack write without depending on the source ImageStack

- starfish/imagestack/imagestack.py
I updated the docstring for the ImageStack class to reflect some of the recently added/changed methods. Specifically:
- `sel()`
- `write()` -> `export()`
- `show_stack_napari()`
I'm not sure how this interacts with the readthedocs documentation, but I use the class docstrings frequently. Please let me know if anything is incomplete or incorrect.
> Updated ImageStack docstrings

- starfish/imagestack/imagestack.py
- starfish/test/image/test_imagestack.py
Allows passing `ImageFormat` to the export method. This does *not* reproduce the error seen by @ambrosejcarr that NUMPY files were being written with ".tiff" names. Both tests here currently produce files with the expected file-ending.
prerequisite for: tiff writing (gh-603)
> [EASY] Pass ImageFormat to ImageStack.export

- starfish/imagestack/_mp_dataarray.py
multiprocessing.Array actually [initializes the data array to 0](https://github.com/python/cpython/blob/c9566b8c454120e3d0ddb5ab970f262a6cd80077/Lib/multiprocessing/sharedctypes.py#L59), though it's not documented.  This reduces the initialization costs of ImageStack significantly.
This partially remediates https://github.com/spacetx/starfish/issues/833, though it's a very tiny part.
> Remove unnecessary initialization in MPDataArray

- starfish/spots/_detector/__init__.py
- starfish/spots/_detector/local_max_peak_finder.py
It was not imported, and so it wasn't registered with the CLI.
Fix some of the click.option calls as action is not a valid parameter for click.
Test plan: `pytest -v -n8 starfish/test/image/` and
```
[tt (.venv)]:~/microscopy/starfish:tonytung-local-max-peak-finder> starfish detect_spots --help
_              __ _     _
| |            / _(_)   | |
___| |_ __ _ _ __| |_ _ ___| |__
/ __| __/ _` | '__|  _| / __| '_  `
\__ \ || (_| | |  | | | \__ \ | | |
|___/\__\__,_|_|  |_| |_|___/_| |_|
Usage: starfish detect_spots [OPTIONS] COMMAND [ARGS]...
Options:
-i, --input PATH                [required]
-o, --output TEXT               [required]
--blobs-stack TEXT              ImageStack that contains the blobs. Will be
max-projected across imaging round and
channel to produce the blobs_image …
```
> Add local max peak finder to the CLI.

- docs/source/contributing/contributing.md
- starfish/image/_filter/__init__.py
- starfish/image/_registration/__init__.py
- starfish/image/_segmentation/__init__.py
- starfish/pipeline/__init__.py
- starfish/pipeline/pipelinecomponent.py
- starfish/spots/_decoder/__init__.py
- starfish/spots/_detector/__init__.py
- starfish/spots/_target_assignment/__init__.py
Created a method that automatically imports all the modules in a directory (with exclusions, so we don't import ourselves).
Test plan: Test plan: `pytest -v -n8 starfish/test/image/`
Depends on #830
> Remove the requirement to import all the algorithm implementations.

- starfish/imagestack/imagestack.py
- starfish/test/image/test_imagestack_coordinates.py
Add a coordinates accessor that gets the entire coordinates array.
Depends on #824
> [easy] Rename coordinates -> tile_coordinates

- examples/format_osmfish.py
- examples/get_imc_data.py
- examples/get_iss_breast_data.py
- examples/get_iss_data.py
- examples/get_merfish_u20s_data.py
- starfish/experiment/builder/__init__.py
- starfish/experiment/builder/cli.py
- starfish/experiment/builder/providers.py
While slicedimage supports images where the individual tiles are different formats, there isn't an API that actually allows _writing_ images of that nature.  We can just provide the tile format at the top level `write_experiment_json` call and write the data accordingly.
Test plan: `python examples/get_iss_breast_data.py /Users/ttung/Downloads/starfish_data/mignardi_breast_1/raw/ ../starfish-formatted-data/breast/ 1` and visual inspection.
> Rework how we parameterize the image format for starfish.experiment.builder

- .flake8
- Makefile
- examples/format_osmfish.py
- starfish/starfish.py
1. Put back E605 as a valid warning.
2. Use r-style strings to not quote backslashes.
Test plan: `make -j lint`, waiting on travis now...
> Fix E605 warnings.

- .travis.yml
- Makefile
- docs/Makefile
- docs/source/API/core_objects/expression_matrix.rst
- docs/source/API/core_objects/index.rst
- docs/source/API/image/filtering/filtering.rst
- docs/source/API/image/index.rst
- docs/source/API/image/registration/registration.rst
- docs/source/API/image/segmentation/segmentation.rst
- docs/source/API/plot/plot.rst
- docs/source/API/spots/decoding/decoding.rst
- docs/source/API/spots/detection/detection.rst
- docs/source/API/spots/index.rst
- docs/source/API/spots/target_assignment/target_assignment.rst
- docs/source/API/types/types.rst
- docs/source/_static/README
- docs/source/debugging.rst
- docs/source/installation/installation.rst
- docs/source/license/license.rst
- docs/source/sptx-format/data_conversion/data_conversion.rst
- docs/source/sptx-format/index.rst
- docs/source/sptx-format/specification.rst
- docs/source/sptx-format/validation.rst
- docs/source/usage/index.rst
- docs/source/usage/iss/iss_cli.sh
- starfish/experiment/experiment.py
- starfish/imagestack/imagestack.py
Fixes applied:
* Corrected formatting of anchors
* Added a few missing pages to index
* Un-ref'd a few undocumented classes
* Allow overriding Makefile variables
Test plan:
* If travis is green, then in the future doc warnings should be avoided.
* Docs should also look reasonable.
> Treat sphinx warnings as errors in travis

- starfish/imagestack/imagestack.py
* Adds ability to save ImageStack to a multi-page Tiff that can be directly opened and viewed by FIJI. 
Testing Strategy: 
* Load data from any notebook
* Call function implemented by this PR
* Try to open the result with FIJI.
> Add ability to save ImageStack as a Multi-page TIFF that FIJI can read. 

- starfish/experiment/experiment.py
- starfish/imagestack/imagestack.py
- starfish/imagestack/parser/tileset/__init__.py
- starfish/imagestack/parser/tileset/_parser.py
1. `_get_dimension_size` gets moved to the new module as it is no longer needed in ImageStack.
2. Rename `tile_metadata` to `tile_data` as it represents both the image data and the metadata now.
Depends on #791
This is part of RFC #776
Test plan: make -j run_notebooks
> Extract the TileSet → ImageStack code into a separate module.

- starfish/imagestack/imagestack.py
Rename the variables to `data_shape` and `data_dimensions` to match what is being done for the coordinates array.
> [easy] rename shape/dimensions for the data array

- starfish/imagestack/imagestack.py
- starfish/imagestack/indexing_utils.py
- starfish/test/image/test_imagestack_index.py
Right now, we use the default indexing provided by xarray, which is by pixel index.  To support r/c/z where the labels are not contiguous, we need to manually assign the labels.
One side effect is that label indexing is inclusive of the start _and_ end bounds.  That is the reason the test is updated.
Test plan: `make -j lint mypy && pytest -v -n8 starfish/test/image/`
Depends on #816
> Use labeled coordinates on r/c/z.

- starfish/imagestack/imagestack.py
If the max coordinate is 1, then the image must be at least 2px along that axis to accommodate that point.
Saw the test spuriously fail https://travis-ci.org/spacetx/starfish/builds/460911858
> [easy] fix off-by-one error for synthetic imagestack creation

- starfish/test/image/imagestack_test_utils.py
- starfish/test/image/test_imagestack_coordinates.py
These are two common idioms across ImageStack tests (or soon-to-be-coming ImageStack tests):
1. verifying a tile (or set of tiles)'s data.
2. verifying a tile's coordinates are common operations across imagestack tests.
Extract these two idioms so we don't keep repeating ourselves.
Test plan: `pytest -v -n8 starfish/test/image/ && make -j lint mypy`
Depends on #827
> Refactor common ImageStack test idioms into utility functions

- starfish/spots/_detector/local_max_peak_finder.py
There is still a z dimension, even though it's size=1.
Test plan: notebooks/py/osmFISH.py seems to run.
> local max peak finder should work in 3d images

- starfish/imagestack/imagestack.py
The current docblock yields this warning (which is treated as an error):
`/home/travis/build/spacetx/starfish/starfish/imagestack/imagestack.py:docstring of starfish.imagestack.imagestack.ImageStack.set_slice:38:Unexpected indentation.`
Blame: #818
> [easy] Fix sphinx error due to ws

- .travis.yml
- setup.py
Adds specific installation instructions because this is the only way for us to effectively "freeze" the installation of `napari` while allowing it to be an optional dependency. In addition, `napari`, through it's `vispy` dependency, requires an old version of `matplotlib`. 
Use `pip install -e .[napari]` to install (note the lack of space after the period). 
cc @kevinyamauchi
> Add optional install for Napari

- examples/format_baristaseq.py
For BaristaSeq, We previously wrote this TileFetcher, uploaded data to `s3`, and added BaristaSeq to `starfish.data`, however the TileFetcher code was not uploaded. 
This PR adds the TileFetcher code.
> Add BaristaSeq tilefetcher

- docs/source/roadmap.md
This PR revises the roadmap in order to prioritize work needed before the spring SpaceTx hackathon.
Specifically...
> To build these feature, we have two major phases of development in the first half of 2019, each culminating in minor releases of _starfish_. The first release (0.1.0) will support the needs of SpaceTx members to be able to create _starfish_ pipelines, while the second (0.2.0) will permit running these pipelines at scale.
>
> - 0.1.0 (April 2019): SpaceTx users are able to define _starfish_ pipelines and run them locally
> - 0.2.0 (June 2019): Insights can be gained from SpaceTx pipelines run at scale
In order to split these out, I ended up doing some reorganization of the roadmap. I also reworded some of the "candidate features for future releases" section.
Specific …
> two-phase roadmap

- starfish/codebook/codebook.py
- starfish/test/codebook/test_from_code_array.py
Rather than loop over targets setting them on the
xarray DataArray, create a single numpy array and
initialize the DataArray with the data.
> Speed up codebook generation (fix #912)

- starfish/imagestack/imagestack.py
- starfish/imagestack/parser/__init__.py
- starfish/imagestack/parser/_tiledata.py
- starfish/imagestack/parser/tileset/_parser.py
There is an inefficiency in the code that has us decoding the image _twice_, once to find the common dtype of the data and once to constitute the 5D tensor.
#802 exacerbates the inefficiency even more, by calling numpy_array multiple times, each time triggering a decode.
This PR changes the code so that we just decode the image once and storing it in a proxy object that looks a lot like a slicedimage Tile object.  Unlike a slicedimage Tile object, however, it retains the image for the lifetime of the object.  We tightly constrain the lifetime of these objects in the ImageStack constructor to avoid bloating memory requirements.
This PR also introduces an `_Expectations` class, which tracks the tile shapes and dtypes of the tiles seen during a decode of a TileSet.  If the shapes are not all …
> Dynamically evaluate the tile shape and dtype as we decode.

- starfish/experiment/builder/__init__.py
- starfish/experiment/builder/orderediterator.py
- starfish/imagestack/imagestack.py
- starfish/test/experiment/builder/test_orderediterator.py
The IDs for rounds/chs/zlayers for imagestack / experiment builders are now taken from a sequence rather than ranging from 0..(n-1).  At all existing call sites, we simply provide a range, so it's a functional noop.  However, this allows us to build tests for labeled indices.
Test plan: `make -j test lint mypy`
Depends on #803
> Add support for labeled indices in imagestack / experiment builders

- starfish/image/_filter/zero_by_channel_magnitude.py
- starfish/image/_registration/fourier_shift.py
- starfish/imagestack/imagestack.py
- starfish/imagestack/parser/_key.py
- starfish/test/image/test_imagestack.py
- starfish/test/image/test_imagestack_labeled_indices.py
- starfish/test/test_utils.py
Currently, we assume all the index values are 0..n-1, if the index has dimension size=n.  This assumption will no longer hold with round-at-a-time processing, where we crop before load.  In that case, we want to preserve the existing round numbers so that we can merge the results.
A new method is added to `ImageStack`, called `index_values`, which returns an iterable over the valid index values.
This PR is missing a test for selecting a subset of an ImageStack, and verifying that the data, the labels on the axes, and the coordinates of the tiles are correct.
Test plan: `make -j test lint mypy`.
Depends on #817, #818, #823, #877
> Decouple the index values from the # of possible index values.

- .travis.yml
- Makefile
- notebooks/subdir.mk
- starfish/test/full_pipelines/api/test_iss_doc_pipeline.py
- starfish/test/full_pipelines/cli/test_dartfish_cli.py
- starfish/test/full_pipelines/cli/test_iss.py
- starfish/test/test_synthetic_data.py
Introduce a slow test marker.  This breaks out check-notebooks and slow-test into a parallel travis run.  If travis has sufficient compute, this allows us to complete a test for a PR in ~9 minutes instead of 15 (see https://travis-ci.com/spacetx/starfish/builds/96790705).
Small change I snuck in: all makefile targets are hyphenated instead of underscored.
> Increase parallelization for travis runs.

- starfish/imagestack/imagestack.py
- starfish/imagestack/parser/crop.py
- starfish/test/image/test_imagestack_cropped_load.py
Create new classes (CroppedTileCollectionData, CroppedTileData) for representing a cropped view of a (TileCollectionData, TileData).  Because cropping happens at the time of ImageStack construction, the memory requirements are significantly lowered to O(number-of-cropped-tiles * size-of-one-cropped-tile + size-of-one-original-tile).
This is #902, except github mysteriously closed that PR. :(
Depends on #828 
Test plan: new imagestack construction tests that verify that the cropping occurs as expected.
Fixes #832
> Support crop-on-load for TileSet -> ImageStack construction

- REQUIREMENTS.txt
- REQUIREMENTS.txt.in
- notebooks/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.ipynb
- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.ipynb
- notebooks/py/DARTFISH_Pipeline_-_Human_Occipital_Cortex_-_1_FOV.py
- notebooks/py/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- starfish/display/__init__.py
- starfish/display/stack.py
- starfish/imagestack/imagestack.py
- starfish/test/display/stack.py
Features:
- Displays ImageStacks using Napari
- If provided with an IntensityTable generated from the provided ImageStack, will display spots
- will max project over selected indices
- will hide spots (per round and channel) to display spots above a threshold in individual tiles. 
- will hide any pre-existing entries in the IntensityTable that are `np.NaN` (enables pre-masking). This also solves the smFISH use case where there is only one entry per intensitytable feature and the rest are `np.NaN`. 
- all combinations of the above are functional (e.g. masking over max projections)
@kevinyamauchi it should have everything you need for showing spots. Let me know if anything is confusing. This should get you started: 
cc @berl in case there's interest. 
install: 
```
$ pip install -e …
```
> starfish.display.stack

- starfish/imagestack/imagestack.py
- starfish/multiprocessing/pool.py
- starfish/spots/_detector/combine_adjacent_features.py
- starfish/spots/_detector/detect.py
- starfish/spots/_detector/pixel_spot_detector.py
- starfish/test/pipeline/test_filter.py
- starfish/test/spots/detector/test_spot_detection.py
This PR:
-Creates a multiprocessing.pool wrapper class called Spool (starfish+pool, but definitely open for suggestions) that, when given n_processes=1 overrides the map function to use a non-mulitprocessed map. 
-Adds n_processes as a parameter in detect.py and pixel_spot_detector.py
-refactors imagestack.transform to use the spool class in a n_processes=1 scenario
-Modified a couple filter/detect tests to verify everything still works with spool. 
With these changes we should be able to attach the debugger to any Filter/detect step when n_processes=1.
fixes: #941
> Multiprocessing module for debugging

- starfish/__init__.py
- starfish/starfish.py
Test plan:
```
% starfish version
0.0.31
% python
Python 3.6.6 (default, Jun 28 2018, 05:43:53)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import starfish
>>> starfish.__version__
'0.0.31'
```
> Add version to starfish module.

- starfish/imagestack/imagestack.py
I noticed that the `show_stack` methods in `ImageStack` have been moved to `display`, so I removed their docstrings.
> Remove show_stack methods from ImageStack docstring

- starfish/experiment/experiment.py
- starfish/experiment/test_experiment.py
Test plan:
```
from starfish import data
from starfish.imagestack.parser.crop import CropParameters
exp = data.ISS()
c = CropParameters(x_slice=slice(100, 300), y_slice=slice(400, 700))
exp['fov_001'].get_image('primary', c)
```
also added unit test.
Fixes #950
> Add support for cropping to the experiment API.

- starfish/image/_filter/__init__.py
- starfish/image/_registration/__init__.py
- starfish/image/_segmentation/__init__.py
- starfish/pipeline/pipelinecomponent.py
- starfish/spots/_decoder/__init__.py
- starfish/spots/_detector/__init__.py
- starfish/spots/_target_assignment/__init__.py
This can be handled in the metaclass to avoid a bunch of boilerplate.
Test plan: `pytest -v -n4 starfish/test/full_pipelines/cli`
> Move _cli_register boilerplate into metaclass.

- starfish/imagestack/imagestack.py
The param section of the ImageStack docstring still had `numpy_array`, so I updated it.
> Fix ImageStack param docstring

- starfish/spots/_detector/blob.py
- starfish/spots/_detector/detect.py
- starfish/spots/_detector/trackpy_local_max_peak_finder.py
- starfish/test/spots/detector/test_spot_detection.py
- starfish/test/test_utils.py
- starfish/types/_spot_attributes.py
This PR fixes errors in each SpotFinder that occur when no spots are detected, and catches warnings that are otherwise repeatedly emitted for every application of a spot-finding call (many times per `ImageStack`). 
It also adds tests that verify that each way of calling each spot detectors works in the case where the `ImageStack` contains no detectable spots, and fixes the two failing tests from the previous PR that resulted from related problems (where _some_ but not _all_ slices of the ImageStack contained no spots).
> [3/3] fix no-spots-detected errors

- starfish/spots/_detector/blob.py
- starfish/spots/_detector/detect.py
- starfish/spots/_detector/trackpy_local_max_peak_finder.py
- starfish/test/spots/detector/test_spot_detection.py
- starfish/test/test_utils.py
- starfish/types/_spot_attributes.py
This PR refactors testing data that was found in `pixel_spot_detector.py`, moving it to `test_utils.py`. In addition, it makes the produced testing data more robust by returning, in addition to an `ImageStack`, a `Codebook` that could have generated the data (enables use with `PixelSpotDecoder`) and the `max_intensity` value for the `ImageStack` (removes magic numbers from the tests). 
The data that was originally found in `pixel_spot_detector.py` was specific to in-situ sequencing datasets, which left some testing holes in our input data types. This PR replicates the above testing construct of `Codebook, ImageStack, max_intensity` for sparse codebooks (MERFISH) and codebooks with informative blanks (DARTFISH). This covers the data types we currently have access to, and passes these data …
> [2/3] Refactor spot finding tests, add new examples

- sptx_format/cli.py
- starfish/test/full_pipelines/cli/test_build.py
- starfish/test/full_pipelines/cli/test_iss.py
- starfish/util/click.py
- starfish/util/exec.py
- call xr.open_dataset and print repr
- try to detect which type of output it is
- return non-zero if unknown or invalid
Also:
- add an `experiment` subcommand
- rewrite `--experiment-json` to use subcommand
- print temp directory for test output for easier testing
Example output:
```
_              __ _     _
| |            / _(_)   | |
___| |_ __ _ _ __| |_ _ ___| |__
/ __| __/ _` | '__|  _| / __| '_  `
\__ \ || (_| | |  | | | \__ \ | | |
|___/\__\__,_|_|  |_| |_|___/_| |_|
============================================================
<xarray.Dataset>
Dimensions:                        (c: 4, features: 51, r: 4)
Coordinates:
z                              (features) int64 ...
y                              (features) int64 ...
x                              (features) int64 ...
radius …
```
> cli: add `validate xarray` command

- Dockerfile
Performing cleanup with conda environment setup
and preventing pip package caching reduces docker
image size from ~3.6 GB down to 2.76 GB
> Optimize dockerfile to reduce docker image size

- sptx_format/cli.py
ctx.exit(0) works by raising an exception, which is caught and reraised as a ctx.exit(1).
This moves the ctx.exit(0) into an else clause.
> Fix exit code of `starfish validate xarray`

- Makefile
We just ran `--force-reinstall --upgrade`.  We shouldn't need to again.
> [easy] Reduce the reinstalling of packages on travis runs

- readthedocs.yml
The sphinx_bootstrap_theme requirement is now in a second file.
RTD v1 only supports a single requirements file (which was
previously auto-detected). With v2 both `CI` and `STRICT` can
be referenced.
see:
- https://github.com/spacetx/starfish/pull/997
- https://readthedocs.org/projects/spacetx-starfish/builds/8570377/
- https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-v1
> RTD: use new requirements files

- REQUIREMENTS.txt
- setup.py
- starfish/display/stack.py
@kne42 says that we don't need to keep matplotlib pinned any more.  We just might want to kill the potentially scary warning from napari.
Depends on #997
Test plan:
```
In [1]: import starfish.data
In [2]: exp = starfish.data.ISS(use_test_data=True)
In [3]: img = exp['fov_001']['primary']
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 256.35it/s]
In [4]: import starfish.display.stack
In [5]: starfish.display.stack(img)
Out[5]: <napari_gui.elements._viewer.Viewer at 0x13634fda0>
```
> Unpin matplotlib and squelch scary warning from napari

- docs/source/installation/installation.rst
install-dev covers installation of strict dependencies, `pip install -e`, and the installation of CI tools.
> [easy] fix documentation about how to install for developers.

- starfish/spots/_detector/local_max_peak_finder.py
- starfish/test/spots/detector/pixel_spot_detector/combine_adjacent_features/test_create_spot_attributes.py
scikit-image in 0.14.2 no longer removes singleton dimensions.  This broke starfish when used with that version of scikit-image.  See http://scikit-image.org/docs/0.14.x/release_notes_and_installation.html#api-changes and https://github.com/scikit-image/scikit-image/pull/3284
Test plan: `pip install -r REQUIREMENTS-STRICT.txt && python notebooks/py/osmFISH.py`
> Fix regionprops call to skimage

- REQUIREMENTS-STRICT.txt
Other dependencies in the graph (like tornado) pull in a newer
version of PyYAML which then gets deleted leading to:
```
FoundError: [Errno 2] No such file or directory:
'/home/docs/checkouts/readthedocs.org/user_builds/
spacetx-starfish/envs/latest/lib/python3.6/site-packages/
PyYAML-4.2b4-py3.6-linux-x86_64.egg'
```
in https://readthedocs.org/projects/spacetx-starfish/builds/8578793/
> Bump PyYAML to 4.2b4

- docs/source/sptx-format/index.rst
- docs/source/sptx-format/input_formats/SpaceTxFormat/index.rst
- docs/source/sptx-format/input_formats/Validation/index.rst
- docs/source/sptx-format/input_formats/index.rst
- docs/source/sptx-format/output_formats/ExpressionMatrix/index.rst
- docs/source/sptx-format/output_formats/IntensityTable/index.rst
- docs/source/sptx-format/output_formats/SegmentationMask/index.rst
- docs/source/sptx-format/output_formats/index.rst
Bug Fix: 
- Corrected API references for `IntensityTable` and `Codebook` 
New Docs: 
- Add Specification for `IntensityTable`
- Add Specification for `ExpressionMatrix`
- Add Placeholder Specification for `SegmentationMask` while we research what object we want to use for this.
> Created specifications for output formats

- docs/source/api/core_objects/expression_matrix.rst
Don't _think_ this was leading to the wider RTD errors, but locally it failed `make docs-html` for me.
> [EASY] docs: fix automodule for expression_matrix

- starfish/image/_filter/bandpass.py
- starfish/image/_filter/clip.py
- starfish/image/_filter/gaussian_high_pass.py
- starfish/image/_filter/gaussian_low_pass.py
- starfish/image/_filter/laplace.py
- starfish/image/_filter/mean_high_pass.py
- starfish/image/_filter/richardson_lucy_deconvolution.py
- starfish/image/_filter/scale_by_percentile.py
- starfish/image/_filter/util.py
- starfish/image/_filter/white_tophat.py
- starfish/imagestack/imagestack.py
- starfish/spots/_detector/detect.py
- starfish/spots/_detector/local_max_peak_finder.py
- starfish/spots/_detector/trackpy_local_max_peak_finder.py
@kevinyamauchi pointed out in #987 and #983 that our apply method hampers our ability to write expressive `PipelineComponent`s because it returns numpy arrays instead of xarray DataArray objects. 
This PR:
1. Modifies `ImageStack.transform` so that methods used by `apply` can take advantage of `xarray` named axes. Because we are rebuilding an array from the `sharedmemory` object, this does not give us access to data stored in the coordinates. Thus, the returned arrays only guarantee that the Axes are in the correct order. If `is_volume` is True, xarrays generated by `ImageStack.transform` have dims = `(z, y, x)` and no coordinates. If `is_volume` is False, xarrays generated by `ImageStack.transform` have dims = `(y, x)` and no coordinates. These are set based on the information in …
> Imagestack.transform executes applied function on xarray objects instead of numpy arrays

- starfish/config/__init__.py
- starfish/test/full_pipelines/cli/get_cli_test_data.py
- starfish/test/full_pipelines/cli/test_iss.py
On adding a validation command, `test_iss.py` begins to fail due to a confusion between the older "hybridization.json" and the newer "primary_images.json". This PR:
(`test_iss.py` should have failed _previously_ which needs tracking down.)
> iss: add validation command

- starfish/image/_filter/util.py
- starfish/spots/_detector/local_max_peak_finder.py
- starfish/spots/_detector/trackpy_local_max_peak_finder.py
There are some places in the codebase where we need a numpy array instead of an xarray.  Switch all instances where we do this to `np.asarray(...)`.  Also, fixed type hints where appropriate.
This should fix the master-breaking bug in #1035, but does not resolve the issue of (xarray) coordinates not being transferred to the constituent xarrays.
> Fix how we cast from xarray to numpy

- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.ipynb
- notebooks/py/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- starfish/image/_filter/bandpass.py
- starfish/image/_filter/gaussian_high_pass.py
- starfish/image/_filter/gaussian_low_pass.py
- starfish/image/_filter/laplace.py
- starfish/image/_filter/mean_high_pass.py
- starfish/image/_filter/richardson_lucy_deconvolution.py
- starfish/image/_filter/scale_by_percentile.py
- starfish/image/_filter/util.py
- starfish/image/_filter/white_tophat.py
- starfish/image/_filter/zero_by_channel_magnitude.py
- starfish/image/_registration/fourier_shift.py
- starfish/imagestack/imagestack.py
- starfish/intensity_table/intensity_table.py
- starfish/spots/_detector/detect.py
- starfish/test/full_pipelines/api/test_merfish.py
- starfish/test/image/test_apply.py
- starfish/test/pipeline/test_filter.py
- starfish/types/__init__.py
- starfish/types/_constants.py
- starfish/util/dtype.py
Clipping and scaling was not happening properly in our filters, leading to some bugs. Specifically, `preserve_float_range` with `rescale=True` scales by the max value of the provided image. This was being called on _each chunk independently_, when some filters need to call it on the _whole imagestack_. This PR adds that flexibility. 
- Move `preserve_float_range` calls into `ImageStack.apply` and enable 3 modes of clipping (see below).
- Move `preserve_float_range` from `filter` to `starfish.util.dtype`.
- Each filter that can create values outside [0, 1] now receives a `clip_method` parameter. 
- Add comments to `apply`, `transform` and related methods to clarify process flow. 
- Add tests for clipping types
- Improve correlation for MERFISH notebook by adjusting deconvolution clipping
- …
> Move preserve_float_range

- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.ipynb
- notebooks/py/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- starfish/image/_filter/bandpass.py
- starfish/image/_filter/gaussian_high_pass.py
- starfish/image/_filter/gaussian_low_pass.py
- starfish/image/_filter/laplace.py
- starfish/image/_filter/linear_unmixing.py
- starfish/image/_filter/mean_high_pass.py
- starfish/image/_filter/richardson_lucy_deconvolution.py
- starfish/image/_filter/scale_by_percentile.py
- starfish/image/_filter/util.py
- starfish/image/_filter/white_tophat.py
- starfish/image/_filter/zero_by_channel_magnitude.py
- starfish/image/_registration/fourier_shift.py
- starfish/imagestack/imagestack.py
- starfish/intensity_table/intensity_table.py
- starfish/spots/_detector/detect.py
- starfish/test/full_pipelines/api/test_merfish.py
- starfish/test/image/filter/test_linear_unmixing.py
- starfish/test/image/test_apply.py
- starfish/test/pipeline/test_filter.py
- starfish/types/__init__.py
- starfish/types/_constants.py
- starfish/util/dtype.py
Based on #990 
- Updates the branch to use the scaling behavior in #1041 
- Removes the for-loop behavior in inner function of the `_unmix` method that is in #990 
Opening a new PR so that @kevinyamauchi can take a look at the tests and make sure everything checks out without me force-pushing his branch.
> Linear Unmixing

- starfish/image/_filter/element_wise_mult.py
This PR introduces a pipeline component for field flatness correction and image normalization via a user supplied correction image. 
Per our discussion in #945, I did the following:
> For illumination correction, the user would supply the full matrix. This method uses the Filter PipelineComponent. The user supplied matrix is a 5-d tensor with any singleton dimension being broadcast. For example, to correct illumination uniformly across (x, y) user would pass (1, 1, 1, x, y). To uniformly scale channels, user would pass (1, c, 1, 1, 1) where c- is a vector of length equal to the number of channels
```python
import numpy as np
from starfish.imagestack.imagestack import ImageStack
import starfish
im = np.ones((1, 3, 5, 2, 2))
stack = ImageStack.from_numpy_array(im)
corr_mat = np.ones((1, 1, …
```
> [RFC] Add ElementWiseMult

- starfish/imagestack/imagestack.py
Since the labels are sourced from the xarray coordinates now, they come back as numpy int64 values.  Most of the time, we just want plain old python integers (e.g., json serialization doesn't work with numpy ints), so cast it.
Also ninja'ed in a small doc fix.
Depends on #1032
> [easy] return python integer labels

- starfish/imagestack/imagestack.py
> [easy] remove unused field

- .travis.yml
This should have been done in #1077.
> [easy] Remove assay_comparison notebook from travis runs.

- REQUIREMENTS-STRICT.txt
- REQUIREMENTS.txt
- data_formatting_examples/format_baristaseq.py
- data_formatting_examples/format_imc_data.py
- data_formatting_examples/format_iss_breast_data.py
- data_formatting_examples/format_iss_data.py
- data_formatting_examples/format_merfish_U2OS_data.py
- data_formatting_examples/format_osmfish.py
- data_formatting_examples/format_seqFISH.py
- data_formatting_examples/format_starmap.py
- starfish/experiment/builder/__init__.py
- starfish/experiment/builder/defaultproviders.py
- starfish/experiment/builder/providers.py
- starfish/imagestack/imagestack.py
- starfish/imagestack/parser/_tiledata.py
- starfish/imagestack/parser/crop.py
- starfish/imagestack/parser/numpy/__init__.py
- starfish/imagestack/parser/tileset/_parser.py
- starfish/spacetx_format/schema/field_of_view/field_of_view.json
- starfish/spacetx_format/schema/field_of_view/tiles/tiles.json
- starfish/test/experiment/test_experiment.py
- starfish/test/image/test_imagestack_coordinates.py
- starfish/test/image/test_imagestack_cropped_load.py
- starfish/test/image/test_imagestack_labeled_indices.py
- starfish/test/image/test_imagestack_metadata.py
- starfish/test/image/test_slicedimage_dtype.py
1. Where tile shape is being used, we use a dict between axis and the size of the tile along that axis.
2. Where there is a contract for tile data, we indicate that the data should be row-major.
Test plan: `make -j fast`  tests on travis will not complete until https://github.com/spacetx/slicedimage/pull/81 has landed and a new version is released.
Resolves #528
> Change tile shape to a dict by default

- starfish/spacetx_format/README.md
This PR clarifies how SpaceTx codebook zeros and missing values should be interpreted. 
Future PRs will implement the logic suggested for implementing libraries, as noted by @berl (see #1057).
> Explain how SpaceTx codebook zero/missing values are interpreted

- starfish/_display.py
This pull request adds the ability to display multiple `ImageStack` objects in the same napari viewer, as discussed in #1086. Towards this, I added the option to pass in a napari `Viewer` object to `display()`. If the user passes in a `Viewer` object, the stack and/or spots are added as new layers in the existing `Viewer`. If `None` (default) is passed, the stack and/or spots are displayed in a new `Viewer`.  Closes #1086.
I am not sure what to do for the `viewer` type hint (line 111). It seems to me like we are trying to avoid importing napari at the top of `_display.py` to ease the dependency, so I am not sure how to give the `Viewer` class as a type hint. Thoughts?
```python
from starfish import data, FieldOfView, display
experiment = data.ISS(use_test_data=False)
fov = …
```
> Enable appending to existing napari viewer in display()

- docs/source/sptx-format/output_formats/DecodedSpots/index.rst
- docs/source/sptx-format/output_formats/index.rst
- starfish/intensity_table/intensity_table.py
- starfish/test/test_decoded_spots.py
- starfish/types/__init__.py
- starfish/types/_decoded_spots.py
Adds a `DecodedSpotTable` and some basic serialization tooling to address #1076. Users who want the underlying dataframe can get it with `DecodedSpotTable.data`. 
See documentation included in PR for more details. 
closes #1076
> Add Decoded Spot Table

- starfish/image/_filter/__init__.py
- starfish/image/_registration/__init__.py
- starfish/image/_segmentation/__init__.py
- starfish/pipeline/pipelinecomponent.py
- starfish/spots/_decoder/__init__.py
- starfish/spots/_detector/__init__.py
- starfish/spots/_pixel_decoder/__init__.py
- starfish/spots/_target_assignment/__init__.py
- starfish/test/image/filter/test_api_contract.py
- starfish/test/pipelinecomponent/test_pipelinecomponent_by_name.py
For running pipeline recipes, we will need to refer to pipeline components by name.  To facilitate that, we will adds a map between the pipeline component name and its implementing class.
We mandate each PipelineComponent provide a name, and we source that from the same variable that defines the CLI command name.
Test plan: see new test.
> Add a mechanism to retrieve PipelineComponent by name

- Makefile
- docs/source/index.rst
So when we delete/rename/reorganize pipeline components the docs build doesn't freakout.
> [easy] - adding make clean to docs build

- Makefile
versioneer depends on the git tag being somewhere in the lineage of master.  This updated procedure tries to get the tag into the lineage of master.
> Tweak the release procedures so we push to master.

- Dockerfile
- docker/pip-config
This replaces #1080, and depends on #1084 
Test plan: `make docker`
> Use a pip config file.

- .travis.yml
This doesn't change often enough to justify running on every branch.
> [easy] Only run the install napari test on master

- codecov.yml
Exclude the test files from the calculations of what code is covered.
Also exclude the file that's autogenerated by versioneer.
This is based on #1111
> Fix code coverage detection

- starfish/multiprocessing/test/test_multiprocessing.py
This silences a harmless warning from pytest.  pytest scrapes all files for methods and classes that start with test to try to run them as tests.  This is not an actual test; instead, it's a class used in a test.
Test plan: `pytest starfish/multiprocessing/test/test_multiprocessing.py`
This is stacked on top of #1111
> [easy] rename TestWrappedArray to WrappedArray

- starfish/util/click/__init__.py
I'm going to build other click-related code, and want to keep them together.
Remove the hack to suppress warnings because we don't check for F401 on `__init__.py` files.
Test plan: `make -j lint mypy`
> [easy] move starfish.util.click into its own package.

- REQUIREMENTS-STRICT.txt
- REQUIREMENTS.txt
- starfish/experiment/builder/__init__.py
- starfish/imagestack/imagestack.py
Pick up https://github.com/spacetx/slicedimage/pull/85, https://github.com/spacetx/slicedimage/pull/86, and https://github.com/spacetx/slicedimage/pull/87.
Code changes to support the API changes.
This will not pass travis until the above PRs are approved, landed, and a new slicedimage package is released.
Partially addresses #1116
> Support for hierarchical directory structures for experiments.

- Makefile
- starfish/REQUIREMENTS-STRICT.txt
They should if the tooling in Makefile is used to generate REQUIREMENTS-STRICT.txt, but if someone (ahem, me) hand-edits the file, all bets are off.
Fix the inconsistency.
Test plan: `make diff-requirements` without copying the changes over fails
> Ensure that the top level and packaged REQUIREMENTS-STRICT.txt stay consistent

- starfish/experiment/builder/__init__.py
- starfish/experiment/builder/inplace.py
Since tiffs record the timestamp that they were written, we cannot calculate the checksums using the normal slicedimage write path.  We add a reference to track from the slicedimage Tile -> FetchedTile, and use that to calculate the checksum.
Test plan: proof of concept script.
Depends on #1126 
This will not pass travis until the PRs referenced in #1126 are landed.
> Additional support code for building experiments in-place.

- starfish/util/click/indirectparams.py
- starfish/util/indirectfile/__init__.py
- starfish/util/indirectfile/_base.py
- starfish/util/indirectfile/_codebook.py
- starfish/util/indirectfile/_imagestack.py
Add the ability to reference an imagestack or a codebook through a set of conversion recipes.  Each conversion recipe can read the input given on the CLI and make an attempt to convert it to the desired type.
For instance, a primary image can be referred to by the json describing the slicedimage set, _or_ @experiment.json[my_fov_name][primary].
> Indirect File click types

- .travis.yml
- notebooks/STARmap.ipynb
- notebooks/py/STARmap.py
- starfish/compat.py
- starfish/data/__init__.py
- starfish/spots/_detector/local_search_blob_detector.py
- starfish/test/spots/detector/test_local_search_blob_detector.py
This PR adds a Spot Detector that enables a local search across (round, channel) pairs. It is able to overcome minor registration errors in data for which the average registration error is smaller than the average distance to the closest spot. 
This PR seeds the local search in a single round, which is adequate for BaristaSeq and STARmap, but multi-round consensus seeding will be added in future PRs for SeqFISH. 
The private methods have been separated out with an eye towards the eventual spot finding refactor in #1005.
> Add LocalSearchBlobDetector to support BaristaSeq, SeqFISH, STARmap

- notebooks/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.ipynb
- notebooks/py/MERFISH_Pipeline_-_U2O2_Cell_Culture_-_1_FOV.py
- starfish/spots/_pixel_decoder/pixel_spot_decoder.py
- starfish/test/full_pipelines/cli/test_merfish_cli.py
Cropping can be done separately by the ImageStack.sel method.
Updates the MERFISH notebook to more clearly indicate
that no cropping is being done.
Closes #759
> Remove cropping from PixelSpotDetector

- docs/source/usage/iss/iss_pipeline.py
- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/py/ISS_Pipeline_-_Breast_-_1_FOV.py
- starfish/imagestack/test/dataset_fixtures.py
- starfish/spots/_detector/_base.py
- starfish/spots/_detector/blob.py
- starfish/spots/_detector/detect.py
- starfish/spots/_detector/local_max_peak_finder.py
- starfish/spots/_detector/test/test_spot_detection.py
- starfish/spots/_detector/test/test_synthetic_data.py
- starfish/spots/_detector/trackpy_local_max_peak_finder.py
- starfish/test/full_pipelines/cli/test_iss.py
- starfish/util/click/__init__.py
High level goal: detect spots should accept imagestacks and not numpy arrays.
1. blobs_image is, at the user's interaction level, an ImageStack.  Internally, `starfish.spots._detector.detect.detect_spots` will convert it to a numpy array.  This is to allow the code path where we don't have a reference image to continue taking advantage of ImageStack's apply/transform logic.
2. Because the way we generate the blobs_image (max projection) happens on different axes, it must be explicitly provided to `detect_spots`.
3. Other small and insignificant changes.
Test plan: `make -j test run_notebooks`
> Refactor blobs_image api.

- starfish/spots/_detector/local_search_blob_detector.py
1. Normalize the run(..) method with the contract specified in SpotFinderAlgorithmBase.
2. Flag an error if someone tries to specify a blobs_image with LocalSearchBlobDetector.
3. Temporarily provide a `image_to_spots` method which the SpotFinderAlgorithmBase requires.
> Unbreak master

- starfish/image/_filter/_base.py
- starfish/image/_registration/_apply_transform/_base.py
- starfish/image/_registration/_learn_transform/_base.py
- starfish/image/_registration/_learn_transform/translation.py
- starfish/image/_segmentation/_base.py
- starfish/spots/_decoder/_base.py
- starfish/spots/_detector/_base.py
- starfish/spots/_pixel_decoder/_base.py
#1124 introduced new click param types that directly return an ImageStack or a Codebook.  This refactors the existing cli params to use those types.
Depends on #1124
> Change all ImageStack and Codebook cli params to use the click params

- docs/source/usage/iss/iss_cli.sh
- starfish/test/full_pipelines/cli/test_iss.py
starfish/test/full_pipelines/cli/test_iss.py changed in #1083, but docs/source/usage/iss/iss_cli.sh was never updated.
This is built on top of #1138, and reflects the changes to starfish/test/full_pipelines/cli/test_iss.py in that PR.
> Update iss_cli.sh to reflect the contents of test_iss.py

- notebooks/STARmap.ipynb
- notebooks/py/STARmap.py
1. Fix for starfish.display.stack being renamed to starfish.display.
2. substack should be stack.
3. Remove unneeded imports.
4. Use public API in notebooks `starfish.spots.SpotFinder.LocalSearchBlobDetector` instead of `starfish.spots._detector.local_search_blob_detector.LocalSearchBlobDetector`
> fixes for broken starmap notebook.

- starfish/spots/_detector/_base.py
#1124 ensures that blobs_stack is already an ImageStack, but #1143 still does the conversion.  Merging both created this conflict.
Test plan: `pytest starfish/test/full_pipelines/cli/test_iss.py`
> Don't try to convert blobs_stack to an ImageStack twice.

- .travis.yml
This is needed as the memory requirements are too high.
> Skip the starmap notebook for now.

- starfish/imagestack/imagestack.py
- starfish/imagestack/parser/tileset/_parser.py
- starfish/imagestack/test/test_slicedimage_dtype.py
1. `set_slice` will catch mismatched tile sizes, so we don't need that.
2. aggregate all the dtypes, and verify that len(data type kinds) == 1 and len(data type sizes) == 1.
Test plan: `pytest -v -n4 starfish/imagestack`
> Simplify the code for verify tile dtype and shape.

- Makefile
- docs/source/_static/data_processing_examples/subdir.mk
New targets: run-examples, run__$(shell_script_name), and run__$(python_script_name)
Examples:
```
% make run-examples
% make run__iss_cli.sh
% make run__iss_pipeline.py
```
> Integrate data processing examples into existing makefile rules.

- starfish/imagestack/imagestack.py
- starfish/imagestack/test/test_imagestack_labeled_indices.py
`ImageStack.apply` uses slice indices based on the labels, but the xarray passed to the worker process does not have the labels.  This PR passes the dims and the coordinates of the original xarray to the worker process so it can reconstitute an identical xarray.
Test plan: Added a test that creates an `ImageStack` with labeled indices, and runs `apply` on it.  Without the code change, it fails.  With the code change, it works.
Fixes #1108, and the comment raised in https://github.com/spacetx/starfish/pull/1035#discussion_r260150143 :)
> Fix apply for ImageStacks with labeled indices.

- notebooks/ISS_Pipeline_-_Breast_-_1_FOV.ipynb
- notebooks/py/ISS_Pipeline_-_Breast_-_1_FOV.py
- starfish/image/_segmentation/_base.py
- starfish/image/_segmentation/watershed.py
- starfish/segmentation_mask.py
- starfish/spots/_target_assignment/_base.py
- starfish/spots/_target_assignment/label.py
- starfish/test/full_pipelines/api/test_iss_api.py
- starfish/test/full_pipelines/cli/test_iss.py
- starfish/test/test_segmentation_mask.py
> replace label images with segmentation masks

- starfish/experiment/builder/inplace.py
- starfish/experiment/builder/test/inplace_script.py
- starfish/experiment/builder/test/test_inplace.py
Turning on inplace_mode for building experiments monkey patches the slicedimage `Tile` class.  This is regarded as acceptable, as experiment builders are all isolated scripts.
However, in the test environment, the monkey patch persists, and can affect subsequent tests.  Therefore, if `starfish/experiment/builder/test/test_inplace.py` was run immediately before `starfish/imagestack/test/test_imagestack.py`, `test_imagestack_export` would spuriously fail.
This PR isolates the inplace test into its own subprocess, much like it would likely be run in real life.  It also adds a note to the documentation that in-place mode should be done in isolated scripts.
Test plan: `pytest starfish/experiment/builder/test/test_inplace.py starfish/imagestack/test/test_imagestack.py` passes now.
> Isolate inplace test

- starfish/spots/_detector/blob.py
- starfish/spots/_detector/local_max_peak_finder.py
- starfish/spots/_detector/trackpy_local_max_peak_finder.py
Adds ability to set `n_processes` for 3/4 spot finders which were missing the flag.
> Add back ability to set number of processes in spot finders

- docs/source/conf.py
Having this set to True means IntensityTable and Codebook try to render all the xarray attributes and methods, instead we should just link to them.
> Disable numpy-doc inherited class logic

- starfish/intensity_table/intensity_table.py
- starfish/intensity_table/overlap.py
- starfish/intensity_table/test/factories.py
- starfish/intensity_table/test/test_overlap.py
IntensityTable overlap code not going to be reused for ImageStack, so might as well keep it together.
Test plan: `pytest -v -n4 starfish/intensity_table/`
Depends on #1169
> Move IntensityTable overlap code and tests inside IntensityTable package

- starfish/imagestack/test/factories/__init__.py
- starfish/imagestack/test/factories/unique_tiles.py
- starfish/imagestack/test/imagestack_test_utils.py
- starfish/imagestack/test/test_cropped_load.py
- starfish/imagestack/test/test_labeled_indices.py
They're nearly the same, so let's just unify them.  The plan is to reuse this for labeled ImageStack -> IntensityTable tests.
Depends on #1177, will be needed for #1168.
> Unify the data provider for cropped loading tests and labeled indices tests.

- docs/source/contributing/index.rst
- docs/source/usage/index.rst
A few headings were getting dropped into the top-level of the TOC because they were marked up as H1 in the rst instead of H2.
This PR changes them to H2 so that the nav renders them as subnav properly.
> cleans up TOC by changing header levels

- starfish/imagestack/imagestack.py
- starfish/imagestack/test/test_apply.py
overwrite the Imagestacks numpy array with the result of preserve_float_range() instead of the xarray 
fixes #1184
> fixing Clip.SCALE_BY_IMAGE

- starfish/codebook/codebook.py
- starfish/codebook/test/factories.py
- starfish/codebook/test/test_from_code_array.py
- starfish/codebook/test/test_metric_decode.py
- starfish/experiment/experiment.py
- starfish/intensity_table/test/test_from_imagestack.py
- starfish/spots/_detector/test/test_synthetic_data.py
- starfish/spots/_pixel_decoder/pixel_spot_decoder.py
- starfish/test/factories.py
- starfish/util/indirectfile/_codebook.py
* update documentation
* `codebook.empty_codebook` --> `codebook.empty`
* `codebook._create_codebook` --> `codebook.from_numpy`
* `codebook.from_json` --> `codebook.open_json`
* `codebook.metric_decode` --> `codebook.decode_metric`  (enable tab completion of codebook.decode_*)
Other changes are refactorings that relate to the above changes.
> Update codebook documentation and harmonize method names

- docs/source/_static/data_processing_examples/3d_smFISH.py
- docs/source/_static/example_data_files/README.rst
- docs/source/help_and_reference/working_with_starfish_outputs/index.rst
- starfish/intensity_table/intensity_table.py
- starfish/intensity_table/test/test_empty_intensity_table.py
- starfish/intensity_table/test/test_intensity_table_serialization.py
- starfish/intensity_table/test/test_overlap.py
- starfish/intensity_table/test/test_to_mermaid.py
- starfish/spots/_decoder/_base.py
- starfish/spots/_detector/_base.py
- starfish/spots/_detector/detect.py
- starfish/spots/_pixel_decoder/_base.py
- starfish/spots/_target_assignment/_base.py
- starfish/test/full_pipelines/api/test_dartfish.py
- starfish/test/full_pipelines/api/test_iss_api.py
- starfish/test/full_pipelines/cli/_base_cli_test.py
* Update docs for IntensityTable
* `IntensityTable.empty_intensity_table` --> `IntensityTable.empty`
* `IntensityTable.save` --> `IntensityTable.to_netcdf`
* `IntensityTable.load` --> `IntensityTable.open_netcdf`
* Added #TODO for @shanaxel42 to doc the overlaps code. 
Other changes relate to refactorings of the above methods.
> Update IntensityTable documentation and harmonize method names

- starfish/codebook/test/test_metric_decode.py
- starfish/codebook/test/test_normalize_code_traces.py
- starfish/codebook/test/test_per_round_max_decode.py
- starfish/imagestack/imagestack.py
- starfish/intensity_table/intensity_table.py
- starfish/intensity_table/test/test_empty_intensity_table.py
- starfish/intensity_table/test/test_from_imagestack.py
- starfish/intensity_table/test/test_from_spot_data.py
- starfish/spots/_detector/detect.py
Currently, we use the offset of r/c/z to label the axes on the intensity table.  We should instead be using the axes labels from the ImageStack.  This PR makes that change in three key areas:
1. `IntensityTable.empty_intensity_table` now accepts the labels for the axes.
2. `IntensityTable.from_spot_data` now accepts the labels for the axes and verifies that the number of labels matches the intensity data.
3. `IntensityTable.from_image_stack` reads the labels for the zplane axes and assigns them correctly.
Test plan: Add a test that instantiates a labeled ImageStack and derives an IntensityTable from it.  Also ran `make test && make -j run-notebooks`.
Depends on #1178
Fixes #1168
> Allow for intensity tables with labeled axes

- starfish/imagestack/indexing_utils.py
- starfish/imagestack/test/test_index.py
When the selection removes a dimension, xarray.expand_dims does not expand the non-indexed dimensions that were removed.  For example, if one selects only a single zplane, it reduce the z physical coordinate to a coordinate scalar, and not an array of size 1.
When we detect that an axis was reduced out of existence, we ensure that the dependent axes are restored to arrays.
Test plan: Wrote a test that selects an ImageStack using a variety of selectors.  In each case, the length of each indexed dimension (i.e., X, Y, ZPLANE) must match its dependent dimension (i.e., XC, YC, ZC).
> Fix the restoration of non-indexed axes.

- starfish/imagestack/imagestack.py
- starfish/imagestack/test/test_index.py
`_tile_data.keys()` returns tiles outside the scope of the imagestack if it has been subselected.  Instead, use `_iter_axes(..)`, which uses the actual xarray coordinates to determine which tiles exist.
Test plan: Add a test that selects and exports an imagestack.
Depends on #1189
Fixes #1154
> Avoid use of _tile_data.keys()

- docs/source/getting_started/installation/index.rst
When starting up a dev environment, we should clone the github repo, not check it out.
Furthermore, we should clone from git:// rather than ssh://
Test plan: visual.
> Clone a repo, not checkout.

- starfish/__init__.py
Remove some easy packages that shouldn't be in the package's top-level namespace
See: https://github.com/spacetx/starfish/issues/1208 for the harder stuff that we should also attend to.
> [Easy] remove unused packages from top-level namespace. 

- docs/source/_static/tutorials/exec_image_corrections.py
- starfish/image/_filter/test/test_api_contract.py
- starfish/image/_filter/test/test_filter.py
- starfish/image/_filter/test/test_histogram_matching.py
- starfish/image/_filter/test/test_linear_unmixing.py
- starfish/image/_filter/test/test_zero_by_channel_magnitude.py
- starfish/imagestack/imagestack.py
- starfish/imagestack/test/factories/from_codebook.py
- starfish/imagestack/test/test_apply.py
- starfish/imagestack/test/test_from_numpy_array.py
- starfish/imagestack/test/test_max_proj.py
- starfish/intensity_table/intensity_table_coordinates.py
- starfish/intensity_table/test/test_concatenate.py
- starfish/intensity_table/test/test_from_imagestack.py
- starfish/intensity_table/test/test_intensity_table_serialization.py
- starfish/intensity_table/test/test_stack_intensity_table_reshaping.py
- starfish/intensity_table/test/test_to_mermaid.py
- starfish/multiprocessing/test/test_multiprocessing.py
- starfish/spots/_detector/test/test_local_search_blob_detector.py
- starfish/spots/_detector/test/test_spot_detection.py
- starfish/spots/_pixel_decoder/combine_adjacent_features.py
- starfish/spots/_pixel_decoder/test/test_calculate_mean_pixel_traces.py
- starfish/spots/_pixel_decoder/test/test_intensities_to_decoded_image.py
- starfish/spots/_target_assignment/label.py
- starfish/test/factories.py
* replace xarray groupby with pandas groupby in `combine_adjacent_features`, resulting in > 1000x speed up of the method and a 5x speed up in the pixel spot decoder. 
Sorry for the unclean diff, my PR's aren't stacked and I merged a few.  `starfish/spots/_pixel_decoder/combine_adjacent_features.py` contains the only changes not covered by other PRs. 
Before: 
After: 
* Note that `create_spot_attributes` may also be possible to speed up, further increasing the speed of this function. 
cc @shanaxel42 @kne42 for awareness, xarray devs really aren't kidding when they say:
> Note that for one-dimensional data, it is usually faster to rely on pandas’ implementation of the same pipeline.
ref: http://xarray.pydata.org/en/stable/groupby.html
> Ajc speed up combine adjacent features

- starfish/spots/_assign_targets/label.py
- starfish/spots/_detect_pixels/combine_adjacent_features.py
Trying to knock some seconds off of starfish. Here's part 2!
* adds vectorization to spot lookups over label images
before: 
after:
> vectorize labeling spot lookups

- docs/source/getting_started/installation/index.rst
I was a little more specific about how to install a pip and a virtualenv since I ran into lots of issues with accidentally overriding apt-get files.
> Adding windows install instructions

- docs/source/api/index.rst
- docs/source/api/recipe/index.rst
- starfish/recipe/__init__.py
- starfish/recipe/errors.py
- starfish/recipe/filesystem.py
- starfish/recipe/runnable.py
- starfish/recipe/test/fakefilter.py
- starfish/recipe/test/test_runnable.py
Runnable is the base unit of a recipe.  Each runnable constitutes a PipelineComponent with a specific algorithm.  Constructor arguments that are FileProviders are loaded into memory and passed in.  Inputs to the `run()` method can also include FileProviders.  In all cases, FileProviders are associated with a file path or url.  The type is inferred from the typing parameters of the method (currently supported: ImageStack, IntensityTable, ExpressionMatrix, and Codebook).
Runnables will be wired together to constitute a pipeline recipe.
Test plan: Added tests to verify a simple Runnable, chained Runnables, and Runnables that has constructor arguments that are FileProviders.
This is a continuation of #1097
> Introduce Runnable

- docs/source/api/recipe/index.rst
- docs/source/creating_an_image_processing_pipeline/index.rst
- starfish/recipe/__init__.py
- starfish/recipe/recipe.py
- starfish/recipe/test/test_recipe.py
Builds on top of #1163 to construct and run recipes with one or more runnables.
A recipe wires together one or more runnables.  Inputs to recipes are available to the recipe itself as the magic variable name "file_inputs".  A runnable is invoked by the magic function "compute".  Anything written to the magic variable "file_outputs" is matched and written out to a set of output paths.
This is a continuation of #1117
Fixes #311
> Recipe and recipe execution

- starfish/__init__.py
- starfish/recipe/cli.py
- starfish/test/full_pipelines/recipe/_base_recipe_test.py
- starfish/test/full_pipelines/recipe/iss_recipe.txt
- starfish/test/full_pipelines/recipe/test_iss.py
1. Add the recipe runner CLI entry point.
2. Add a recipe for the ISS pipeline and a test that exercises the recipe.
Test plan: `pytest starfish/test/full_pipelines/recipe`
Depends on #1192 
Fixes #311
> Recipe runner CLI entry point

- Makefile
- docs/source/_static/data_processing_examples/iss_cli.sh
1. Add a `test-examples` rule that sets TESTING=1, and runs the examples.  Rationale: the data processing examples might rationally be run with multiple FOVs.  In our testing environment, we likely will only want to run a single FOV.  Happy to change the logic for this if this rationale does not hold.
2. Update `docs/source/_static/data_processing_examples/iss_cli.sh` to match `starfish/test/full_pipelines/cli/test_iss.py`
Test plan: `make -j test-examples`
NOT IN THIS PR: any integration into travis
> Fix data processing examples.

- docker/Dockerfile
- docker/environment.yml
After upgrading conda, the following showed up:
```
$ conda env create -n sf01 -f docker/environment.yml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
```
> Add pip to docker environment

- starfish/__init__.py
- starfish/__main__.py
`starfish/__main__.py` is so that we can do `python -m starfish`, which is what pycharm does.
`starfish/test/__init__.py` is so that setuptools includes the pipeline tests in the zip file.
> Add missing files for starfish initialization

- starfish/core/config/test/test_config.py
StarfishConfig() will read from ~/.starfish/config unless we set STARFISH_CONFIG in the environment.
Test plan: `test_starfish_environ` no longer throws a warning.
> Isolate test environment.

- starfish/core/codebook/codebook.py
- starfish/core/intensity_table/intensity_table_coordinates.py
- starfish/core/spots/_decode/test/test_decoding_without_spots.py
* add missing metadata to empty tables when zero spots are detected
* add missing metadata to empty tables when zero spot tables are passed to a decoder
* verify that empty intensity tables can be converted to decoded_spots
* verify those tables can be loaded and dumped to disk
* write down tests
Fixes #1271
> Enable zero-spot decoding

- starfish/core/config/test/test_config.py
- starfish/core/util/config.py
If the config value in the config file is false, we currently just return the default value.  The reason is that the test checks for falsey rather than not None, and we fall through.
Test plan: wrote a test that hits this case, and fixed it with the code patch.
> Fix config value == False

- starfish/core/intensity_table/intensity_table.py
- starfish/core/intensity_table/intensity_table_coordinates.py
- starfish/core/intensity_table/test/test_intensity_table_coords.py
- starfish/core/intensity_table/test/test_synthetic_intensities.py
- starfish/core/spots/_detect_spots/blob.py
- starfish/core/spots/_detect_spots/trackpy_local_max_peak_finder.py
- starfish/core/test/factories.py
1. Remove the casts to int.
2. Interpolate the coordinates if there are more than one pixel location, otherwise use sel.
3. Update tests.
Fixes #1310
> Preserve subpixel offsets from spot detection

- starfish/core/pipeline/algorithmbase.py
use `functools.wraps` to properly propagate the `__name__` and `__doc__` attributes of `run` methods (as modified with `AlgorithmBaseType.run_with_logging`)
this allows documentation tools to properly capture and build the documentation for these methods whereas it was previously blank:
note that this is the minimum implementation for such a process; for more feature-complete wrapping, one should use the [`decorator`](https://github.com/micheles/decorator/blob/master/docs/documentation.md) or [`wrapt`](https://wrapt.readthedocs.io/en/latest/quick-start.html) packages
> fix run method docs

- starfish/core/image/_filter/call_bases.py
- starfish/core/image/_filter/test/test_call_bases.py
As discussed in #1263, this filter component performs base calling for in situ sequencing. The filter determines which base (if any) is represented in each X, Y location in a (round, z plane) slice (i.e., in a (channel, x, y) image). Each pixel value in the resulting image is the base quality score for a given base call.
Currently, the base quality score is calculated as the intensity of the called base divided by the L2 norm of the intensities in all 4 channels (this is how it is done in the original BaristaSeq paper). However, I think it could be useful to add the capability for the user to provide their own custom functions. However, this will likely present challenges for provenance logging. Thoughts, @ambrosejcarr and @dganguli?
```python
import numpy as np
from starfish import …
```
> RFC: Base calling filter for in situ sequencing

- REQUIREMENTS-STRICT.txt
- REQUIREMENTS.txt
- starfish/REQUIREMENTS-STRICT.txt
Key change is that json files are read in parallel.  (see https://github.com/spacetx/slicedimage/pull/91)
> [easy] Bump slicedimage requirement to 3.1.0

- starfish/core/imagestack/physical_coordinate_calculator.py
- starfish/core/imagestack/test/test_physical_coordinate_calculator.py
It should reflect that the physical coordinate of a pixel is the top-left corner of a pixel.  Therefore, the last pixel's coordinate should be the top-left corner and is the max of the tile's range.
Test plan: added a test!
Part of #1332
> Fix physical coordinate calculator

- starfish/core/spots/_detect_spots/trackpy_local_max_peak_finder.py
The `trackpy.locate()` wrapped by starfish is missing the
`max_iterations` parameter which allows additional refinement of
detected spot's center of mass.
see: https://soft-matter.github.io/trackpy/dev/generated/trackpy.locate.html
> Add a missing parameter to wrapper for trackpy local max peak finder

- starfish/core/spacetx_format/test_codebook.py
- starfish/core/spacetx_format/test_experiment.py
- starfish/core/spacetx_format/test_field_of_view.py
- starfish/core/spacetx_format/test_fov_manifest.py
- starfish/core/spacetx_format/test_fuzz.py
- starfish/core/spacetx_format/util.py
1. Use Version objects instead of strings when possible.
2. Use the authoritative VERSIONs declared in the code instead of duplicating.
3. Use the Latest*Validator primitives to construct the current validators.
Test plan: `pytest -v -n8 starfish/core/spacetx_format/`
This is built on top of #1278
> Use the Versions specified in the code

- REQUIREMENTS-STRICT.txt
- REQUIREMENTS.txt
- starfish/REQUIREMENTS-STRICT.txt
This deploys the fix in https://github.com/spacetx/slicedimage/pull/99 to resolve https://github.com/spacetx/starfish/issues/1277
> [easy] bump to slicedimage 3.1.1

- starfish/core/imagestack/imagestack.py
- starfish/core/imagestack/parser/_tiledata.py
- starfish/core/imagestack/parser/crop.py
- starfish/core/imagestack/parser/numpy/__init__.py
- starfish/core/imagestack/parser/tileset/_parser.py
- starfish/core/imagestack/test/test_from_numpy_array.py
The coordinates for zplanes need to be a sequence of coordinate values since a start/end range does not work for irregularly spaced coordinates.  To make the API consistent, this PR passes _all_ coordinates to the numpy parser and between the parsers and ImageStack as sequences of coordinate values.
Add a test for from_numpy(..) to verify that construction of an ImageStack from a numpy array with coordinates works correctly.
Test plan: `pytest -v -n4 starfish/core/imagestack/test/`
Depends on #1350
> ImageStack parsers should provide coordinates as an array

- starfish/core/imagestack/imagestack.py
- starfish/core/spots/_detect_spots/test/test_spot_detection.py
Added two test cases where we create ImageStacks with labeled axes, and run spot detection on them.  One is with a reference image, and the other does not.
Verified that without the fixes in #1349, the tests fail.
Fixes #1258
> Tests for spot detection on labeled data

- starfish/core/imagestack/test/factories/all_purpose.py
- starfish/core/imagestack/test/factories/unique_tiles.py
- starfish/core/imagestack/test/imagestack_test_utils.py
- starfish/core/imagestack/test/test_cropped_load.py
- starfish/core/imagestack/test/test_labeled_indices.py
1. Create a `LocationAwareFetchedTile` class, which is like `FetchedTile`, but is explicitly aware of its location in 5D space.
2. Create an all_purpose.imagestack_factory method that produces an ImageStack with the provided coordinate ranges.
3. Fix existing tests that did not deal with coordinates properly.
4. Fix `imagestack_test_utils.py::verify_physical_coordinates`, which used zplane as an index rather than a value.  In the case of labeled images, this makes a difference.
Test plan: `make -j all`
> Create an all-purpose ImageStack factory

- starfish/core/imagestack/imagestack.py
When we parse a 4D tileset into an ImageStack, we always set up a ZPLANE and initialize it to 0.  Similarly, we should always create Z coordinates and set it to NaN.
> Always create Z coordinates, even on 4D datasets.

- starfish/core/intensity_table/overlap.py
Regular min/max was doing some crazy sorting on our xarray coords. 
This take advantage of numpy's built in min/max functions and Speeds up `IntensityTable.concatenate_intensity_tables(overlap_strategy=TAKE_MAX`) on the three tables provided by @njmei  from 479.860 seconds to  0.216 seconds.
fixes: #1363
> using numpy min/max functions for calculating IntensityTable overlaps

- starfish/experiment/builder.py
This commit addresses an import error encountered
when trying to import inplace TileFetcher functionality.
Though if you want to keep the inplace stuff a `secret`
option for now, that's understandable too...
Example failing import:
```
from starfish.experiment.builder.inplace import (
InplaceFetchedTile,
enable_inplace_mode,
inplace_tile_opener)
```
In the future these should be imported with:
```
from starfish.experiment.builder import (
InplaceFetchedTile,
enable_inplace_mode,
inplace_tile_opener)
```
> Add inplace TileFetcher options back to public builder API

- starfish/core/experiment/builder/__init__.py
- starfish/core/experiment/builder/cli.py
Need this for the generalized experiment formatter (#1318), and @njmei needs it for #1322.
Test plan: `pytest -v -n4 starfish/core/experiment/builder/test/`
> Add the ability to write labeled experiments

- docs/source/_static/data_formatting_examples/format_merfish_U2OS_data.py
* Update tilefetcher to format complete dataset instead of 1 fov
Testing strategy: 
```python
import starfish.data
exp = starfish.Experiment.from_json(https://d2nhj9g34unfro.cloudfront.net/browse/formatted/MERFISH/20190511/
exp  # do things, verify 496 fovs
```
> TileFetcher formats complete 496 fov MERFISH dataset

- starfish/core/codebook/codebook.py
When there are intensities that are near-zero (due to numpy generating some denorm-to-zero values instead of zeros), we sometimes get near-zero total intensity.  When we normalize that, we get infinite values.  Instead of using `fillna`, we replace anything that is not finite with the partitioned value.
Test plan: `make fast` and on the linux docker container, I verified that the code snipped posted by @richardque works now.
Fixes #1365
> Handle denormalized numbers when normalizing intensities/codebooks

- notebooks/py/smFISH.py
- notebooks/smFISH.ipynb
1. `iterate_image_type` is now deprecated.  Use `get_images` instead.
2. Remove extra call to `get_image(..)`.  The output is not used anywhere.
Test plan: python notebooks/py/smFISH.py
> Fix smFISH notebook.

- starfish/core/image/_filter/clip_percentile_to_zero.py
- starfish/core/image/_filter/clip_value_to_zero.py
This commit adds two custom clip `Filter` classes called:
ClipValueToZero and ClipPercentileToZero
They operate by clipping to a minimum value (or min percentile value)
and then subtracting the entire image with that minimum value.
This will allow us to [create/run](https://spacetx-starfish.readthedocs.io/en/latest/creating_an_image_processing_pipeline/tutorials/exec_running_a_pipeline.html#running-a-pipeline) recipes for our pipeline(s).
> Add custom clip Filter classes

- starfish/core/image/_registration/transforms_list.py
Right now the TranslationList object is a bit tricky to work with. I often want to print out the translations that I've calculated to test if the data is registered; learning the translations and looking at the results is one of the best non-visual ways to accomplish this. 
Printing out the TranslationList at present returns: 
`<starfish.core.image._registration.transforms_list.TransformsList object at 0x15df55da0>`
This PR adds a `__repr__` that instead prints: 
```
In [10]: translation_list
Out[10]: image_fragment: {<Axes.ROUND: 'r'>: 0, <Axes.ZPLANE: 'z'>: 0, <Axes.CH: 'c'>: 3}
translation: y=-22.82, x=5.778, rotation: 0.0, scale: 1.0
image_fragment: {<Axes.ROUND: 'r'>: 1, <Axes.ZPLANE: 'z'>: 0, <Axes.CH: 'c'>: 3}
translation: y=-22.173, x=1.871, rotation: 0.0, scale: 1.0 …
```
> [RFC] Add TransformsList __repr__

- starfish/core/expression_matrix/concatenate.py
- starfish/core/expression_matrix/expression_matrix.py
- starfish/core/expression_matrix/test/test_concatenate.py
- starfish/core/intensity_table/concatenate.py
* Add a method to concatenate ExpressionMatrix objects
* Add a test
* Fix constant usage in ExpressionMatrix
* Fix IntensityTable concatenate, which was returning a DataArray instead of an IntensityTable
> Add concatenate method for ExpressionMatrix

- docs/source/_static/data_formatting_examples/format_iss_breast_data.py
- starfish/data.py
* update starfish.data with complete ISS experiment
* add coordinates to experiment
* update TileFetcher
Testing strategy: 
- Ran notebook with new data, got same results for `fov_000` in new experiment (is named `fov_001` in master)
> Format complete ISS experiment and expose in starfish.data

- .travis.yml
- docs/source/_static/data_processing_examples/subdir.mk
- notebooks/subdir.mk
With this change, one can just run `make notebooks/py/smFISH.py`
Also, we run all notebooks with ipython instead of python now.
> Fix how we structure the run notebook rules.

- REQUIREMENTS.txt
- starfish/core/experiment/builder/__init__.py
- starfish/core/experiment/builder/cli.py
- starfish/core/experiment/builder/test/test_build.py
- starfish/experiment/builder.py
Both `build_image` and `write_experiment_json` get an irregular flavor.  In each case, the irregular case accepts an iterator of `TileCoordinate` objects, which record where the tile is in the 5D tensor.  `build_image` and `write_experiment_json` internally call their irregular flavors because they are very generalized.
#1374 introduced `write_labeled_experiment_json`, and this replaces that operation.  We are not deprecating that API because it never made it into a release; we will simply replace it.
Fixes #1322
> Support for irregular images in the builder

- notebooks/BaristaSeq.ipynb
- notebooks/py/BaristaSeq.py
#1255 removed 'nan's from pixel decoding so the drop('nan') is no longer needed.
> [easy] remove nan code, fix baristaSeq notebook

- starfish/core/image/_filter/element_wise_mult.py
- starfish/core/image/_filter/test/test_filter.py
Fixes #1145. Asserts that element_wise returns an xarray and adds a test
> Saxelrod fix element wise

- starfish/core/experiment/builder/__init__.py
@shanaxel42 requested this in #1382, but I missed a few places.
Test plan: none whatsoever.
> [easy] Rename tile_coordinates to tile_identifier

- notebooks/py/BaristaSeq.py
- starfish/core/spots/_detect_pixels/combine_adjacent_features.py
fixes: #1275 
Test: Run BaristaSeq with Clip(expand_dynamic_range=False)
> Warn and return empty SpotAttributes when PixelDecoding finds 0 spots

- starfish/core/experiment/builder/test/inplace_script.py
- starfish/core/experiment/builder/test/test_inplace.py
When we construct an experiment in-place, the source data comes from the tiles already on disk.  Therefore, whatever image data we provide the TileFetcher that we pass into `write_experiment_json` should be discarded.  This verifies that the data from the tiles on the disk are what gets constituted into the experiment, and that the data returned by TileFetcher is ignored.
Test plan: passed the test.
Fixes #1388
> Codify the expectation that in-place experiment construction does not rely on TileFetcher data

- starfish/core/image/_filter/reduce.py
- starfish/core/image/_filter/test/test_reduce.py
Module defaults to np (== numpy).  Class no longer accepts a callable.  Alias list is a dict that relatively easy to extend.
> Refactor reduce to take an optional module and only a function name.

- docs/source/_static/data_formatting_examples/format_baristaseq.py
- docs/source/_static/data_formatting_examples/format_imc_data.py
- docs/source/_static/data_formatting_examples/format_iss_breast_data.py
- docs/source/_static/data_formatting_examples/format_iss_data.py
- docs/source/_static/data_formatting_examples/format_merfish_U2OS_data.py
- docs/source/_static/data_formatting_examples/format_osmfish.py
- docs/source/_static/data_formatting_examples/format_seqFISH.py
- starfish/core/experiment/builder/defaultproviders.py
- starfish/core/experiment/builder/providers.py
- starfish/core/experiment/builder/test/inplace_script.py
- starfish/core/imagestack/imagestack.py
- starfish/core/imagestack/indexing_utils.py
- starfish/core/imagestack/test/factories/all_purpose.py
- starfish/core/imagestack/test/test_coordinates.py
- starfish/core/imagestack/test/test_slicedimage_dtype.py
- starfish/core/types/__init__.py
- starfish/types.py
It is either a scalar or a range.
Also ninja'ed in the fix for `convert_coords_to_indices` to return a Union[int, Tuple[int, int]], as indexers must be integers.
> [easy] Create a data type for describing a coordinate value.

- starfish/core/image/_filter/max_proj.py
> [easy] Warn about the deprecation of the MaxProject filter

- docs/source/_static/data_formatting_examples/format_osmfish.py
1. starfish.util has moved to starfish.core.util
2. use click.argument instead of click.option.
Test plan: used formatter against osmfish 3d TIFFs
> Fix osmfish formatter.

- starfish/core/imagestack/test/imagestack_test_utils.py
x/y coordinates has to be a range (i.e., Tuple[Number, Number]).
z can either be any of a range (Tuple[Number, Number], or a single scalar Number, when `zplane` is provided.
> [easy] Fix the types for verify_physical_coordinates

- starfish/core/imagestack/test/factories/all_purpose.py
- starfish/core/imagestack/test/factories/unique_tiles.py
- starfish/core/imagestack/test/test_cropped_load.py
- starfish/core/imagestack/test/test_labeled_indices.py
This allows us to generate data that is unique across the entire 6-dimensional tensor.  This helps verify that multi-fov datasets are constructed properly.
> [easy] Add FOV-id to unique data generator

- starfish/core/experiment/builder/test/factories/__init__.py
- starfish/core/experiment/builder/test/factories/all_purpose.py
- starfish/core/experiment/builder/test/factories/unique_tiles.py
- starfish/core/imagestack/test/factories/__init__.py
- starfish/core/imagestack/test/factories/all_purpose.py
- starfish/core/imagestack/test/factories/unique_tiles.py
- starfish/core/imagestack/test/test_cropped_load.py
- starfish/core/imagestack/test/test_labeled_indices.py
Currently, we have an ImageStack factory that takes a set of parameters, builds a slicedimage Collection, and then parses that yield the requested ImageStack.
It turns out that building a slicedimage Collection is quite useful if we want to write just a set of tiles and build up the json metadata around it.
This PR extracts the logic that builds the slicedimage Collection, extends it to support multi-FOV collections, and puts it in a separate place.  Then we adapt the ImageStack factory to utilize the slicedimage Collection factory.
Test plan: `pytest -v -n4 starfish/core/imagestack/test`
Depends on #1402, #1403
> Create a slicedimage Collection factory

- notebooks/subdir.mk
This should unbreak the cronjob.  I think I broke this in #1384.  Whoops!
> Fix the path where we find skip files

- starfish/core/experiment/builder/inplace.py
- starfish/core/experiment/builder/test/inplace_script.py
#1389 codifies the expectation that in-place tile construction does not rely on the data from `tile_data()`.  This removes the requirement that in-place tile construction even needs to implement `tile_data()` by providing a default implementation.
Note that this doesn't preclude someone from implementing `tile_data()` (example: the structured data formatter in #1421) for cases where the TileFetcher can be used inplace or non-inplace.
> Remove tile_data from set of methods in-place tile construction needs to implement

- starfish/core/spots/_detect_pixels/combine_adjacent_features.py
This ensures we shut down the pool when complete.
Test plan: `pytest -v -n4  starfish/core/spots/`
Fixes: #1435
> Instantiate the multiprocessing pool using `with`

- REQUIREMENTS-STRICT.txt
- REQUIREMENTS.txt
- starfish/REQUIREMENTS-STRICT.txt
- starfish/core/experiment/builder/__init__.py
- starfish/core/experiment/builder/inplace.py
- starfish/core/experiment/builder/structured_formatter.py
- starfish/core/experiment/builder/test/inplace_script.py
Test plan: in-place experiment writing tests pass.
Note that travis won't succeed until https://github.com/spacetx/slicedimage/pull/109/ is approved and released.
> Update in-place experiment writing to use the new WriterContract API in slicedimage 4.0.0

- .travis.yml
This will be implemented as a AWS cloudwatch event -> AWS lambda -> travis API push that hits once a week.
This should bring some sanity to our crons.
> Get rid of the check-requirements cron job.

- starfish/core/image/Filter/reduce.py
- starfish/core/image/Filter/zero_by_channel_magnitude.py
- starfish/core/imagestack/imagestack.py
- starfish/core/imagestack/test/test_slicedimage_dtype.py
- starfish/core/multiprocessing/test/test_multiprocessing.py
The imagestack's xarray is created with coordinates and NaNs for the values.  When someone accesses the `xarray` property, `get_slice()`, `set_slice()` (except when called by the code initializing the data array), `transform()`, `sel()`, or `max_proj()`, the array is initialized with the correct data.
Theoretically, this allows someone to initialize the ImageStack and examine the coordinates without having the tile data read.
Test plan: pass existing tests.
> on-demand loading of data.

- REQUIREMENTS-STRICT.txt
- starfish/REQUIREMENTS-STRICT.txt
For reasons that are not clear, pyparsing 2.4.1 seems to have been removed.  Following https://github.com/pyparsing/pyparsing/issues/105 to keep an eye on it.
> downgrade pyparsing

- starfish/core/experiment/builder/__init__.py
- starfish/core/experiment/builder/test/test_small_axis.py
If num_round/num_ch/num_zplane > X or Y size, then throw a warning.
Fixes #1523
> Throw a warning when the data size is unusual.

- starfish/core/experiment/builder/inplace.py
- starfish/core/spacetx_format/util.py
Doing so does not work great on Windows.  Instead, one should use pathlib.Path.as_uri().
> get rid of file:// creation by string concatenation

- starfish/core/multiprocessing/test/test_multiprocessing.py
They are meaningless and bound to fail.
> disable multiprocessing tests on Windows

- starfish/core/multiprocessing/pool.py
In our implementation of multiprocessing, we do not actually leverage python's `multiprocessing` module if n_processes=1 or if the OS is NT.  In that case, we call all the code in the current process, current thread.  Part of that involves calling the `multiprocessing.Pool`'s initializer.  However, that is an optional argument, and we don't want to call it if it's not present.
> only call initializer if it's present

- starfish/core/types/test/test_decoded_spots.py
Generally, it'll all resolve to float32 anyway, but in this test, the autodetected type was int for one column, but was loaded back in as float.  This quirk appears to be specific to Windows, for whatever reason.
> don't check frame type when testing decoded spots.

- .travis.yml
On a Windows sh image, it does nothing.  I don't want to leave this in in case it confuses someone.
> Remove python version directive.

- starfish/core/image/Filter/element_wise_mult.py
Instead of reaching into the private _data field, use the xarray property.
Test plan: `pytest -v -n8  --ff starfish/core/image/Filter/test`
Part of #834
> [easy] use the xarray property

- starfish/core/image/Filter/reduce.py
1. Docblock does not accurately reflect the data type we want.
2. In order to accept `Axes` as strings, we need to find the matching enum.
3. Constrain internal code to work in the enum.
> [easy] Fix reduce

- starfish/core/imagestack/imagestack.py
- starfish/core/imagestack/test/test_apply.py
With the existing code, funcs passed to apply and transform can only use keyword arguments.  This is unnecessarily limiting, and if we want to support #1446, we need to be able to work with a variety of functions with their own argument calling mechanisms.
> funcs passed to apply and transform can use positional arguments

- starfish/core/image/Filter/__init__.py
- starfish/core/image/Filter/map.py
- starfish/core/image/Filter/test/test_map.py
This allows a variety of mapping functions to be added to a starfish pipeline without writing a new Filter.
Test plan: Add a simple test.
Fixes #1446
Depends on #1519
> map filter

- starfish/core/experiment/builder/__init__.py
- starfish/core/experiment/builder/inplace.py
- starfish/core/experiment/experiment.py
- starfish/core/image/Filter/max_proj.py
Add a ..deprecated:: docstring.  This will serve as a helpful example next time someone wants to deprecate something.
Part of #1508
> Bring existing deprecated methods in compliance with deprecation policy.

- starfish/core/util/dtype.py
- starfish/core/util/test/test_dtype.py
There are two flaws with the existing `preserve_float_range` implementation:
1. It wastes memory by copying even when it does not have to.
2. It does extra loops through the array.
This attempts to optimize `preserve_float_range`, while retaining flexibility for the caller to configure the behavior we want.  There is a new parameter, `preserve_input`, which controls whether or not it is important to preserve the input.  When it is true, we will make deliberate effort to preserve the input data, even at the cost of performance.  When it is false, we will overwrite the input data unless we are forced to make a copy (the two reasons that compel us to do so are if the dtype is different and if the input array is immutable).
Test plan: Add new tests to cover all the scenarios, and `make -j …
> Don't waste memory/compute in preserve_float_range

- docs/source/api/data_structures/decoded_intensity_table.rst
- docs/source/api/data_structures/index.rst
- docs/source/help_and_reference/glossary/glossary.md
- starfish/__init__.py
- starfish/core/codebook/codebook.py
- starfish/core/expression_matrix/test/test_serialization.py
- starfish/core/intensity_table/decoded_intensity_table.py
- starfish/core/intensity_table/intensity_table.py
- starfish/core/intensity_table/test/factories.py
- starfish/core/intensity_table/test/test_intensity_table_coords.py
- starfish/core/intensity_table/test/test_to_mermaid.py
- starfish/core/spots/AssignTargets/label.py
- starfish/core/spots/Decode/metric_decoder.py
- starfish/core/spots/Decode/per_round_max_channel_decoder.py
- starfish/core/spots/Decode/test/test_decoding_without_spots.py
- starfish/core/spots/DetectSpots/test/test_synthetic_data.py
- starfish/core/types/test/test_decoded_spots.py
- workflows/wdl/iss_published/recipe.py
- workflows/wdl/iss_spaceTX/recipe.py
Introducing DecodedIntensityTable which is just a subclass of IntensityTable. I moved anything related to decoded spots into the DecodedIntensityTable class. This is mostly to reduce confusion in the codebase between the outputs of various spot finding and decoding methods. In most cases the very end of a pipeline will now be a DecodedIntensityTable.
> Adding DecodedIntensityTable class

- REQUIREMENTS-STRICT.txt
- starfish/REQUIREMENTS-STRICT.txt
- starfish/core/codebook/codebook.py
- starfish/core/expression_matrix/expression_matrix.py
- starfish/core/image/Filter/reduce.py
- starfish/core/imagestack/imagestack.py
- starfish/core/imagestack/indexing_utils.py
- starfish/core/intensity_table/intensity_table.py
- starfish/core/intensity_table/intensity_table_coordinates.py
- starfish/core/segmentation_mask.py
- starfish/core/spots/AssignTargets/label.py
- starfish/core/spots/DetectPixels/combine_adjacent_features.py
- starfish/core/spots/DetectSpots/_base.py
- starfish/core/spots/DetectSpots/detect.py
- starfish/core/spots/DetectSpots/local_search_blob_detector.py
- starfish/core/util/dtype.py
- starfish/util/plot.py
xarray 0.13.0 now has type annotations, which breaks a bunch of things.  This attempts to fix the issues.
It appears that xr.DataArray no longer acts like a Sequence[Number], so a bunch of things need to be casted.  It's probable that we should create a new type annotation for array-like objects (i.e., Union[Sequence, xr.DataArray, np.ndarray]).
Depends on #1561 
Test plan: travis.  https://travis-ci.com/spacetx/starfish/builds/128278048 has the errors from upgrading xarray to 0.13.0.
> Fix mypy + xarray errors

- starfish/core/spots/AssignTargets/_base.py
AssignTargetsAlgorithm should be operating with DecodedIntensityTable.
> [easy] Fix superclass type annotations

- docs/source/api/spots/index.rst
- starfish/core/spots/DecodeSpots/_base.py
- starfish/core/spots/FindSpots/_base.py
- starfish/core/types/__init__.py
- starfish/core/types/_spot_finding_results.py
- starfish/spots.py
This PR lays some of the ground work for the spot finding refactor. 
- Adds two new modules FindSpots and DecodeSpots (which will be the only ones left by the end of this).
- Adds their base class api contracts. 
- Adds new class SpotFindingResults which is a wrapper class around a dictionary of round/ch index pairs and the spots found there (SpotAttributes).
Depends on #1489
> Adding new modules and data SpotFindingResults class. 

- starfish/core/intensity_table/intensity_table_coordinates.py
- starfish/core/intensity_table/test/test_intensity_table_coords.py
- starfish/core/spots/DetectPixels/pixel_spot_decoder.py
- starfish/core/spots/DetectSpots/detect.py
- starfish/core/spots/DetectSpots/local_search_blob_detector.py
- starfish/core/types/_spot_finding_results.py
This PR adds physical coordinate information to the SpotResultsClass. This is needed for when the coordinates get transferred during decoding.
Depends on #1489 #1515 
See it in action in #1518
> Add physical Coordinate support to SpotFindingResults 

- .travis.yml
- Makefile
- REQUIREMENTS-CI.txt
- setup.py
- starfish/core/_display.py
- starfish/core/spots/AssignTargets/_base.py
- starfish/core/test/test_display.py
for `starfish.display`:
- unpin napari version (set minimum to `0.1.5`)
- add tests
- view masks by themselves
please note that we had to use a hack to test the module as `pytest-qt` was not working properly for unknown reasons
> starfish.display: unpin napari version, add tests, view masks separately

- starfish/core/types/_spot_attributes.py
A bug came up during the spot finding refactor. You can't do the interpolation needed for a coordinate transfer if the arrays in your intensity table are just objects.
> [Easy] Adding dtypes to SpotAttributes

- notebooks/STARmap.ipynb
- notebooks/SeqFISH.ipynb
- notebooks/py/STARmap.py
- notebooks/py/SeqFISH.py
- starfish/core/spots/DecodeSpots/per_round_max_channel_decoder.py
- starfish/core/spots/DecodeSpots/test/test_nearest_neighbor_trace_builder.py
- starfish/core/spots/DecodeSpots/trace_builders.py
- starfish/core/spots/DecodeSpots/util.py
- starfish/core/spots/DetectSpots/local_search_blob_detector.py
- starfish/core/spots/FindSpots/blob.py
- starfish/core/types/__init__.py
- starfish/core/types/_constants.py
- starfish/core/types/_spot_finding_results.py
- starfish/types.py
Both STARmap and current Seqfish currently use LocalSearchBlobDetector. This refactor eliminates the need for a separate LocalSearchBlobDetector class and instead both assays now use the regular BlobDetector and the PerRoundMaxChannel with a trace building strategy of 'nearest neighbors'. A lot of the changes here are mostly just moving code that already existed in LocalSearchBlobDetector and a few changes to make BlobDetector work for both ISS and STARmap.
> Spot Refactor: LocalSearchBlobDetector

- starfish/core/_display.py
This PR updates starfish display for the napari `0.2.0` release. The only thing that should need to be changed is the `multichannel` keyword has been renamed to `rgb`. We will be making the release in the next few hours.
> napari 0.2.0 release

- starfish/core/imagestack/imagestack.py
- starfish/core/pipeline/algorithmbase.py
- starfish/core/types/_spot_finding_results.py
- starfish/core/util/logging.py
- starfish/test/full_pipelines/api/test_dartfish.py
- starfish/test/full_pipelines/api/test_iss_api.py
This PR does a bit of a provenance log refactor fixing some issues and also setting things up to work with the new FindSpots and DecodeSpots modules. 
Depends on #1515 #1489 #1516
> 1.) Provenance logging refactor and support for SpotFindingResults

- starfish/core/codebook/codebook.py
- starfish/core/codebook/test/test_approximate_nearest_code.py
- starfish/core/codebook/test/test_from_code_array.py
- starfish/core/codebook/test/test_metric_decode.py
- starfish/core/codebook/test/test_per_round_max_decode.py
- starfish/core/intensity_table/intensity_table.py
- starfish/core/intensity_table/test/test_concatenate.py
- starfish/core/intensity_table/test/test_empty_intensity_table.py
- starfish/core/intensity_table/test/test_stack_intensity_table_reshaping.py
- starfish/core/intensity_table/test/test_synthetic_intensities.py
- starfish/core/spots/DetectPixels/combine_adjacent_features.py
- starfish/core/spots/DetectPixels/test/test_calculate_mean_pixel_traces.py
- starfish/core/spots/DetectSpots/detect.py
- starfish/core/spots/DetectSpots/test/test_synthetic_data.py
- starfish/core/test/factories.py
- starfish/core/test/test_synthetic_spot_creation.py
These two seem to think that 'c' precedes 'r', which is different from the rest of the codebase.
> Fix dimension ordering on Codebook and IntensityTable

- docs/source/_static/data_processing_examples/iss_pipeline.py
- notebooks/ISS.ipynb
- notebooks/py/ISS.py
In #1540, I missed a conversion from Reduce.FunctionSource to types.FunctionSource.
> Fix broken build

- starfish/core/image/Filter/reduce.py
- starfish/core/imagestack/imagestack.py
- starfish/core/imagestack/test/test_max_proj.py
This is syntactic sugar to simplify single map / reduce operations.  Right now, we would need to instantiate the filter and then run it against the stack, e.g.,
```
max_projector = Filter.Reduce((Axes.CH, Axes.ROUND, Axes.ZPLANE))
max_projected = max_projector.run(stack)
```
With this, it simplifies to:
```
max_projected = stack.reduce((Axes.CH, Axes.ROUND, Axes.ZPLANE), "max")
```
Test plan: Converted imagestack/test/test_max_proj.py to use this idiom.
Depends on #1540
> Add map/reduce methods to ImageStack

- REQUIREMENTS-STRICT.txt
- REQUIREMENTS.txt
- starfish/REQUIREMENTS-STRICT.txt
- starfish/core/test/test_multiprocessing_workflow.py
We want to support multiprocessing + imagestack for two use cases:
1. algorithms that do not release the GIL do not run well under multithreading.
2. it allows us to parallelize across FOVs in an interesting way [1]
This adds a test case that we can pass an ImageStack to a child process for processing.
Note that this will not pass travis until https://github.com/spacetx/slicedimage/pull/125 is landed and released.
Test plan: this is the test plan
Depends on #1586
[1] Ideally, we should make it such that the child workers cooperatively share the compute resources.  This is not done today.  See #1588 for what needs to be done next.
> Test case for multiprocessing + imagestack

- starfish/core/segmentation_mask/segmentation_mask.py
- starfish/core/segmentation_mask/test/test_segmentation_mask.py
- starfish/core/spots/AssignTargets/label.py
Maps from cell id to mask.
Depends on #1578 
Part of #1497
> Convert SegmentationMaskCollection to a dict-like object

- starfish/core/codebook/codebook.py
- starfish/core/expression_matrix/expression_matrix.py
- starfish/core/intensity_table/decoded_intensity_table.py
- starfish/core/intensity_table/intensity_table.py
The absence of `__slots__` triggers a warning.
Test plan: travis alltest!
> Add __slots__ to classes that subclass xr.DataArray

- notebooks/STARmap.ipynb
- notebooks/SeqFISH.ipynb
- notebooks/py/STARmap.py
- notebooks/py/SeqFISH.py
- starfish/core/spots/DecodeSpots/per_round_max_channel_decoder.py
- starfish/core/spots/DecodeSpots/test/test_nearest_neighbor_trace_builder.py
- starfish/core/spots/DecodeSpots/trace_builders.py
- starfish/core/spots/DecodeSpots/util.py
- starfish/core/spots/DetectSpots/local_search_blob_detector.py
- starfish/core/spots/FindSpots/blob.py
- starfish/core/types/__init__.py
- starfish/core/types/_constants.py
- starfish/core/types/_spot_finding_results.py
- starfish/types.py
Both STARmap and current Seqfish currently use LocalSearchBlobDetector. This refactor eliminates the need for a separate LocalSearchBlobDetector class and instead both assays now use the regular BlobDetector and the PerRoundMaxChannel with a trace building strategy of 'nearest neighbors'. A lot of the changes here are mostly just moving code that already existed in LocalSearchBlobDetector and a few changes to make BlobDetector work for both ISS and STARmap.
depends on: #1518 #1517
> 3.) SeqFish/StarMap/LocalBlobSearch

- starfish/core/segmentation_mask/segmentation_mask.py
Replace the existing code with masked fill.
Depends on #1579, #1581
> Use masked fill to produce labeled images

- starfish/core/_display.py
- starfish/core/errors.py
- starfish/core/image/Filter/max_proj.py
- starfish/core/image/Filter/test/test_api_contract.py
- starfish/core/image/Segment/watershed.py
- starfish/core/image/_registration/ApplyTransform/test/test_warp.py
- starfish/core/image/_registration/LearnTransform/test/test_translation.py
- starfish/core/image/_registration/test/test_transforms_list.py
- starfish/core/imagestack/imagestack.py
- starfish/core/spots/DetectSpots/detect.py
Remove ImageStack.max_proj. Steer users towards using ImageStack.reduce.
Addresses comment in https://github.com/spacetx/starfish/pull/1342/files#r288261378
Fixes #220
Depends on #1548
> clean up max projection

- notebooks/osmFISH.ipynb
- notebooks/py/osmFISH.py
- starfish/core/spots/DecodeSpots/__init__.py
- starfish/core/spots/DecodeSpots/metric_decoder.py
- starfish/core/spots/FindSpots/__init__.py
- starfish/core/spots/FindSpots/local_max_peak_finder.py
This PR:
- adds a new version of LocalMaxPeakFinder to the FindSpots module that processes SpotFindingResults
-  Refactors osmFish to use FindSpots.LocalMaxPeakFinder and DecodeSpots.PerRoundMaxChannel with a trace building strategy of SEQUENTIAL
depends on: #1593  #1592 #1518 #1517
> 5.) refactoring localMaxPeakFinder/osmFIsh

- starfish/core/segmentation_mask/segmentation_mask.py
- starfish/core/segmentation_mask/test/test_segmentation_mask.py
regionprops are useful to characterize and filter segmented cells.  This PR changes what we store for mask data to be a tuple of binary mask and regionprops.  If we construct a mask collection from a labeled image, we retain the region props that are automatically calculated as a part of this conversion process.  If we construct a mask collection from what's stored on disk, we will calculate the regionprops when requested.
Test plan: Save to disk a mask collection generated from a labeled image, and after loading it from disk, verify that the region props of the two mask collections match.
Part of #1497
> Make regionprops available per mask

- setup.py
- starfish/__init__.py
- starfish/core/util/logging.py
1. Reduce the susceptibility for circular imports.  Right now, there is an arc from logging -> types -> SpotFindingResults -> logging.
2. Add a method to decode an encoded log back into a Log object.
3. Expose Log as a top-level starfish construct. (i.e., in the `starfish` namespace)
Test plan: travvvvvvis.
> Logging improvements

- starfish/core/imagestack/imagestack.py
We've used this codepath enough that it's reasonably safe to assume that it'll work.  This avoids the allocation of memory until the data is actually filled in.
Test plan: travis.
> Don't fill a new ImageStack with NaN

- starfish/core/codebook/codebook.py
Found this while working on decoding. The order of the codebook.json indices are out of order, everywhere else we use round, ch.
> [Easy] - fixing bug with codebook.to_json

- starfish/core/label_image/__init__.py
- starfish/core/label_image/label_image.py
- starfish/core/label_image/test/test_label_image.py
- starfish/core/label_image/util.py
Rather than passing around a naked 2D/3D array as a label image, create a type for holding that data.
Test plan: see tests!
Depends on #1617
Part of #1497
> Add a label image data type

- REQUIREMENTS-STRICT.txt
- REQUIREMENTS.txt
- starfish/REQUIREMENTS-STRICT.txt
The latest version of botocore caps python-dateutil at 2.8.0.  Unfortunately, if another package has already declared an unversioned dependency on python-dateutil, 2.8.1 is installed.  Later on, when botocore is installed, it blows up and install fails.
This adds a temporary (hopefully) restriction to match botocore's requirement so that we can successfully install.
Test plan: `pip install -e .` without any angry errors.
> Fix install issues

- starfish/core/spots/DecodeSpots/trace_builders.py
- starfish/core/spots/DecodeSpots/util.py
- starfish/core/spots/FindSpots/blob.py
- starfish/core/spots/FindSpots/local_max_peak_finder.py
- starfish/core/spots/FindSpots/spot_finding_utils.py
- starfish/core/spots/FindSpots/trackpy_local_max_peak_finder.py
- starfish/core/types/__init__.py
- starfish/core/types/_constants.py
- starfish/core/types/_spot_finding_results.py
- starfish/types.py
Changes the return value for every image_to_spots method to PerImageSpotResults, a named tuple that contains the SpotAttributes found in the image as well as any extra information for QC and debugging. The only spot finder that returns extra data at this point is PeakLocalMax which now returns threshold information. 
fixes: #908, #708
> 10.) Formalizing the ability to return extra info from spot finding 

- starfish/core/binary_mask/binary_mask.py
- starfish/core/binary_mask/expand.py
- starfish/core/binary_mask/test/test_binary_mask.py
- starfish/core/binary_mask/util.py
- starfish/test/full_pipelines/api/test_iss_api.py
1. Use typed axes/coordinates when possible.
2. Have `_get_axes_names` return axes/coordinates in the order they are expected in the numpy arrays.
3. Improve how we render the mask names.
Test plan: `pytest starfish/core/binary_mask/test`
> Clean up binary mask

- REQUIREMENTS-STRICT.txt
- REQUIREMENTS.txt
- starfish/REQUIREMENTS-STRICT.txt
- starfish/core/imagestack/test/test_slicedimage_dtype.py
- starfish/core/spots/FindSpots/local_max_peak_finder.py
It's easier to exclude these versions forever and ever than it is to carry around this code workaround, I think.  Please reject if you don't agree. :) 
Also made the DataTypeWarning tests less brittle.  We only care that we raised our warning.  We don't care if others raised warnings.
> Switch to version exclusion for scikit-image workaround

- starfish/core/codebook/codebook.py
- starfish/core/codebook/test/test_to_json.py
This verifies that the two operations are symmetric.
Test plan: this is the test.
> [easy] Test for Codebook.to_json / open_json

- starfish/__init__.py
- starfish/core/binary_mask/_io.py
- starfish/core/binary_mask/binary_mask.py
- starfish/core/binary_mask/expand.py
- starfish/core/binary_mask/test/test_binary_mask.py
- starfish/core/binary_mask/test/test_expand.py
- starfish/core/image/Segment/watershed.py
- starfish/core/segmentation_mask/segmentation_mask.py
- starfish/core/test/test_display.py
LabelImage requires all the pixel coordinate and physical coordinate values along each axis, so to facilitate the easy conversion to and from BinaryMaskCollection and LabelImage, we need to change the data model for BinaryMaskCollection.
Previously, BinaryMaskCollection stored a series of xarrays for each of the masks.  This does not guarantee that the pixel/physical coordinates for every position along each axis.  Furthermore, it duplicates a lot of data.
This new approach stores the coordinates as independent arrays, and then stores each mask as a naked np.ndarray with offsets.  Conversions to and from LabelImage is pretty straightforward.  Returning each mask as an xarray (to maintain compatibility with the existing API) requires generating an xarray on the fly, but is not terribly …
> Update data model for BinaryMaskCollection

- starfish/core/codebook/codebook.py
- starfish/core/codebook/test/test_to_json.py
`to_json` walks through each of the targets/r/c in a codebook when trying to save.  Unfortunately, selecting an array with the same target twice results in a 3D array (target/r/c) rather than a 2D array (r/c).
This PR rewrites to_json so it can handle multiple codewords that decode to the same target.  Rather than selecting by label, we walk through each of the targets by integer offset.  This also optimizes the walkthrough of the codebook object by finding all the non-zero points in numpy code rather than in python code.  With the seqFISH dataset, this is at least a 10x speedup in writing out the json file.  With denser codebooks, the speedup probably is inconsequential.
Test plan: wrote a test that has multiple codewords for the same target.  it crashes without the fix and succeehds …
> Support multiple codewords for the same target

- starfish/core/morphology/object/binary_mask/test/test_binary_mask.py
This results in a binary mask with zero masks.  Verify that this isn't a corner case that doesn't work.
Test plan: this is the test.
Depends on #1631
> Verify that binary masks can be generated from empty label images

- starfish/core/image/Filter/reduce.py
- starfish/core/image/Segment/watershed.py
- starfish/core/imagestack/imagestack.py
- starfish/core/imagestack/parser/_tiledata.py
- starfish/core/imagestack/parser/crop.py
- starfish/core/imagestack/parser/numpy/__init__.py
- starfish/core/imagestack/parser/tileset/_parser.py
- starfish/core/morphology/binary_mask/_io.py
- starfish/core/morphology/binary_mask/binary_mask.py
- starfish/core/morphology/label_image/label_image.py
- starfish/core/morphology/label_image/test/test_label_image.py
- starfish/core/segmentation_mask/segmentation_mask.py
Mostly this is a no-op in terms of complexity, but we got rid of one ugly cast!  Later on, we'll also get some benefits from segmentation code.
Depends on #1649 
Test plan: make -j lint mypy
> Use ArrayLike where appropriate.

- starfish/core/image/Segment/watershed.py
- starfish/core/morphology/binary_mask/binary_mask.py
- starfish/core/morphology/binary_mask/test/test_binary_mask.py
- starfish/core/morphology/label_image/label_image.py
- starfish/core/morphology/label_image/test/test_label_image.py
- starfish/core/morphology/util.py
- starfish/core/test/test_display.py
1. Refactored all the normalization code (i.e., code that handles optional coordinates, code that handles dictionary with differently typed keys) to a couple modules.
2. Renamed `LabelImage.from_array_and_coords` to `LabelImage.from_label_array_and_coords` to be more clear about what it does.
3. Added a docblock to better describe `test_pixel_coordinates` test.
4. Added a test to verify that we correctly normalize coordinates are passed in by string.
Depends on #1631, #1650 
Test plan: `pytest starfish/core/morphology`
> Improve coordinate handling code for BinaryMaskCollection and LabelImage

- starfish/core/morphology/label_image/test/test_label_image.py
Using arrays that have identical cardinality on multiple axes is a bad idea because it can mask serious bugs.  This PR varies the cardinality of the data to avoid this problem.
Test plan: `pytest -v -n4  starfish/core/morphology/object/`
Depends on #1633
> Improve label tests

- starfish/core/morphology/binary_mask/test/test_binary_mask.py
Using arrays that have identical cardinality on multiple axes is a bad idea because it can mask serious bugs.  This PR varies the cardinality of the data to avoid this problem.
Depends on #1632
> Improve binary mask collection tests

- starfish/core/morphology/binary_mask/binary_mask.py
- starfish/core/morphology/binary_mask/test/test_binary_mask.py
The existing builders for binary masks crop the masks to the smallest box that fits the non-zero data.  This adds a method to reverse the crop when retrieving the masks.  Documentation is also added to the builders' docblocks to indicate that they crop the masks.
Note that the constructor of BinaryMaskCollection does _not_ crop the masks.  The builders decide what they want to do.
Depends on #1632
Test plan: Add tests to verify the uncropping works as expected.
> Methods for uncropping binary masks.

- starfish/core/image/Segment/watershed.py
- starfish/core/morphology/binary_mask/binary_mask.py
- starfish/core/morphology/binary_mask/test/test_from_binary_arrays_and_ticks.py
- starfish/core/morphology/binary_mask/test/test_from_label_array_and_ticks.py
1. `from_binary_arrays_and_ticks` will allow morphological filters to take a set of binary masks, run some processing, and produce another set of binary masks.
2. `from_label_array_and_ticks` will allow image processing tools that produce a labeled image and produce a set of binary masks.
`skimage.feature.watershed` is an example of (2), and indeed, we adapt the existing watershed output to use `from_label_array_and_ticks`
Test plan: pass travis, but mostly `make -j lint mypy && pytest -v -n4  starfish/core/morphology/object/`
Depends on #1647
> Additional builders for BinaryMaskCollection

- starfish/core/morphology/binary_mask/test/factories.py
- starfish/core/morphology/binary_mask/test/test_binary_mask.py
- starfish/core/morphology/binary_mask/test/test_from_binary_arrays_and_ticks.py
- starfish/core/morphology/binary_mask/test/test_from_label_array_and_ticks.py
Methods to create label arrays, binary arrays, and binary masks.  This is mostly to reduce a bit of copy pasta, and to make it easier to write simple examples in docblocks.
Depends on #1637
Test plan: `pytest starfish/core/morphology/object/binary_mask/test/`
> Factory methods for binary mask collections

- starfish/core/_display.py
- starfish/core/test/test_display.py
1. on osx, firing viewer.window.close() upon the timer's expiration seems to crash python.  Removing it seems to be ok on osx.  Will test on travis shortly.
2. Fix the synthetic mask we used to test the code.  As it turns out, the labelimage created had only 0 values (rand produces values between 0 and 1, randint is what we really wanted), so it was never exercising the masks code.
3. Fix masks.display() (same as #1663).  This is required to pass travis because (2) now catches the bug.
Test plan: this is mostly tests. :)  https://travis-ci.com/spacetx/starfish/builds/137469517 shows how it works on travis.
> Fix display tests and code

- starfish/core/codebook/codebook.py
- starfish/core/imagestack/imagestack.py
- starfish/core/imagestack/indexing_utils.py
- starfish/core/spots/DecodeSpots/__init__.py
- starfish/core/spots/DecodeSpots/simple_lookup_decoder.py
- starfish/core/spots/DecodeSpots/test/test_composite_codebook.py
- starfish/core/types/_spot_finding_results.py
- Added a slicing method in codebook that allows a user to easily get a portion of the data.
- Added a new SimpleLookupDecoder for non multiplexed data that just makes a table of r/ch keys to target value and decodes. 
- Added a few tests to demonstrate workflows with composite experiment data
> Composite codebook support

- starfish/core/morphology/binary_mask/binary_mask.py
- starfish/core/morphology/binary_mask/test/test_binary_mask.py
This allows a method to be applied to the individual masks and constituted into a new binary mask collection.
Depends on #1653
Test plan: Wrote a test that performed binary dilation on the standard set of masks used for testing, and verified the results were somewhat sane.
> Provide an apply method to binary mask collections.

- starfish/core/image/Filter/bandpass.py
- starfish/core/image/Filter/clip.py
- starfish/core/image/Filter/clip_percentile_to_zero.py
- starfish/core/image/Filter/clip_value_to_zero.py
- starfish/core/image/Filter/gaussian_high_pass.py
- starfish/core/image/Filter/gaussian_low_pass.py
- starfish/core/image/Filter/laplace.py
- starfish/core/image/Filter/mean_high_pass.py
- starfish/core/image/Filter/richardson_lucy_deconvolution.py
- starfish/core/image/Filter/white_tophat.py
- starfish/core/image/_registration/ApplyTransform/warp.py
- starfish/core/imagestack/imagestack.py
- starfish/core/intensity_table/intensity_table.py
- starfish/core/spots/FindSpots/_base.py
- starfish/core/spots/FindSpots/blob.py
- starfish/core/spots/FindSpots/local_max_peak_finder.py
- starfish/core/spots/FindSpots/spot_finding_utils.py
- starfish/core/spots/FindSpots/trackpy_local_max_peak_finder.py
- starfish/core/types/__init__.py
Most places either expect a numpy array or an xarray.  Remove the Union where it's not necessary.
Fixes #1564
> Remove Union[np.ndarray, xr.DataArray]

- Makefile
I think this would generally be better.  The caveat is that occasionally, when I discover an upstream dependency breaks starfish, that the detailed changelog turns out to be useful.
> RFC: Add step to trim the changelog to user-relevant notes.

- starfish/core/morphology/Filter/__init__.py
- starfish/core/morphology/Filter/_base.py
- starfish/core/morphology/Filter/map.py
- starfish/core/morphology/Filter/test/test_map.py
- starfish/core/morphology/binary_mask/binary_mask.py
- starfish/core/types/_functionsource.py
- starfish/morphology.py
This PR introduces filters to take a binary mask collection to produce another binary mask collection.
A map filter is added that can take arbitrary methods in numpy/scipy/skimage and run them against the binary masks.
Depends on #1655
Test plan: Added a simple test that does binary dilation on binary masks.
> Filters for mask collections

- starfish/core/image/Filter/richardson_lucy_deconvolution.py
- starfish/test/full_pipelines/api/test_merfish.py
Richardson Lucy deconv was not passing the user-requested clip method to `apply()`.  This PR adds the missing parameter, and adjusts the expected results accordingly.  As a bonus, the coefficient goes up a bit!
Test plan: `pytest starfish/test/full_pipelines/api/test_merfish.py`
> [easy] Clip method for Richardson Lucy

- starfish/core/_display.py
This PR adds axis labels to `starfish.display()` using the recently-added labeled axis support in `napari` (thanks, @HagaiHargil !).
I added the `axis_labels` keyword argument to the `Viewer` constructor in `_display.py`. 
Currently, I just create a list of the `Axes` `Enum` values. Is there a better way to do this? Maybe get the axes from the stack?
I downloaded and viewed the test data from the ISS example notebook.
> add axis labels to display()

- starfish/core/image/Filter/element_wise_mult.py
- starfish/core/image/Filter/gaussian_high_pass.py
- starfish/core/image/Filter/gaussian_low_pass.py
- starfish/core/image/Filter/mean_high_pass.py
- starfish/core/image/Filter/reduce.py
- starfish/core/imagestack/imagestack.py
- starfish/core/intensity_table/intensity_table.py
- starfish/core/types/__init__.py
- starfish/core/types/_constants.py
- starfish/core/util/levels.py
- starfish/core/util/test/test_levels.py
- starfish/core/util/test/test_preserve_float_range.py
- starfish/types.py
Clip is nice and useful, but doesn't allow for the expansion of dynamic range when the peak intensity is less than fully saturated.
This PR adds linear image leveling.  Five modes are offered:
1. Clip supersaturated values.
2. Scale by the peak intensity of the entire image if any part of the image is supersaturated.
3. Scale by the peak intensity of each image chunk if any part of the image chunk is supersaturated.
4. Scale by the peak intensity of the entire image.
5. Scale by the peak intensity of each image chunk.
1-3 matches the existing modes of Clip, so we reimplement Clip using the new linear image leveler.
Test plan: Add test cases for the new image leveling approaches.  Existing Clip tests pass.
> Linear image leveling

- starfish/core/morphology/Filter/map.py
#1654 removed one level of the hierarchy.  The documentation didn't get updated correctly.  The See Also is also a copy-pasta that's not relevant.
Test plan: none whatsoever.
> [easy] fix docs for morphology.Filter.map

- starfish/core/image/Filter/bandpass.py
- starfish/core/image/Filter/element_wise_mult.py
- starfish/core/image/Filter/gaussian_high_pass.py
- starfish/core/image/Filter/gaussian_low_pass.py
- starfish/core/image/Filter/laplace.py
- starfish/core/image/Filter/linear_unmixing.py
- starfish/core/image/Filter/map.py
- starfish/core/image/Filter/mean_high_pass.py
- starfish/core/image/Filter/reduce.py
- starfish/core/image/Filter/richardson_lucy_deconvolution.py
- starfish/core/image/Filter/white_tophat.py
- starfish/core/imagestack/imagestack.py
- starfish/core/types/_constants.py
Adjusts all the filters to use levels instead of clip/preserve_float_range.  `clip_method` is still supported though deprecated.  If both are provided, an exception is thrown.  If `clip_method` by itself is provided, then a deprecation warning is printed and the `clip_method` is translated to the appropriate `levels_method`.
Depends on #1666, #1668
Test plan: this is an -alltest branch since it affects so much code.  if goes green, we should presumably be good. :)
> Use the new levels module.

- starfish/core/image/Segment/watershed.py
#1652 replaced a block of code that scales the intensity of the image by the max, with a reduce operation that does Clip.SCALE_BY_IMAGE.  As I discovered later, Clip.SCALE_BY_IMAGE does not do what the documentation says it does, and in fact, it only scales by the max intensity if the max intensity is > 1.0.  That means it's not a refactor and actually affected the output.
Levels.SCALE_BY_IMAGE, however, does what we want here and can do what we originally had here.
Depends on #1669
Test plan: pretty much none.
> Fix stain generation in watershed

- starfish/core/morphology/Filter/areafilter.py
- starfish/core/morphology/Filter/test/test_areafilter.py
This filter allows us to filter a BinaryMaskCollection based on the size of the masks.
Test plan: Added some basic test cases.
> Area filter for binary masks

- starfish/core/morphology/Binarize/__init__.py
- starfish/core/morphology/Binarize/_base.py
- starfish/core/morphology/Binarize/test/test_threshold.py
- starfish/core/morphology/Binarize/threshold.py
BinarizeImage takes an ImageStack and binarizes it into a BinaryMaskCollection.
Depends on #1637
Test plan: add tests for simple binarizing, and to test the input requirements.
> Thresholded binarize conversion algorithm

- starfish/core/spots/DetectPixels/combine_adjacent_features.py
- starfish/test/full_pipelines/api/test_merfish.py
Fixes: #1273 
Added small test
> [easy] adding spot ids to pixel results

- starfish/core/image/Filter/util.py
- starfish/core/image/Segment/watershed.py
Refactor the existing watershed code to use the new binarizer and mask filtering (for binary opening).
Depends on #1670, #1651
Test plan: still see 69 cells in the iss notebook.
> Use thresholded binarize and mask filtering in existing watershed code.

- starfish/core/morphology/binary_mask/binary_mask.py
- starfish/core/morphology/binary_mask/expand.py
xarray prefers to be indexed with a tuple of selectors rather than a sequence.  Update the API to generate tuples and use them instead.
Test plan: Saw fewer deprecation warnings in the test console.
> [easy] fix deprecation warnings for indexing using a sequence

- starfish/core/morphology/util.py
This works for both pixel and physical ticks.
> [easy] utility function to test equality of two sets of tick markers.

- docs/source/api/data_structures/binary_mask.rst
- docs/source/api/data_structures/index.rst
- docs/source/api/data_structures/label_image.rst
- docs/source/api/index.rst
- docs/source/api/morphology/index.rst
- docs/source/api/types/index.rst
- starfish/core/morphology/binary_mask/binary_mask.py
- starfish/core/morphology/label_image/label_image.py
- starfish/core/types/_constants.py
- starfish/morphology.py
- Added top-level .rst files for a bunch of packages/modules that should be autodoc'ed.
- Fixed places where things didn't generate correctly.
- Added top-level constructs to starfish.morphology
- Fixed inadvertent copy-pasta in `starfish/core/types/_constants.py`
Test plan: `make docs-html lint mypy`
> Fix docs build

- starfish/core/morphology/Filter/__init__.py
- starfish/core/morphology/Filter/reduce.py
- starfish/core/morphology/Filter/test/test_reduce.py
- starfish/core/morphology/binary_mask/binary_mask.py
- starfish/core/morphology/binary_mask/test/test_binary_mask.py
This is the counterpart to the apply provided in #1655.
Depends on #1686 
Test plan: Added a test that reduced using xors. Because we have boring test data that don't overlap, this is one way of generating interesting output.
> Mechanism to reduce multiple masks into one

- starfish/core/morphology/binary_mask/test/factories.py
None of the arguments should be required.
Test plan: used in a separate PR.
> [easy] fix factory for 3d binary mask collections

- starfish/core/image/Segment/watershed.py
- Get rid of the remaining naked numpy arrays and replace them with ImageStacks.
- Use ImageStack.reduce rather than instantiating a Reduce Filter and applying it.
Depends on #1686 
Test plan: ran iss notebook and found 69 cells.
> Clean up watershed (again)

- docs/source/api/morphology/index.rst
- starfish/core/morphology/Merge/__init__.py
- starfish/core/morphology/Merge/_base.py
- starfish/core/morphology/Merge/simple.py
- starfish/core/morphology/Merge/test/test_simple.py
- starfish/morphology.py
This does not handle the case where the pixel/physical ticks do not line up.  This is for cases where we derive the data from the exact same set of images, and inherit their pixel/physical ticks from the same source.
Depends on #1690, #1691, #1696
Test plan: Added one positive test case, and tested the cases where the merge should fail.
> Pipeline component and implementation for merging BinaryMaskCollections

- starfish/core/spots/AssignTargets/label.py
If 3D data is present, use it to limit target assignment.  If zplane information is not available, just set the bounds to -inf,+inf.
Part of #53.  This fixes @dganguli's [comment](https://github.com/spacetx/starfish/issues/53#issuecomment-364592217) dated from Feb 9, 2018!
> Add 3D support to target assignment.

- starfish/core/morphology/Binarize/__init__.py
- starfish/core/morphology/Binarize/watershed.py
This PR adds a Binarizer that effectively wraps skimage's watershed implementation.
Test plan: used in subsequent PR.
> Wrap skimage's watershed

- docs/source/getting_started/installation/index.rst
I dug into it a bit more and the issue is that installing scikit-image from source requires numpy to already be installed.  Typically, scikit-image is installed from prebuilt binaries, which circumvents the issue.  However, scikit-image has not declared itself fully compatible with python3.8, and as such, is not producing prebuilt binaries.
> [easy] Document workaround for python3.8

- .travis.yml
- starfish/core/test/test_display.py
1. Two sets of napari tests -- one against pinned dependencies and one against latest.  This way, we can understand where things break.
2. Use `pytest-qt` to run napari tests.  Use the qtbot fixture.
3. Run napari tests on branches with `napari` in the name.
Test plan: tests die at the same place as it did previously
> Modernize napari tests.

- readthedocs.yml
this brings readthedocs up to speed with @ttung 's changes in #1709 , un-breaking the builds
> [EASY] updates readthedocs requirements

- requirements/REQUIREMENTS-NAPARI-CI.txt
- starfish/core/test/test_display.py
This passes everything except for the starfish+"latest napari" test.
> Move napari pin back to 0.2.6 for CI purposes

- docs/source/conf.py
docs currently are not building on readthedocs b/c the relative path to the logo for sphinx-gallery cannot be resolved.
this PR fixes the build by calling the absolute path
test plan: build on readthedocs. https://readthedocs.org/projects/spacetx-starfish/builds/10211763/
> [EASY] fixes path to logo for sphinx-gallery

- starfish/core/morphology/Merge/_base.py
- starfish/core/morphology/Merge/simple.py
It turns out that sphinx skips classes with documentation identical to the superclass, even if the individual methods have different documentation.  Right now, the documentation for SimpleMerge isn't being outputted.  With this PR, the documentation is generated.
Test plan: `make docs-html`
> Fix autodoc of SimpleMerge

- docs/source/getting_started/loading_data/index.rst
The example datasets are documented in the API section.  This may make it easier to find.
> Link to the available datasets in "loading data" section

- REQUIREMENTS.txt
`DataArray.drop_sel` was added in 0.14.1.  The old API (removed in #1683) is being deprecated so we are want the new API.  However, that is only added in 0.14.1.
Fixes: #1726
Test plan: make -j fast
> Move xarray to 0.14.1

- starfish/core/image/Segment/watershed.py
- starfish/test/full_pipelines/api/test_iss_api.py
Uses the labeling algorithms provided by #1680 and the area filter from #1673 to implement labeling.
Depends on #1671, #1673, #1680
Test plan: ISS notebook yields 96 cells.  The previous implementation did not support 3D and flattened everything along the Z axis.  Processing in 3D exposed issues in `peak_local_max`.  If we use the footprint + exclude borders approach, there is an off-by-one error in trimming the Z axis, resulting in completely blank images and no peaks.  Therefore, we have to exclude the borders.  Because of that, we detect more cells.
> Refactor watershed's label image generation using the new API

- starfish/core/image/Filter/util.py
- starfish/core/image/Segment/watershed.py
Remove starfish.core.image.Filter.util.bin_open as there are no more users of this method.
Depends on #1692, #1693, #1684, #1688
Test plan: ISS notebook still yields 96 cells.
> Refactor watershed mask creation using new API

- starfish/core/image/Segment/watershed.py
Use the component from #1700 to replace the remaining procedural code in the existing watershed component.
Depends on #1700, #1699, #1694
Test plan: visually the ISS notebook looks the same.
> Use the new watershed component to finish componentizing the existing watershed

- docs/source/api/types/index.rst
- starfish/core/image/Filter/bandpass.py
- starfish/core/image/Filter/element_wise_mult.py
- starfish/core/image/Filter/gaussian_high_pass.py
- starfish/core/image/Filter/gaussian_low_pass.py
- starfish/core/image/Filter/laplace.py
- starfish/core/image/Filter/linear_unmixing.py
- starfish/core/image/Filter/map.py
- starfish/core/image/Filter/mean_high_pass.py
- starfish/core/image/Filter/reduce.py
- starfish/core/image/Filter/richardson_lucy_deconvolution.py
- starfish/core/image/Filter/white_tophat.py
- starfish/core/imagestack/imagestack.py
- starfish/core/types/__init__.py
- starfish/types.py
It has been deprecated in favor of Clip.
Test plan: make -j fast
Depends on #1724
Fixes #1723
> Remove starfish.types.Clip

- starfish/core/morphology/Filter/areafilter.py
- starfish/core/morphology/Filter/test/test_areafilter.py
This re-adds the positional argument style for specifying AreaFilter, while displaying a warning that it's deprecated.
Fixes #1734
Test plan: Add tests to cover the old style and the illegal path of specifying both positional and keyword arguments
> Support old argument style for AreaFilter

- starfish/core/morphology/binary_mask/binary_mask.py
Ex. if someone saves the output of ilastik object classification as a tiff file
> Adding method to binary mask collection that imports external labeled images

- starfish/data.py
> adding mouse v human example to starfish.data

- starfish/core/experiment/builder/test/structured_formatter/util.py
- starfish/core/test/test_multiprocessing_workflow.py
It's defined elsewhere, with nearly identical code.
Test plan: make -j fast-test mypy lint
> Remove duplicate UniqueTiles

- starfish/core/imagestack/imagestack.py
- starfish/core/imagestack/parser/tilefetcher/__init__.py
- starfish/core/imagestack/parser/tilefetcher/_parser.py
- starfish/core/imagestack/test/test_from_tilefetcher.py
1. Add a parser from TileFetcher to the TileCollectionData.
2. Add a top-level classmethod to wrap a TileFetcher and produce an ImageStack.
3. Add a test to verify this functionality.
Test plan: Tests pass.
Fixes: #1603
Depends on #1736, #1738
> Create a TileFetcher-based constructor for ImageStack

- REQUIREMENTS.txt
- starfish/core/image/Filter/__init__.py
- starfish/core/image/Filter/ilastik_pre_trained_probability.py
Creates a IlastikPretrainedProbability that takes in the path to an ilastick executable file, and ilastick project file and an Imagestack and runs ilastick headless to apply the pretrained prediction model to the Imagestack. The output of ilastik is then loaded back in as an ImageStack. 
Test plan: So I tested everything locally but not sure how to write a unit test without having to install ilastick on travis...
fixes: #1499
> New IlastikPretrainedProbability filter 

- starfish/core/image/Filter/clip.py
- starfish/core/image/Filter/clip_percentile_to_zero.py
- starfish/core/image/Filter/clip_value_to_zero.py
> Add level_method to the clip filters.

- requirements/REQUIREMENTS-CI.txt
- requirements/REQUIREMENTS-NAPARI-CI.txt
- starfish/REQUIREMENTS-STRICT.txt
#1740 added h5py but not to the pinned requirements files.  That resulted in unhappy travis runs (e.g., https://travis-ci.com/spacetx/starfish/builds/146897038)
Test plan: none
> [easy] add h5py to pinned requirements

- starfish/core/config/__init__.py
- starfish/core/config/test/test_config.py
STARFISH_VALIDATION_STRICT and STARFISH_VERBOSE should take precedence over the file config and STARFISH_CONFIG
Test plan: Added a test that verifies tho correct behavior.
> Specific config environment variables should override file config and STARFISH_CONFIG

- starfish/core/imagestack/imagestack.py
- starfish/core/morphology/Binarize/threshold.py
Added the documentation for the `tile_opener` argument.
Fixes #1786
> [easy] Fix documentation for ImageStack.export

- examples/data_loading/plot_tilefetcher_loader.py
- starfish/core/imagestack/imagestack.py
- starfish/core/imagestack/parser/_tiledata.py
- starfish/core/imagestack/parser/crop.py
- starfish/core/imagestack/parser/numpy/__init__.py
- starfish/core/imagestack/parser/tilefetcher/_parser.py
- starfish/core/imagestack/parser/tileset/_parser.py
- starfish/core/imagestack/test/test_from_tilefetcher.py
When we construct an ImageStack from a tilefetcher, we now allow accept a `group_by` parameter which controls how we load the data.  If an axis is in the `group_by`, then we load all the data for any given value for that axis before moving on to another value for that axis.
For instance, if Axes.ROUND is in `group_by`, then we will load all the data for round=0 before we load the data for round=1.
Test plan: Added tests to verify that the loader works with a variety of `group_by`s.  Dan Goodwin's 3D data loads in 100seconds now instead of 10 minutes.
> Add group_by for tilefetcher-based ImageStack construction

- starfish/core/intensity_table/decoded_intensity_table.py
- starfish/test/full_pipelines/api/test_iss_api.py
Fixes: #1392
Removes 'nan' as a target value in ExpressionMatrix and reformats is as a metadata column called 'number_of_undecoded_spots`.  Also renames the 'nan' cell_id row to "unassigned".
> removing nan propagation to expression matrix

- starfish/core/__init__.py
- starfish/core/_version.py
By removing the type: ignore at the top of starfish/core/_version.py, it now behaves correctly.
Test plan: `make -j lint mypy`
Fixes #1766
> [easy] Remove # type: ignore for get_versions

- examples/pipelines/iss_pipeline.py
Now that #700 has landed, we no longer need to disable validation.
Depends on #1792
Fixes #1779
> [easy] Validate iss experiment.json file

- starfish/core/codebook/codebook.py
- starfish/core/codebook/test/test_from_code_array.py
1. Explicitly check for the codeword entry not being a dictionary.
2. Explicitly check for the required fields in a codeword entry.
3. Improve comments in test.
Fixes #1777
> improve from_code_array validation

- starfish/core/codebook/codebook.py
- starfish/core/codebook/test/test_synthetic_one_hot_codebook.py
> [easy] Clearer exception for when n_codes does not match the number of target names

- starfish/core/spots/FindSpots/trackpy_local_max_peak_finder.py
ImageStacks are always 5D, so spot detection should always expect a 3D images (no R/C).
Fixes #1778
> [easy] Remove workaround for non-3D images

- starfish/core/image/Filter/test/test_api_contract.py
This statement is not true.  Some filters will never accept is_volume (i.e., Reduce), so it is not generalizable.
Test plan: `pytest -v -n4 starfish/core/image/Filter/test`
Fixes #1772
> Remove TODO re is_volume

- starfish/core/morphology/binary_mask/binary_mask.py
- starfish/core/morphology/binary_mask/test/test_from_binary_arrays_and_ticks.py
Through most ways of constructing BinaryMaskCollections, we calculate region properties and store them with our BinaryMaskCollection.  However, on a few code paths (notably `from_binary_arrays_and_ticks` and `from_fiji_roi_set`), we calculate the regionprops on demand.
This code path was not properly tested and we were not generating the regionprops correctly.  This fixes the problem and adds a quick sanity test.
Test plan: test passes with changes, does not otherwise.
> Fix on-demand calculation of BinaryMaskCollection's regionprops

- starfish/core/spots/FindSpots/trackpy_local_max_peak_finder.py
1. is_volume is deprecated and documentation removed.
2. if someone passes in is_volume=False, we raise an error.
3. if someone passes in is_volume=True, we raise a warning.
Fixes #1818
> Deprecate is_volume parameter with trackpy

- starfish/core/spots/FindSpots/local_max_peak_finder.py
- starfish/core/spots/FindSpots/test/test_spot_detection.py
- starfish/core/types/_spot_attributes.py
- starfish/core/types/_spot_finding_results.py
1. Thread the `is_volume` parameter through, and use that to determine which axes to group by.
2. `image_to_spots` now takes an xarray, and uses the `Z` data on the xarray coordinate to record the z data in cases where we group by 2d slices.
3. Call spot detection on the reference image using `ImageStack.transform` so we can use axes grouping.
4. Add the ability to combine spot attributes by R/C.  This is because `SpotFindingResults` is organized by R/C and not by R/C/Z.
Test plan: Added spot detection tests with 2D spot detectors.  Because the spots on the different zplanes are now considered separate, we see a lot more spots.
Fixes #1815
> Ensure that LocalMaxPeakFinder works in 3D

- docs/source/contributing/index.rst
- docs/source/index.rst
Explained user support is moving from slack to image.sc, which should meet community partner requirement for image.sc.
> point users to image.sc forum

- starfish/core/spots/FindSpots/local_max_peak_finder.py
- starfish/core/spots/FindSpots/test/test_local_max_peak_finder.py
Test plan: run spot detection on a spot that's uniformly illuminated.  Without the `num_peaks_per_label=1` kwarg, it finds a peak at each pixel.  With the kwarg, it finds only 1 peak.
> Add support for kwargs to peak_local_max

- Makefile
Related to https://github.com/napari/napari/issues/1036
Test plan: use a branch that contains `napari` which should trigger the napari CI components.
> Napari seems to want a newer version of pip

- docs/source/contributing/index.rst
- docs/source/index.rst
Now that we're officially a community partner on image.sc we can link directly to the starfish tag feed.
> link to image.sc/tag/starfish

- .travis.yml
- Makefile
To achieve the pin, we install based on requirements/REQUIREMENTS-NAPARI-CI.txt **before** we run make install-dev.  Unfortunately, install-dev is where we upgrade pip such that it doesn't choke on napari.  This should hopefully fix the issue where napari test is broken.
Test plan: branch name has napari, so it should run the napari test
> Fix the travis test where we pin the napari version

- docs/source/usage/index.rst
- examples/data_formatting/README.txt
- examples/how_to/blob_detector.py
- starfish/spacetx_format/README.md
Fixed broken links to "SpaceTx Format", "codebook", and "data formatting examples"
> fixed broken links in Starfish Usage

- docs/source/contributing/index.rst
- docs/source/getting_started/installation/index.rst
See it on read the docs [here](https://spacetx-starfish.readthedocs.io/en/mcai-installation-doc/)
List of changes:
* Emphasized recommendation to use Python 3.7
* Added clarification for using venv and Jupyter notebooks
* Moved installation for developers to 'Contributing to starfish'
* Changed installation for windows section to no longer use WSL
> Update starfish installation guide for JOSS submission

- starfish/core/spots/AssignTargets/label.py
- starfish/core/spots/DecodeSpots/trace_builders.py
Two bug fixes:
1. Made `build_traces_sequential` reassign unique `spot_id`s to every feature after concatenating `PerImageSliceResults`.
2. Made `Label._assign()` explicitly label features by `spot_id` instead of row number, ensuring that labeling is accurate even when `spot_id`s do not match row numbers in an `IntensityTable`. `Spot_id`s must still be unique for accurate labeling though.
> fix how spot_ids are handled by build_traces_sequential and Label._assign()

- requirements/REQUIREMENTS-NAPARI-CI.txt
- requirements/REQUIREMENTS-NAPARI-CI.txt.in
- setup.py
- starfish/core/_display.py
- starfish/core/test/test_display.py
Napari installation will by default not install a backend.  This selects the default napari backend (PyQt5)
> Bump napari to 0.3.4

- Makefile
pip installs setuptools and wheel implicitly.  As a result, neither of these packages show up in our requirements.txt.  As such, we never install newer versions of these packages.  Any package that expects a newer version of these packages will break.  In this case, xarray wants setuptools 41.2+, but pip won't try to upgrade that because it's installed by default.
This PR changes our install flow to force reinstall and upgrade everything requested to ensure we pick up the right packages.
Test plan: `make release-env` produces a working environment.
> Upgrade setuptools and wheel

- Makefile
Don't force-reinstall as that can cause conflicts with environments with distutils-installed packages.
Fixes #1922
> Ignore requirements that are already satisfied

- starfish/core/spots/DecodeSpots/trace_builders.py
- starfish/core/spots/DecodeSpots/util.py
A starfish user wants to try the Nearest Neighbor Trace Builder but had issues because the `IntensityTable` was [missing the `spot_id` coord and `features` dim](https://forum.image.sc/t/unable-to-retrieve-values-from-decodedintensitytable/44913). This pull request adds those to the `IntensityTable` so a full starfish pipeline (as demonstrated in the [Quick Start tutorial](https://spacetx-starfish.readthedocs.io/en/latest/gallery/quick_start/plot_quick_start.html)) can be built and run. This does not necessarily mean the Nearest Neighbor Trace Builder will give satisfactory results when tested on real data.
> Add necessary coords for IntensityTable when using Nearest Neighbors strategy

- starfish/core/compat.py
It was [moved to skimage.exposure @ 0.16.0](https://scikit-image.org/docs/0.16.x/release_notes_and_installation.html#deprecations)
Fixes: #1932
Test plan: Travis
> Import match_histograms from skimage.exposure

- .travis.yml
- Makefile
Always upgrade to $PIP_VERSION.
A couple minor changes:
1. Add a pip freeze to the test workflows to ensure we know what's being installed.
2. Do not include pip in requirements.txt because windows freaks out if it's asked to install pip in a requirements.txt file.
> Upgrade to a consistent version of pip in all workflows

- REQUIREMENTS.txt
- starfish/core/morphology/Filter/min_distance_label.py
- starfish/test/full_pipelines/api/test_iss_api.py
Before this change, multiple local maxima were returned even within the min_distance if their values were identical. This lead to over-segmentation in some cases.
See #2006
> Add min_distance parameter to peak_local_max call

- starfish/core/spots/FindSpots/blob.py
Replaced np.sqrt(3) with np.sqrt(2) when calculating 2d blob radius.
Close issue #2022
> fixing blob radius calculation in 2d

- CHANGELOG.md
- examples/pipelines/baristaseq_pipeline.py
- examples/pipelines/data
- setup.cfg
Following the "Deployment" steps in the Makefile, I have done the following:
1) Updated the CHANGELOG.md file 
2) Made some minor corrections to resolve errors when running example pipelines
3) Corrected the "Windows" Operating System classifier in setup.cfg
I have also uploaded the package to TestPyPI, but couldn't `pip install ...` as some dependencies don't work via testpypi.
> Release 0.3.0

- starfish/core/image/Filter/bandpass.py
- starfish/core/image/Filter/mean_high_pass.py
- starfish/core/spots/DecodeSpots/test/test_nearest_neighbor_trace_builder.py
- starfish/core/test/factories.py
> Replace scipy.ndimage.filters with scipy.ndimage for scipy v2 support

- CHANGELOG.md
Updating CHANGELOG.md before tagging and releasing 0.3.2
> Updating CHANGELOG.md for release 0.3.2

- starfish/core/spots/FindSpots/blob.py
This closes #2003 
Fixed 2 bugs in blob.py that were discovered when running the BlobDetector how-to example:
https://spacetx-starfish.readthedocs.io/en/latest/gallery/how_to/blob_detector.html#howto-blobdetector
1. Replaced deprecated pandas append() with concat()
2. Fixed the shape of `intensities` in 2d by adding the index `z_inds` as it is still used although it is set to zero.
> fix: blob.py 2d intensities shape and pd.concat instead of append

- .github/workflows/starfish-prod-ci.yml
Thanks to @iimog work on fixing #2062 with #2063 (setting normalization=None instead of default "phase" in starfish wrapper for scikit-image.registration.phase_cross_correlation() and adjusting expected values), it seems that we can now add MacOS to `.github/workflows/starfish-prod-ci.yml` without failing tests. As there is no normalization in the image registration step, we don't get the slight differences in arithmetic calculations on Intel hardware vs. Apple silicon (probably FFT implementation but not important).
> add MacOS to Github actions workflow

- requirements/REQUIREMENTS-CI.txt.in
This closes #2077 by circumventing dependabot bug when handling relative paths of constraint files.
This will allow dependabot to resume its role to open PRs for security updates.
> fix: changing pip install flag from -c to -r due to dependabot relative path error
